// generated in ./lib/models
export default {
  "adjectives": {
    "f": {
      "fwd": "1:os,a",
      "both": "1:ão,ó,z,e¦2:em,el,il¦3:aso,zul¦4a:nhol¦éia:eu¦esa:ês¦á:au¦a:o",
      "rev": "4:anja¦1m:oa¦2s:co¦3s:ito",
      "ex": "2a:bom"
    },
    "mp": {
      "fwd": "s:¦eis:il",
      "both": "1:ó¦3:nja¦2es:mão¦2is:vel¦2a:itos¦1óis:hol¦1es:z¦1is:ul¦1a:cos¦eses:ês¦ns:m",
      "rev": "1:os,us¦2:ves,des,tes¦3:bres,oces¦4:remes¦1il:ceis¦1o:sa",
      "ex": "3a:raso"
    },
    "fp": {
      "fwd": "2:os¦eis:il¦1is:el",
      "both": "3:nja¦4ias:ropeu¦3s:aso¦2as:ol¦2es:iz¦1s:ão,e¦1ns:em¦1as:om¦1is:ul¦esas:ês¦ás:au¦as:o",
      "rev": "1:ó¦3:cos¦4:itos¦1il:ceis¦2l:veis",
      "ex": "2:só"
    }
  },
  "conditional": {
    "first": {
      "fwd": "ia:¦oria:ôr¦coitaria:çoitar¦1ria:izer¦2ria:fazer¦2caria:inçar",
      "both": "4ria:sprazer¦3caria:troçar,braçar",
      "rev": "2:eria,iria,oria¦3:maria,daria,laria,taria,garia,çaria,oaria,haria,varia,saria,jaria,paria,baria,zaria,naria,iaria,earia,uaria,xaria¦4:ncaria,traria,araria,oraria,uraria,iraria,icaria,ucaria,nraria,graria,braria,eraria,rraria,draria,rcaria,ecaria,scaria,fraria,lcaria,ufaria,craria,lraria,vraria,ofaria,ifaria,afaria,lfaria¦5:mpraria,locaria,vocaria,opraria,tacaria,hocaria,focaria,lacaria,upraria,pocaria,bocaria,pacaria,hacaria,arfaria,tocaria¦2çar:mocaria¦3zer:sfaria,sdiria,ldiria,-faria¦4zer:radiria,endiria,mefaria,safaria,erdiria¦4çar:trincaria¦5zer:trafaria,rrefaria",
      "ex": "2ria:fazer,dizer¦3ria:trazer,afazer¦2caria:coçar,roçar,laçar¦3caria:calçar,forçar,atiçar¦4caria:remoçar¦2ia:ir¦3ia:dar¦1oria:pôr¦5ia:tocar,focar,tacar,sacar,locar,socar,arfar¦4ria:refazer,redizer¦6ia:trocar,brocar,blefar,surfar¦4ia:orar,irar,arar,erar¦5ria:condizer,perfazer,predizer¦10ia:reciprocar,embasbacar¦8ia:triunfar,derrocar,atarefar¦7ia:atracar,xerocar,ensacar,assacar¦1coitaria:açoitar¦7ria:putrefazer,liquefazer¦6ria:rarefazer¦9ia:atarracar,esburacar"
    },
    "second": {
      "fwd": "ias:¦orias:ôr¦coitarias:çoitar¦1rias:izer¦2rias:fazer¦2carias:inçar",
      "both": "4rias:sprazer¦3carias:troçar,braçar",
      "rev": "2:erias,irias,orias¦3:marias,darias,larias,tarias,garias,çarias,oarias,harias,varias,sarias,jarias,parias,barias,zarias,narias,iarias,earias,uarias,xarias¦4:ncarias,trarias,ararias,orarias,urarias,irarias,icarias,ucarias,nrarias,grarias,brarias,erarias,rrarias,drarias,rcarias,ecarias,scarias,frarias,lcarias,ufarias,crarias,lrarias,vrarias,ofarias,ifarias,afarias,lfarias¦5:mprarias,locarias,vocarias,oprarias,tacarias,hocarias,focarias,lacarias,uprarias,pocarias,bocarias,pacarias,hacarias,arfarias,tocarias¦2çar:mocarias¦3zer:sfarias,sdirias,ldirias,-farias¦4zer:radirias,endirias,mefarias,safarias,erdirias¦4çar:trincarias¦5zer:trafarias,rrefarias",
      "ex": "2rias:fazer,dizer¦3rias:trazer,afazer¦2carias:coçar,roçar,laçar¦3carias:calçar,forçar,atiçar¦4carias:remoçar¦2ias:ir¦3ias:dar¦1orias:pôr¦5ias:tocar,focar,tacar,sacar,locar,socar,arfar¦4rias:refazer,redizer¦6ias:trocar,brocar,blefar,surfar¦4ias:orar,irar,arar,erar¦5rias:condizer,perfazer,predizer¦10ias:reciprocar,embasbacar¦8ias:triunfar,derrocar,atarefar¦7ias:atracar,xerocar,ensacar,assacar¦1coitarias:açoitar¦7rias:putrefazer,liquefazer¦6rias:rarefazer¦9ias:atarracar,esburacar"
    },
    "third": {
      "fwd": "ia:¦oria:ôr¦coitaria:çoitar¦1ria:izer¦2ria:fazer¦2caria:inçar",
      "both": "4ria:sprazer¦3caria:troçar,braçar",
      "rev": "2:eria,iria,oria¦3:maria,daria,laria,taria,garia,çaria,oaria,haria,varia,saria,jaria,paria,baria,zaria,naria,iaria,earia,uaria,xaria¦4:ncaria,traria,araria,oraria,uraria,iraria,icaria,ucaria,nraria,graria,braria,eraria,rraria,draria,rcaria,ecaria,scaria,fraria,lcaria,ufaria,craria,lraria,vraria,ofaria,ifaria,afaria,lfaria¦5:mpraria,locaria,vocaria,opraria,tacaria,hocaria,focaria,lacaria,upraria,pocaria,bocaria,pacaria,hacaria,arfaria,tocaria¦2çar:mocaria¦3zer:sfaria,sdiria,ldiria,-faria¦4zer:radiria,endiria,mefaria,safaria,erdiria¦4çar:trincaria¦5zer:trafaria,rrefaria",
      "ex": "2ria:fazer,dizer¦3ria:trazer,afazer¦2caria:coçar,roçar,laçar¦3caria:calçar,forçar,atiçar¦4caria:remoçar¦2ia:ir¦3ia:dar¦1oria:pôr¦5ia:tocar,focar,tacar,sacar,locar,socar,arfar¦4ria:refazer,redizer¦6ia:trocar,brocar,blefar,surfar¦4ia:orar,irar,arar,erar¦5ria:condizer,perfazer,predizer¦10ia:reciprocar,embasbacar¦8ia:triunfar,derrocar,atarefar¦7ia:atracar,xerocar,ensacar,assacar¦1coitaria:açoitar¦7ria:putrefazer,liquefazer¦6ria:rarefazer¦9ia:atarracar,esburacar"
    },
    "firstPlural": {
      "fwd": "íamos:¦oríamos:ôr¦coitaríamos:çoitar¦1ríamos:izer¦2ríamos:fazer¦2caríamos:inçar",
      "both": "4ríamos:sprazer¦3caríamos:troçar,braçar",
      "rev": "2:eríamos,iríamos,oríamos¦3:maríamos,daríamos,laríamos,taríamos,garíamos,çaríamos,oaríamos,haríamos,varíamos,saríamos,jaríamos,paríamos,baríamos,zaríamos,naríamos,iaríamos,earíamos,uaríamos,xaríamos¦4:ncaríamos,traríamos,araríamos,oraríamos,uraríamos,iraríamos,icaríamos,ucaríamos,nraríamos,graríamos,braríamos,eraríamos,rraríamos,draríamos,rcaríamos,ecaríamos,scaríamos,fraríamos,lcaríamos,ufaríamos,craríamos,lraríamos,vraríamos,ofaríamos,ifaríamos,afaríamos,lfaríamos¦5:mpraríamos,locaríamos,vocaríamos,opraríamos,tacaríamos,hocaríamos,focaríamos,lacaríamos,upraríamos,pocaríamos,bocaríamos,pacaríamos,hacaríamos,arfaríamos,tocaríamos¦2çar:mocaríamos¦3zer:sfaríamos,sdiríamos,ldiríamos,-faríamos¦4zer:radiríamos,endiríamos,mefaríamos,safaríamos,erdiríamos¦4çar:trincaríamos¦5zer:trafaríamos,rrefaríamos",
      "ex": "2ríamos:fazer,dizer¦3ríamos:trazer,afazer¦2caríamos:coçar,roçar,laçar¦3caríamos:calçar,forçar,atiçar¦4caríamos:remoçar¦2íamos:ir¦3íamos:dar¦1oríamos:pôr¦5íamos:tocar,focar,tacar,sacar,locar,socar,arfar¦4ríamos:refazer,redizer¦6íamos:trocar,brocar,blefar,surfar¦4íamos:orar,irar,arar,erar¦5ríamos:condizer,perfazer,predizer¦10íamos:reciprocar,embasbacar¦8íamos:triunfar,derrocar,atarefar¦7íamos:atracar,xerocar,ensacar,assacar¦1coitaríamos:açoitar¦7ríamos:putrefazer,liquefazer¦6ríamos:rarefazer¦9íamos:atarracar,esburacar"
    },
    "secondPlural": {
      "fwd": "íeis:¦oríeis:ôr¦coitaríeis:çoitar¦1ríeis:izer¦2ríeis:fazer¦2caríeis:inçar",
      "both": "4ríeis:sprazer¦3caríeis:troçar,braçar",
      "rev": "2:eríeis,iríeis,oríeis¦3:maríeis,daríeis,laríeis,taríeis,garíeis,çaríeis,oaríeis,haríeis,varíeis,saríeis,jaríeis,paríeis,baríeis,zaríeis,naríeis,iaríeis,earíeis,uaríeis,xaríeis¦4:ncaríeis,traríeis,araríeis,oraríeis,uraríeis,iraríeis,icaríeis,ucaríeis,nraríeis,graríeis,braríeis,eraríeis,rraríeis,draríeis,rcaríeis,ecaríeis,scaríeis,fraríeis,lcaríeis,ufaríeis,craríeis,lraríeis,vraríeis,ofaríeis,ifaríeis,afaríeis,lfaríeis¦5:mpraríeis,locaríeis,vocaríeis,opraríeis,tacaríeis,hocaríeis,focaríeis,lacaríeis,upraríeis,pocaríeis,bocaríeis,pacaríeis,hacaríeis,arfaríeis,tocaríeis¦2çar:mocaríeis¦3zer:sfaríeis,sdiríeis,ldiríeis,-faríeis¦4zer:radiríeis,endiríeis,mefaríeis,safaríeis,erdiríeis¦4çar:trincaríeis¦5zer:trafaríeis,rrefaríeis",
      "ex": "2ríeis:fazer,dizer¦3ríeis:trazer,afazer¦2caríeis:coçar,roçar,laçar¦3caríeis:calçar,forçar,atiçar¦4caríeis:remoçar¦2íeis:ir¦3íeis:dar¦1oríeis:pôr¦5íeis:tocar,focar,tacar,sacar,locar,socar,arfar¦4ríeis:refazer,redizer¦6íeis:trocar,brocar,blefar,surfar¦4íeis:orar,irar,arar,erar¦5ríeis:condizer,perfazer,predizer¦10íeis:reciprocar,embasbacar¦8íeis:triunfar,derrocar,atarefar¦7íeis:atracar,xerocar,ensacar,assacar¦1coitaríeis:açoitar¦7ríeis:putrefazer,liquefazer¦6ríeis:rarefazer¦9íeis:atarracar,esburacar"
    },
    "thirdPlural": {
      "fwd": "iam:¦oriam:ôr¦coitariam:çoitar¦1riam:izer¦2riam:fazer¦2cariam:inçar",
      "both": "4riam:sprazer¦3cariam:troçar,braçar",
      "rev": "2:eriam,iriam,oriam¦3:mariam,dariam,lariam,tariam,gariam,çariam,oariam,hariam,variam,sariam,jariam,pariam,bariam,zariam,nariam,iariam,eariam,uariam,xariam¦4:ncariam,trariam,arariam,orariam,urariam,irariam,icariam,ucariam,nrariam,grariam,brariam,erariam,rrariam,drariam,rcariam,ecariam,scariam,frariam,lcariam,ufariam,crariam,lrariam,vrariam,ofariam,ifariam,afariam,lfariam¦5:mprariam,locariam,vocariam,oprariam,tacariam,hocariam,focariam,lacariam,uprariam,pocariam,bocariam,pacariam,hacariam,arfariam,tocariam¦2çar:mocariam¦3zer:sfariam,sdiriam,ldiriam,-fariam¦4zer:radiriam,endiriam,mefariam,safariam,erdiriam¦4çar:trincariam¦5zer:trafariam,rrefariam",
      "ex": "2riam:fazer,dizer¦3riam:trazer,afazer¦2cariam:coçar,roçar,laçar¦3cariam:calçar,forçar,atiçar¦4cariam:remoçar¦2iam:ir¦3iam:dar¦1oriam:pôr¦5iam:tocar,focar,tacar,sacar,locar,socar,arfar¦4riam:refazer,redizer¦6iam:trocar,brocar,blefar,surfar¦4iam:orar,irar,arar,erar¦5riam:condizer,perfazer,predizer¦10iam:reciprocar,embasbacar¦8iam:triunfar,derrocar,atarefar¦7iam:atracar,xerocar,ensacar,assacar¦1coitariam:açoitar¦7riam:putrefazer,liquefazer¦6riam:rarefazer¦9iam:atarracar,esburacar"
    }
  },
  "futureTense": {
    "first": {
      "fwd": "3:xer,ser¦4:iver¦user:ôr¦coitar:çoitar¦2iver:ster¦2car:inçar",
      "both": "2:ir¦3:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,var,har,oar,cer,jar,sar,gar,dar,rer,lar,mer,mar¦4:xtar,uçar,içar,eçar,ater,ctar,ptar,eder,rçar,otar,rter,mber,etar,rtar,lver,utar,atar,eber,over,ltar,rder,star,nder,ntar¦5:poçar,daçar,maçar,ençar,paçar,titar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,haçar,litar,enzer,bitar,ritar,mitar,meter,citar,vitar,ançar,sitar,ditar,eitar,caver,rever¦5iver:brestar,ntreter¦5er:tervir¦4ir:terver¦3car:emoçar,troçar,braçar¦3er:nvir,avir,evir,dvir,ovir¦3ouver:mprazer¦3ir:tever¦2iver:bter,nter¦1ouver:eaver¦1sser:izer¦user:or¦ouber:aber¦uder:oder¦izer:azer",
      "rev": "3:çar,ter,tar¦4:ever,azer,ozer,rver,exer,oser¦5:viver,esser¦erer:iser¦1r:ier¦1azer:rouxer¦2er:evir,etiver¦3er:ustiver¦4çar:trincar",
      "ex": "3:ler,rer¦4:atar,içar¦5:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦6:traçar,ferver,sorver,poitar¦7:almoçar,ameaçar,realçar,esboçar,achoçar,panaçar,afoitar¦8:derreter,absorver,bagunçar,engraçar,morraçar¦9:descalçar,espicaçar,pernoitar,embaraçar,desgraçar,alvoroçar,congraçar¦10:escorraçar,abiscoitar¦12:desembaraçar¦for:ir¦2er:vir¦1ir:ver¦3iver:estar,deter,reter¦1iver:ter¦1er:dar¦1ouver:haver¦2iser:querer¦2ouxer:trazer¦4ir:prever¦3ir:rever¦2car:coçar,roçar,laçar¦2iver:ater¦3car:calçar,forçar,atiçar¦6ir:entrever¦3er:avir¦1user:pôr¦4iver:abster¦1coitar:açoitar"
    },
    "second": {
      "fwd": "useres:ôr¦coitares:çoitar¦2iveres:ster¦2cares:inçar¦3es:xer,ser¦4es:iver",
      "both": "5es:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iveres:brestar,ntreter¦5ires:ntrever¦4es:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4ires:terver¦4eres:rovir¦3cares:emoçar,troçar,braçar¦3es:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3eres:avir,evir,dvir,nvir¦3ouveres:mprazer¦3ires:tever¦2iveres:bter,nter¦1íres:uir,air¦1ouveres:eaver¦1sseres:izer¦useres:or¦ouberes:aber¦uderes:oder¦izeres:azer",
      "rev": "3:çares,teres,tares,uires¦4:everes,azeres,ozeres,oseres,exeres¦5:viveres,erveres,esseres¦erer:iseres¦1r:ieres¦1azer:rouxeres¦2er:evires,etiveres¦3er:bstiveres,ustiveres¦4çar:trincares",
      "ex": "fores:ir¦2eres:vir¦1ires:ver¦3iveres:estar,deter,reter¦1iveres:ter¦1eres:dar¦1ouveres:haver¦2iseres:querer¦2ouxeres:trazer¦3es:rir,ler,rer¦7eres:intervir¦5es:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7es:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4ires:prever¦6es:servir,traçar,ferver,poitar¦3ires:rever¦2cares:coçar,roçar,laçar¦2iveres:ater¦3cares:calçar,forçar,atiçar¦8es:derreter,saltitar,engraçar,morraçar¦4es:atar,içar¦10es:despedaçar,escorraçar,abiscoitar¦3eres:avir¦9es:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12es:desembaraçar¦1useres:pôr¦1coitares:açoitar"
    },
    "third": {
      "fwd": "3:xer,ser¦4:iver¦user:ôr¦coitar:çoitar¦2iver:ster¦2car:inçar",
      "both": "2:ir¦3:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,var,har,oar,cer,jar,sar,gar,dar,rer,lar,mer,mar¦4:xtar,uçar,içar,eçar,ater,ctar,ptar,eder,rçar,otar,rter,mber,etar,rtar,lver,utar,atar,eber,over,ltar,rder,star,nder,ntar¦5:poçar,daçar,maçar,ençar,paçar,titar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,haçar,litar,enzer,bitar,ritar,mitar,meter,citar,vitar,ançar,sitar,ditar,eitar,caver,rever¦5iver:brestar,ntreter¦5er:tervir¦4ir:terver¦3car:emoçar,troçar,braçar¦3er:nvir,avir,evir,dvir,ovir¦3ouver:mprazer¦3ir:tever¦2iver:bter,nter¦1ouver:eaver¦1sser:izer¦user:or¦ouber:aber¦uder:oder¦izer:azer",
      "rev": "3:çar,ter,tar¦4:ever,azer,ozer,rver,exer,oser¦5:viver,esser¦erer:iser¦1r:ier¦1azer:rouxer¦2er:evir,etiver¦3er:ustiver¦4çar:trincar",
      "ex": "3:ler,rer¦4:atar,içar¦5:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦6:traçar,ferver,sorver,poitar¦7:almoçar,ameaçar,realçar,esboçar,achoçar,panaçar,afoitar¦8:derreter,absorver,bagunçar,engraçar,morraçar¦9:descalçar,espicaçar,pernoitar,embaraçar,desgraçar,alvoroçar,congraçar¦10:escorraçar,abiscoitar¦12:desembaraçar¦for:ir¦2er:vir¦1ir:ver¦3iver:estar,deter,reter¦1iver:ter¦1er:dar¦1ouver:haver¦2iser:querer¦2ouxer:trazer¦4ir:prever¦3ir:rever¦2car:coçar,roçar,laçar¦2iver:ater¦3car:calçar,forçar,atiçar¦6ir:entrever¦3er:avir¦1user:pôr¦4iver:abster¦1coitar:açoitar"
    },
    "firstPlural": {
      "fwd": "usermos:ôr¦coitarmos:çoitar¦2ivermos:ster¦2carmos:inçar¦3mos:xer,ser¦4mos:iver",
      "both": "5mos:poçar,daçar,maçar,ençar,paçar,titar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,haçar,litar,enzer,bitar,ritar,mitar,meter,citar,vitar,ançar,sitar,ditar,eitar,caver,rever¦5ivermos:brestar,ntreter¦5ermos:tervir¦4mos:xtar,uçar,içar,eçar,ater,ctar,ptar,eder,rçar,otar,rter,mber,etar,rtar,lver,utar,atar,eber,over,ltar,rder,star,nder,ntar¦4irmos:terver¦3carmos:emoçar,troçar,braçar¦3ermos:nvir,avir,evir,dvir,ovir¦3mos:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,var,har,oar,cer,jar,sar,gar,dar,rer,lar,mer,mar¦3ouvermos:mprazer¦3irmos:tever¦2ivermos:bter,nter¦2mos:ir¦1ouvermos:eaver¦1ssermos:izer¦usermos:or¦oubermos:aber¦udermos:oder¦izermos:azer",
      "rev": "3:çarmos,termos,tarmos¦4:evermos,azermos,ozermos,rvermos,exermos,osermos¦5:vivermos,essermos¦erer:isermos¦1r:iermos¦1azer:rouxermos¦2er:evirmos,etivermos¦3er:ustivermos¦4çar:trincarmos",
      "ex": "formos:ir¦2ermos:vir¦1irmos:ver¦3ivermos:estar,deter,reter¦1ivermos:ter¦1ermos:dar¦1ouvermos:haver¦2isermos:querer¦2ouxermos:trazer¦3mos:ler,rer¦5mos:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7mos:almoçar,ameaçar,realçar,esboçar,achoçar,panaçar,afoitar¦4irmos:prever¦3irmos:rever¦6mos:traçar,ferver,sorver,poitar¦2carmos:coçar,roçar,laçar¦2ivermos:ater¦3carmos:calçar,forçar,atiçar¦8mos:derreter,absorver,bagunçar,engraçar,morraçar¦4mos:atar,içar¦6irmos:entrever¦3ermos:avir¦9mos:descalçar,espicaçar,pernoitar,embaraçar,desgraçar,alvoroçar,congraçar¦10mos:escorraçar,abiscoitar¦12mos:desembaraçar¦1usermos:pôr¦4ivermos:abster¦1coitarmos:açoitar"
    },
    "secondPlural": {
      "fwd": "userdes:ôr¦coitardes:çoitar¦2iverdes:ster¦2cardes:inçar¦3des:xer,ser¦4des:iver",
      "both": "5des:poçar,daçar,maçar,ençar,paçar,titar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,haçar,litar,enzer,bitar,ritar,mitar,meter,citar,vitar,ançar,sitar,ditar,eitar,caver,rever¦5iverdes:brestar,ntreter¦5erdes:tervir¦4des:xtar,uçar,içar,eçar,ater,ctar,ptar,eder,rçar,otar,rter,mber,etar,rtar,lver,utar,atar,eber,over,ltar,rder,star,nder,ntar¦4irdes:terver¦3cardes:emoçar,troçar,braçar¦3erdes:nvir,avir,evir,dvir,ovir¦3des:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,var,har,oar,cer,jar,sar,gar,dar,rer,lar,mer,mar¦3ouverdes:mprazer¦3irdes:tever¦2iverdes:bter,nter¦2des:ir¦1ouverdes:eaver¦1sserdes:izer¦userdes:or¦ouberdes:aber¦uderdes:oder¦izerdes:azer",
      "rev": "3:çardes,terdes,tardes¦4:everdes,azerdes,ozerdes,rverdes,exerdes,oserdes¦5:viverdes,esserdes¦erer:iserdes¦1r:ierdes¦1azer:rouxerdes¦2er:evirdes,etiverdes¦3er:ustiverdes¦4çar:trincardes",
      "ex": "fordes:ir¦2erdes:vir¦1irdes:ver¦3iverdes:estar,deter,reter¦1iverdes:ter¦1erdes:dar¦1ouverdes:haver¦2iserdes:querer¦2ouxerdes:trazer¦3des:ler,rer¦5des:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7des:almoçar,ameaçar,realçar,esboçar,achoçar,panaçar,afoitar¦4irdes:prever¦3irdes:rever¦6des:traçar,ferver,sorver,poitar¦2cardes:coçar,roçar,laçar¦2iverdes:ater¦3cardes:calçar,forçar,atiçar¦8des:derreter,absorver,bagunçar,engraçar,morraçar¦4des:atar,içar¦6irdes:entrever¦3erdes:avir¦9des:descalçar,espicaçar,pernoitar,embaraçar,desgraçar,alvoroçar,congraçar¦10des:escorraçar,abiscoitar¦12des:desembaraçar¦1userdes:pôr¦4iverdes:abster¦1coitardes:açoitar"
    },
    "thirdPlural": {
      "fwd": "userem:ôr¦coitarem:çoitar¦2iverem:ster¦2carem:inçar¦3em:xer,ser¦4em:iver",
      "both": "5em:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iverem:brestar,ntreter¦5irem:ntrever¦4em:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4irem:terver¦4erem:rovir¦3carem:emoçar,troçar,braçar¦3em:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3erem:avir,evir,dvir,nvir¦3ouverem:mprazer¦3irem:tever¦2iverem:bter,nter¦1írem:uir,air¦1ouverem:eaver¦1sserem:izer¦userem:or¦ouberem:aber¦uderem:oder¦izerem:azer",
      "rev": "3:çarem,terem,tarem,uirem¦4:everem,azerem,ozerem,oserem,exerem¦5:viverem,erverem,esserem¦erer:iserem¦1r:ierem¦1azer:rouxerem¦2er:evirem,etiverem¦3er:bstiverem,ustiverem¦4çar:trincarem",
      "ex": "forem:ir¦2erem:vir¦1irem:ver¦3iverem:estar,deter,reter¦1iverem:ter¦1erem:dar¦1ouverem:haver¦2iserem:querer¦2ouxerem:trazer¦3em:rir,ler,rer¦7erem:intervir¦5em:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7em:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4irem:prever¦6em:servir,traçar,ferver,poitar¦3irem:rever¦2carem:coçar,roçar,laçar¦2iverem:ater¦3carem:calçar,forçar,atiçar¦8em:derreter,saltitar,engraçar,morraçar¦4em:atar,içar¦10em:despedaçar,escorraçar,abiscoitar¦3erem:avir¦9em:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12em:desembaraçar¦1userem:pôr¦1coitarem:açoitar"
    }
  },
  "imperativeNeg": {
    "first": {
      "fwd": "onhas:ôr¦jas:gir,ger¦igas:eguir¦iras:erir¦as:uer¦ças:cir¦urtas:ortir¦coites:çoitar¦1jas:aver¦1as:mer,rer,ber,her,per,ser,hir¦1gas:izer¦1es:iar¦2as:ndir,rter,mbir,ulir,idir,irir,rdir¦2eies:nsiar¦2ças:pedir,medir¦2ques:inçar¦3es:iguar,nquar¦3as:arrir¦4es:inguar,coitar",
      "both": "5as:ementir,flectir,mprazer¦5jas:terver¦5ejas:brestar¦5nhas:treter¦4ues:umegar,amegar,elegar¦4es:foitar,noitar¦4as:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4intas:ressentir¦4jas:tever¦4eies:cendiar¦4iras:equerer¦4enhas:tervir¦3as:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3ues:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3es:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3ques:emoçar,troçar,braçar¦3idas:egredir,sgredir¦3ias:crer¦3eies:mediar¦3nhas:ster,bter,nter¦3enhas:rovir¦2as:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2es:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úles:baular¦2enhas:avir,evir,nvir¦2ízes:juizar¦2intas:smentir,nsentir¦2ues:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilas:mpelir,xpelir¦2ínes:ruinar¦2ita:mpetir¦2has:aler¦2cas:erder¦1údes:iudar¦1irvas:servir¦1ças:uvir,azer¦1ízes:aizar,eizar¦1úces:iuçar¦1ísques:aiscar¦1águas:saguar¦1es:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjas:vergir¦1águes:xaguar¦1iras:arir¦1íbas:oibir¦1as:oer,nir,xer¦1ulas:golir¦1únas:eunir¦1itas:letir¦1ies:ear¦1nhas:or¦1ibas:aber¦1ssas:oder¦ólegues:olegar¦irzas:erzir¦ínquas:inquir¦igras:egrir¦ispas:espir¦ubras:obrir¦éques:equar¦irtas:ertir¦ussas:ossir¦ças:cer¦ces:çar¦ques:car¦urmas:ormir",
      "rev": "ar:ês¦entir:intas¦ervir:irvas¦udar:údes¦iliar:ílies¦ectir:ictas¦1rer:eiras¦1zer:agas¦1r:eias¦1gir:ijas,ujas,ljas¦1eguir:sigas¦1erir:firas,diras,giras,siras,tiras¦1etir:pitas¦1edir:ridas¦1enir:vinas¦1estir:vistas¦1ar:tes¦1ir:venhas¦2ar:stejas,vies,pies,oies,fies,cies,ries,gies,dies,aies,ties,bies,sies,zies,nies,uies,mies,xies¦2er:omas,rras,ebas,chas,fras,etas,emas,osas,mpas¦2gir:injas,urjas,eajas,erjas,oajas,unjas,arjas¦2r:vejas,tenhas¦2ger:lejas,anjas,rejas,onjas¦2zer:digas¦2cir:arças¦2uer:rgas¦3ir:vidas,cidas,undas,uspas,andas,indas,sidas,lidas,uiras,unhas,bulas,redas,urzas,feras,ardas¦3ger:otejas¦3er:olhas,ambas,ervas,ertas,ueras,relas,essas¦3ar:ilies,plies,alies,olies¦3dir:xpeças¦4dir:espeças,impeças,esmeças¦4gir:terajas¦4ar:zigues,relies¦4ir:cumbas,apulas,sentas,lanhas¦4çar:trinques¦4ger:sterjas¦5ar:pinques,ginques,anigues",
      "ex": "vás:ir¦águes:aguar¦2jas:ser,ver,haver,reger,viger¦1enhas:vir¦3ejas:estar¦2nhas:ter¦1ês:dar¦3iras:querer¦3gas:trazer¦2as:rir¦2ias:ler¦1intas:sentir,mentir¦2ças:pedir,medir¦3as:abrir,dever,meter,jazer,arder,bulir,urdir¦3ias:crer¦3ues:pegar,negar,regar,cegar,legar,segar¦5jas:prover,prever¦1istas:vestir¦1irvas:servir¦4jas:rever¦2eies:odiar¦4nhas:deter,reter¦3itas:repetir¦1ulas:polir¦4as:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2es:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idas:agredir¦3eies:mediar,ansiar¦4inas:prevenir¦3enhas:advir¦3istas:investir,revestir¦2údes:saudar¦2ques:coçar,roçar,laçar¦3nhas:ater¦5idas:progredir¦3ques:calçar,forçar,atiçar¦3es:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4ues:alegar¦3ílies:mobiliar¦3intas:assentir¦7jas:entrever¦2enhas:avir¦4ias:reler¦4intas:ressentir¦7as:dissentir¦1as:rer¦9as:retrogredir¦8as:correferir¦2ictas:flectir¦4es:poitar¦1onhas:pôr¦2gas:dizer¦1jas:agir¦1igas:seguir¦1iras:ferir,gerir¦4ças:impedir¦7es:averiguar¦1urtas:sortir¦5es:minguar¦1coites:açoitar"
    },
    "second": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦a:uer¦urta:ortir¦coite:çoitar¦1ja:aver¦1a:mer,rer,ber,her,per,ser,hir¦1ga:izer¦1e:iar¦2a:ndir,rter,mbir,ulir,idir,irir,rdir¦2eie:nsiar¦2ça:pedir,medir¦2que:inçar¦3e:iguar,nquar¦3a:arrir¦4e:inguar,coitar",
      "both": "5a:ementir,flectir,mprazer¦5ja:terver¦5eja:brestar¦5nha:treter¦4ue:umegar,amegar,elegar¦4e:foitar,noitar¦4a:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4inta:ressentir¦4ja:tever¦4eie:cendiar¦4ira:equerer¦4enha:tervir¦3a:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3ue:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3e:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3que:emoçar,troçar,braçar¦3ida:egredir,sgredir¦3ia:crer¦3eie:mediar¦3nha:ster,bter,nter¦3enha:rovir¦2a:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2e:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úle:baular¦2enha:avir,evir,nvir¦2íze:juizar¦2inta:smentir,nsentir¦2ue:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ila:mpelir,xpelir¦2íne:ruinar¦2itas:mpetir¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1ça:uvir,azer¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1água:saguar¦1e:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irja:vergir¦1águe:xaguar¦1ira:arir¦1íba:oibir¦1a:oer,nir,xer¦1ula:golir¦1úna:eunir¦1ita:letir¦1ie:ear¦1nha:or¦1iba:aber¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦ças:cir¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦udar:úde¦iliar:ílie¦ectir:icta¦1rer:eira¦1zer:aga¦1r:eia¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita¦1edir:rida¦1enir:vina¦1estir:vista¦1ar:te¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,osa,mpa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2uer:rga¦3ir:vida,cida,unda,uspa,anda,inda,sida,lida,uira,unha,bula,reda,urza,fera,arda¦3ger:oteja¦3er:olha,amba,erva,erta,uera,rela,essa¦3ar:ilie,plie,alie,olie¦3dir:xpeça¦4dir:espeça,impeça,esmeça¦4gir:teraja¦4ar:zigue,relie¦4ir:cumba,apula,senta,lanha¦4çar:trinque¦4ger:sterja¦5ar:pinque,ginque,anigue",
      "ex": "vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir¦2ia:ler¦1inta:sentir,mentir¦2ça:pedir,medir¦3a:abrir,dever,meter,jazer,arder,bulir,urdir¦3ia:crer¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦3ita:repetir¦1ula:polir¦4a:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3ida:agredir¦3eie:mediar,ansiar¦4ina:prevenir¦3enha:advir¦3ista:investir,revestir¦2úde:saudar¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4ue:alegar¦3ílie:mobiliar¦3inta:assentir¦7ja:entrever¦2enha:avir¦4ia:reler¦4inta:ressentir¦7a:dissentir¦1a:rer¦9a:retrogredir¦8a:correferir¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦5e:minguar¦1coite:açoitar"
    },
    "third": {
      "fwd": "onhamos:ôr¦jamos:gir,ger¦igamos:eguir¦iramos:erir¦amos:uer¦çamos:cir¦urtamos:ortir¦coitemos:çoitar¦1amos:mer,rer,ber,bir,her,per,ser,hir¦1gamos:izer¦2amos:idir,ndir,rter,nzer,ulir,irir,rdir¦2çamos:pedir,medir¦2quemos:inçar¦3amos:urtir,arrir",
      "both": "5amos:ementir,flectir,mprazer¦5ejamos:brestar¦5mos:saguar¦5nhamos:treter¦4amos:morder,opelir,xceler,inquir,rreter,orrir¦4nhamos:uster,bster¦4jamos:tever¦4iramos:equerer¦4enhamos:tervir¦3amos:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3quemos:emoçar,troçar¦3intamos:essentir¦3idamos:egredir,sgredir¦3iamos:crer¦3inamos:revenir¦3enhamos:rovir¦3nhamos:nter¦2amos:lpir,orir,urir,alir,odir,ater,plir,upir,imir,eder,trir,udir,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,itir,umir,prir,stir,nder,air¦2intamos:smentir,nsentir¦2istamos:evestir¦2ilamos:mpelir,xpelir¦2enhamos:avir,evir,nvir¦2ita:mpetir¦2hamos:aler¦2camos:erder¦1irvamos:servir¦1irjamos:vergir¦1iramos:arir¦1amos:oer,nir,xer,ver¦1ulamos:golir¦1itamos:letir¦1nhamos:or¦1uemos:gar¦1çamos:uvir,azer¦1ssamos:oder¦irzamos:erzir¦igramos:egrir¦ispamos:espir¦ubramos:obrir¦irtamos:ertir¦ussamos:ossir¦çamos:cer¦cemos:çar¦quemos:car¦urmamos:ormir¦emos:ar",
      "rev": "entir:intamos¦ervir:irvamos¦ectir:ictamos¦1rer:eiramos¦1zer:agamos¦1r:eiamos¦1ber:aibamos¦1gir:ijamos,ujamos,ljamos¦1eguir:sigamos¦1erir:firamos,diramos,giramos,siramos,tiramos¦1etir:pitamos¦1edir:ridamos¦1ir:venhamos¦1estir:vistamos¦2ar:stejamos¦2er:omamos,rramos,ebamos,framos,emamos,chamos,azamos,mpamos,osamos¦2gir:injamos,urjamos,eajamos,erjamos,oajamos,unjamos,arjamos¦2r:vejamos,tenhamos¦2ger:lejamos,anjamos,rejamos¦2zer:digamos¦2cir:arçamos¦2uer:rgamos¦3ir:vidamos,cidamos,undamos,oibamos,andamos,umbamos,indamos,pulamos,sidamos,entamos,uiramos,redamos,nibamos,urdamos,anhamos¦3ger:otejamos¦3er:olhamos,ordamos,ambamos,ertamos,enzamos,ueramos,relamos¦3çar:braquemos¦3dir:xpeçamos,smeçamos¦4dir:espeçamos,impeçamos¦4gir:terajamos¦4iar:obilemos¦4ir:olidamos,runhamos,cardamos,eferamos¦4çar:trinquemos¦5er:bressamos",
      "ex": "vamos:ir¦2jamos:ser,ver,haver,reger,viger¦1enhamos:vir¦3ejamos:estar¦2nhamos:ter¦3iramos:querer¦3gamos:trazer¦2amos:rir¦2iamos:ler¦2ibamos:saber,caber¦1intamos:sentir,mentir¦2çamos:pedir,medir¦3amos:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iamos:crer¦5jamos:prover,prever¦1istamos:vestir¦1irvamos:servir¦4jamos:rever¦4nhamos:deter,reter,obter¦3itamos:repetir¦1ulamos:polir¦4quemos:abraçar¦4amos:morder,treler,curtir,exibir,ebulir,elidir,ilidir,condir,garrir¦3idamos:agredir¦3enhamos:advir¦3istamos:investir¦2quemos:coçar,roçar,laçar¦3nhamos:ater¦5idamos:progredir¦3quemos:calçar,forçar,atiçar¦5emos:mobiliar¦3intamos:assentir¦7jamos:entrever,interver¦2enhamos:avir¦4iamos:reler¦7amos:dissentir¦1amos:rer¦9amos:retrogredir¦8amos:correferir¦2ictamos:flectir¦1onhamos:pôr¦2gamos:dizer¦1jamos:agir¦1igamos:seguir¦1iramos:ferir,gerir¦4çamos:impedir¦1urtamos:sortir¦1coitemos:açoitar¦3jamos:monger¦6jamos:absterger"
    },
    "firstPlural": {
      "fwd": "onhais:ôr¦jais:gir,ger¦igais:eguir¦irais:erir¦ais:uer¦çais:cir¦urtais:ortir¦coiteis:çoitar¦1ais:mer,rer,ber,bir,her,per,ser,hir¦1gais:izer¦2ais:idir,ndir,rter,nzer,ulir,irir,rdir¦2çais:pedir,medir¦2queis:inçar¦3ais:urtir,arrir",
      "both": "5ais:ementir,flectir,mprazer¦5ejais:brestar¦5is:saguar¦5nhais:treter¦4ais:morder,opelir,xceler,inquir,rreter,orrir¦4nhais:uster,bster¦4jais:tever¦4irais:equerer¦4enhais:tervir¦3ais:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3queis:emoçar,troçar¦3intais:essentir¦3idais:egredir,sgredir¦3iais:crer¦3inais:revenir¦3enhais:rovir¦3nhais:nter¦2ais:lpir,orir,urir,alir,odir,ater,plir,upir,imir,eder,trir,udir,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,itir,umir,prir,stir,nder,air¦2intais:smentir,nsentir¦2istais:evestir¦2ilais:mpelir,xpelir¦2enhais:avir,evir,nvir¦2itamos:mpetir¦2hais:aler¦2cais:erder¦1irvais:servir¦1irjais:vergir¦1irais:arir¦1ais:oer,nir,xer,ver¦1ulais:golir¦1itais:letir¦1nhais:or¦1ueis:gar¦1çais:uvir,azer¦1ssais:oder¦irzais:erzir¦igrais:egrir¦ispais:espir¦ubrais:obrir¦irtais:ertir¦ussais:ossir¦çais:cer¦ceis:çar¦queis:car¦urmais:ormir¦eis:ar",
      "rev": "entir:intais¦ervir:irvais¦ectir:ictais¦1rer:eirais¦1zer:agais¦1r:eiais¦1ber:aibais¦1gir:ijais,ujais,ljais¦1eguir:sigais¦1erir:firais,dirais,girais,sirais,tirais¦1etir:pitais¦1edir:ridais¦1ir:venhais¦1estir:vistais¦2ar:stejais¦2er:omais,rrais,ebais,frais,emais,chais,azais,mpais,osais¦2gir:injais,urjais,eajais,erjais,oajais,unjais,arjais¦2r:vejais,tenhais¦2ger:lejais,anjais,rejais¦2zer:digais¦2cir:arçais¦2uer:rgais¦3ir:vidais,cidais,undais,oibais,andais,umbais,indais,pulais,sidais,entais,uirais,redais,nibais,urdais,anhais¦3ger:otejais¦3er:olhais,ordais,ambais,ertais,enzais,uerais,relais¦3çar:braqueis¦3dir:xpeçais,smeçais¦4dir:espeçais,impeçais¦4gir:terajais¦4ir:olidais,runhais,cardais,eferais¦4çar:trinqueis¦5er:bressais",
      "ex": "vades:ir¦2jais:ser,ver,haver,reger,viger¦1enhais:vir¦3ejais:estar¦2nhais:ter¦3irais:querer¦3gais:trazer¦2ais:rir¦2iais:ler¦2ibais:saber,caber¦1intais:sentir,mentir¦2çais:pedir,medir¦3ais:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iais:crer¦5jais:prover,prever¦1istais:vestir¦1irvais:servir¦4jais:rever¦4nhais:deter,reter,obter¦3itais:repetir¦1ulais:polir¦4queis:abraçar¦4ais:morder,treler,curtir,exibir,ebulir,elidir,ilidir,condir,garrir¦3idais:agredir¦3enhais:advir¦3istais:investir¦2queis:coçar,roçar,laçar¦3nhais:ater¦5idais:progredir¦3queis:calçar,forçar,atiçar¦3intais:assentir¦7jais:entrever,interver¦2enhais:avir¦4iais:reler¦7ais:dissentir¦1ais:rer¦9ais:retrogredir¦8ais:correferir¦2ictais:flectir¦1onhais:pôr¦2gais:dizer¦1jais:agir¦1igais:seguir¦1irais:ferir,gerir¦4çais:impedir¦1urtais:sortir¦1coiteis:açoitar¦3jais:monger¦6jais:absterger"
    },
    "secondPlural": {
      "fwd": "onham:ôr¦jam:gir,ger¦igam:eguir¦iram:erir¦am:uer¦çam:cir¦urtam:ortir¦coitem:çoitar¦1jam:aver¦1am:mer,rer,ber,her,per,ser,hir¦1gam:izer¦1em:iar¦2am:ndir,rter,mbir,ulir,idir,irir,rdir¦2eiem:nsiar¦2çam:pedir,medir¦2quem:inçar¦3em:iguar,nquar¦3am:arrir¦4em:inguar,coitar",
      "both": "5am:ementir,flectir,mprazer¦5jam:terver¦5ejam:brestar¦5nham:treter¦4uem:umegar,amegar,elegar¦4em:foitar,noitar¦4am:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4intam:ressentir¦4jam:tever¦4eiem:cendiar¦4iram:equerer¦4enham:tervir¦3am:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3uem:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3em:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3quem:emoçar,troçar,braçar¦3idam:egredir,sgredir¦3iam:crer¦3eiem:mediar¦3nham:ster,bter,nter¦3enham:rovir¦2am:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2em:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úlem:baular¦2enham:avir,evir,nvir¦2ízem:juizar¦2intam:smentir,nsentir¦2uem:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilam:mpelir,xpelir¦2ínem:ruinar¦2itais:mpetir¦2ham:aler¦2cam:erder¦1údem:iudar¦1irvam:servir¦1çam:uvir,azer¦1ízem:aizar,eizar¦1úcem:iuçar¦1ísquem:aiscar¦1águam:saguar¦1em:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjam:vergir¦1águem:xaguar¦1iram:arir¦1íbam:oibir¦1am:oer,nir,xer¦1ulam:golir¦1únam:eunir¦1itam:letir¦1iem:ear¦1nham:or¦1ibam:aber¦1ssam:oder¦óleguem:olegar¦irzam:erzir¦ínquam:inquir¦igram:egrir¦ispam:espir¦ubram:obrir¦équem:equar¦irtam:ertir¦ussam:ossir¦çam:cer¦cem:çar¦quem:car¦urmam:ormir",
      "rev": "ar:eem¦entir:intam¦ervir:irvam¦udar:údem¦iliar:íliem¦ectir:ictam¦1rer:eiram¦1zer:agam¦1r:eiam¦1gir:ijam,ujam,ljam¦1eguir:sigam¦1erir:firam,diram,giram,siram,tiram¦1etir:pitam¦1edir:ridam¦1enir:vinam¦1estir:vistam¦1ar:tem¦1ir:venham¦2ar:stejam,viem,piem,oiem,fiem,ciem,riem,giem,diem,aiem,tiem,biem,siem,ziem,niem,uiem,miem,xiem¦2er:omam,rram,ebam,cham,fram,etam,emam,osam,mpam¦2gir:injam,urjam,eajam,erjam,oajam,unjam,arjam¦2r:vejam,tenham¦2ger:lejam,anjam,rejam,onjam¦2zer:digam¦2cir:arçam¦2uer:rgam¦3ir:vidam,cidam,undam,uspam,andam,indam,sidam,lidam,uiram,unham,bulam,redam,urzam,feram,ardam¦3ger:otejam¦3er:olham,ambam,ervam,ertam,ueram,relam,essam¦3ar:iliem,pliem,aliem,oliem¦3dir:xpeçam¦4dir:espeçam,impeçam,esmeçam¦4gir:terajam¦4ar:ziguem,reliem¦4ir:cumbam,apulam,sentam,lanham¦4çar:trinquem¦4ger:sterjam¦5ar:pinquem,ginquem,aniguem",
      "ex": "vão:ir¦águem:aguar¦2jam:ser,ver,haver,reger,viger¦1enham:vir¦3ejam:estar¦2nham:ter¦1eem:dar¦3iram:querer¦3gam:trazer¦2am:rir¦2iam:ler¦1intam:sentir,mentir¦2çam:pedir,medir¦3am:abrir,dever,meter,jazer,arder,bulir,urdir¦3iam:crer¦3uem:pegar,negar,regar,cegar,legar,segar¦5jam:prover,prever¦1istam:vestir¦1irvam:servir¦4jam:rever¦2eiem:odiar¦4nham:deter,reter¦3itam:repetir¦1ulam:polir¦4am:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2em:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idam:agredir¦3eiem:mediar,ansiar¦4inam:prevenir¦3enham:advir¦3istam:investir,revestir¦2údem:saudar¦2quem:coçar,roçar,laçar¦3nham:ater¦5idam:progredir¦3quem:calçar,forçar,atiçar¦3em:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4uem:alegar¦3íliem:mobiliar¦3intam:assentir¦7jam:entrever¦2enham:avir¦4iam:reler¦4intam:ressentir¦7am:dissentir¦1am:rer¦9am:retrogredir¦8am:correferir¦2ictam:flectir¦4em:poitar¦1onham:pôr¦2gam:dizer¦1jam:agir¦1igam:seguir¦1iram:ferir,gerir¦4çam:impedir¦7em:averiguar¦1urtam:sortir¦5em:minguar¦1coitem:açoitar"
    },
    "thirdPlural": {
      "fwd": "",
      "both": "itam:etir",
      "rev": "",
      "ex": ""
    }
  },
  "imperative": {
    "first": {
      "fwd": "õe:ôr¦urte:ortir¦coita:çoitar¦1e:sir,cir¦1ói:roer¦1ole:pulir¦2e:idir,ngir,olir,ndir,etir,inir,odir,atir,elir,mbir,nzir,rdir¦2eia:nsiar¦2ca:inçar¦3e:ertir,urtir,arrir",
      "both": "2:izer¦3:fazer¦5:sprazer¦5e:sservir,nsfugir¦5á:brestar¦5ê:ntrever¦5eia:ncendiar¦5ói:onstruir¦4e:emunir,parzir,smedir,esunir,cernir,olorir,esumir,eragir,ssumir¦4ca:stroçar¦4ê:terver¦4ói:estruir¦4i:caver¦4ém:treter,tervir¦3e:talir,anhir,nibir,runir,ornir,bulir,oagir,unhir,ramir,pedir,rquir,xibir,ludir,audir,eagir,nguir,eguir,artir¦3ca:emoçar,braçar¦3í:mbair¦3ide:sgredir¦3ê:tever¦3eia:mediar¦3ém:rovir¦2e:lpir,urir,lgir,plir,ctir,irir,brir,rpir,adir,imir,anir,trir,uzir,rgir,utir,itir,erir,ntir,prir,stir,igir,uvir,rmir¦2ém:avir,evir,dvir,ster,bter,nvir,nter¦2íza:juizar¦2ome:bsumir,nsumir¦2ê:crer¦2ína:ruinar¦1úda:iudar¦1íza:aizar,eizar¦1úça:iuçar¦1ísca:aiscar¦1ói:moer¦1ode:cudir¦1íbe:oibir¦1úne:eunir¦1ia:ear¦ólega:olegar¦irze:erzir¦ínque:inquir¦igre:egrir¦ope:upir¦água:aguar¦ospe:uspir¦équa:equar¦obe:ubir¦õe:or¦:r",
      "rev": "er:ê, ou dize¦ugir:oge¦udar:úda¦iliar:ília¦ular:úla¦1er:z ou faze,r,tém¦1ar:tá¦1r:ei¦1edir:ride¦1enir:vine¦1ir:vém¦2er:az¦2ir:une,are,uge,ene,ore¦2oer:rrói¦2ulir:apole¦3ir:vide,inge,cide,pete,bole,unde,gole,fine,lode,ande,arce,pele,umbe,inde,side,unge,rode,lide,arde,urze,urde¦4ir:flete,emole,epole,ranze,grede¦4çar:trinca¦5ir:iverte,dverte",
      "ex": "4:querer,trazer¦vai:ir¦água:aguar¦1ê:ser,ver,ler¦3 ou faze:fazer¦1em:vir¦3á:estar¦2m:ter¦1á:dar,haver¦3 ou dize:dizer¦2e:agir,unir¦3e:pedir,medir,punir,parir,rugir,mugir,munir,zunir,balir,lenir,latir,ungir,delir,tinir,urdir¦2ê:crer¦5i:reaver¦1oge:fugir¦1ome:sumir¦4ê:prover,prever¦4e:servir,despir,fremir,zurzir,tossir,curtir,condir,garrir¦3ê:rever,reler¦2eia:odiar¦3ém:deter,reter¦1ule:polir¦1ói:roer,moer,soer¦3ide:agredir¦3eia:mediar,ansiar¦4ine:prevenir¦2úda:saudar¦2ca:coçar,roçar,laçar¦2ém:ater,avir¦2ege:frigir¦5ide:progredir¦4a:prazer¦3ca:calçar,forçar,atiçar¦1ole:bulir¦3ília:mobiliar¦4ide:regredir¦1usca:moscar¦5e:revenir,retinir¦3oge:refugir¦9e:retrogredir¦3úla:abaular¦6e:reflorir¦1õe:pôr¦1urte:sortir¦1coita:açoitar"
    },
    "second": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦ita:etir¦a:uer¦ça:cir¦urta:ortir¦coite:çoitar¦1ja:aver¦1a:mer,rer,ber,her,per,ser,hir¦1ga:izer¦1e:iar¦2a:itir,ndir,nzer,idir,mbir,rter,nzir,ulir,irir¦2eie:nsiar¦2ça:pedir,medir¦2que:inçar¦3a:urtir,arrir¦3e:iguar,nquar¦4e:inguar",
      "both": "3:emir,amir,rpir,anir¦4:celir,ernir,aurir,rquir¦5:turdir,randir,epelir,olorir,emolir¦5a:ementir,flectir,mprazer,estruir,nstruir¦5eja:brestar¦5nha:treter¦4a:florir,mburir,etinir,opelir,xceler,esunir,rreter,epolir,efinir,rantir,orrir¦4ue:umegar,amegar,elegar¦4e:ltitar,noitar¦4ça:sprazer¦4inta:ressentir¦4ia:screr¦4ida:nsgredir¦4ja:tever¦4eie:cendiar¦4ira:equerer¦4enha:tervir¦3a:munir,rurir,arzir,runir,ardir,abrir,reler,nibir,orver,xibir,rguir,fruir,order,meter,rever,artir¦3í:rruir¦3ue:iegar,negar,fegar,segar,pegar,vegar,regar,hegar¦3e:vitar,bitar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3que:emoçar,troçar,braçar¦3inta:esmentir¦3ida:egredir¦3ila:ompelir¦3eie:mediar¦3nha:ster,bter,nter¦3ina:revenir¦3enha:rovir¦2a:cuir,alir,odir,plir,tuir,adir,upir,imir,ater,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,stir,suir,umir,prir,ubir,iver,nder,air¦2e:fuar,ruar,suar,duar,muar,xtar,juar,ctar,cuar,ptar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úle:baular¦2ue:sgar,lgar,ngar,rgar,agar,igar,ugar,ogar¦2enha:avir,evir,dvir,nvir¦2íze:juizar¦2ista:evestir¦2íne:ruinar¦2ila:xpelir¦2inta:nsentir¦2ça:fazer¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1ça:uvir¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1e:far,xar,nar,zar,bar,par,var,har,oar,jar,rar,sar,dar,lar,mar¦1irja:vergir¦1ira:arir¦1íba:oibir¦1a:oer,xer¦1ula:golir¦1úna:eunir¦1ie:ear¦1nha:or¦1iba:aber¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦águe:aguar¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦udar:úde¦er:am¦ir:í¦iliar:ílie¦ectir:icta¦1zer:aça,aga¦1rer:eira¦1r:eia,i,ei¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita,lita¦1edir:rida¦1estir:vista¦1ar:te¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,mpa,osa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2ir:una,rua,rna,ena,ola,lpa¦2cir:arça¦2uer:rga¦3ir:vida,cida,uira,unda,uspa,mita,anda,inda,sida,anza,umba,bula,lida,reda,urza¦3ger:oteja¦3er:olha,amba,erva,enza,erta,uera,essa¦3ar:ilie,plie,alie,olie,elie¦3dir:xpeça,smeça¦4dir:espeça,impeça¦4gir:teraja¦4ar:zigue,nigue¦4ir:apula,runha,senta,efera¦4çar:trinque¦5ar:pinque,ginque¦5ger:bsterja",
      "ex": "4:latir,ungir,munir,delir,tinir¦5:abolir,fulgir¦6:impelir¦7:esculpir,impingir¦vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger¦2ça:fazer,pedir,medir¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir,unir¦2ia:ler¦1inta:sentir,mentir¦3a:abrir,dever,punir,meter,jazer,cozer,arder,zunir,urdir,lenir,bulir¦3ia:crer¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦1ula:polir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦4a:cuspir,ferver,fornir,zurzir,surdir,curtir,condir,garrir¦3ida:agredir¦3eie:mediar,ansiar¦3ista:investir¦2úde:saudar¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦4am:prazer¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦3i:soer¦2í:ruir,puir¦4ue:alegar¦3ílie:mobiliar¦3inta:assentir¦6a:obstruir¦7ja:entrever,interver¦2enha:avir¦4ia:reler¦3í:fruir,pruir¦1usque:moscar¦4inta:ressentir¦9í:desobstruir¦7a:dissentir,insculpir¦5a:revenir,rebolir,planhir¦1a:rer¦9a:retrogredir¦8a:correferir¦5e:afoitar,minguar¦6í:abstruir¦8e:abiscoitar¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦1coite:açoitar"
    },
    "third": {
      "fwd": "onhamos:ôr¦jamos:gir,ger¦igamos:eguir¦iramos:erir¦itamos:etir¦amos:uer¦çamos:cir¦urtamos:ortir¦coitemos:çoitar¦1amos:mer,rer,ber,bir,her,per,ser,hir¦1gamos:izer¦2amos:idir,itir,ndir,nzer,ulir,rter,irir,rdir¦2çamos:pedir,medir¦2quemos:inçar¦3amos:urtir,arrir",
      "both": "5amos:ementir,flectir,mprazer¦5ejamos:brestar¦5nhamos:treter¦4amos:morder,opelir,xceler,inquir,rreter,orrir¦4nhamos:uster,bster¦4jamos:tever¦4iramos:equerer¦4enhamos:tervir¦3amos:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3quemos:emoçar,troçar¦3intamos:essentir,onsentir¦3idamos:egredir,sgredir¦3iamos:crer¦3inamos:revenir¦3enhamos:rovir¦3nhamos:nter¦2amos:lpir,orir,urir,alir,odir,plir,upir,imir,eder,udir,trir,ater,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,umir,prir,stir,nder,air¦2intamos:smentir¦2istamos:evestir¦2ilamos:mpelir,xpelir¦2enhamos:avir,evir,dvir,nvir¦2hamos:aler¦2camos:erder¦1irvamos:servir¦1irjamos:vergir¦1iramos:arir¦1amos:oer,nir,xer,ver¦1ulamos:golir¦1nhamos:or¦1uemos:gar¦1çamos:uvir,azer¦1ssamos:oder¦irzamos:erzir¦igramos:egrir¦ispamos:espir¦ubramos:obrir¦irtamos:ertir¦ussamos:ossir¦çamos:cer¦cemos:çar¦quemos:car¦urmamos:ormir¦emos:ar",
      "rev": "entir:intamos¦ervir:irvamos¦ectir:ictamos¦1rer:eiramos¦1zer:agamos¦1r:eiamos¦1ber:aibamos¦1gir:ijamos,ujamos,ljamos¦1eguir:sigamos¦1erir:firamos,diramos,giramos,siramos,tiramos¦1etir:pitamos,litamos¦1edir:ridamos¦1estir:vistamos¦1ir:venhamos¦2ar:stejamos¦2er:omamos,rramos,ebamos,framos,emamos,chamos,azamos,mpamos,osamos¦2gir:injamos,urjamos,eajamos,erjamos,oajamos,unjamos,arjamos¦2r:vejamos,tenhamos¦2ger:lejamos,anjamos,rejamos¦2zer:digamos¦2cir:arçamos¦2uer:rgamos¦3ir:vidamos,cidamos,uiramos,undamos,oibamos,andamos,mitamos,umbamos,indamos,pulamos,sidamos,unhamos,entamos,bulamos,lidamos,redamos,nibamos,urdamos,anhamos¦3ger:otejamos¦3er:olhamos,ordamos,ambamos,ertamos,enzamos¦3çar:braquemos¦3dir:xpeçamos,smeçamos¦4dir:espeçamos,impeçamos¦4gir:terajamos¦4iar:obilemos¦4er:queramos¦4ir:cardamos,eferamos¦4çar:trinquemos¦5er:bressamos",
      "ex": "vamos:ir¦2jamos:ser,ver,haver,reger,viger¦1enhamos:vir¦3ejamos:estar¦2nhamos:ter¦3iramos:querer¦3gamos:trazer¦2amos:rir¦2iamos:ler¦2ibamos:saber,caber¦1intamos:sentir,mentir¦2çamos:pedir,medir¦3amos:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iamos:crer¦5jamos:prover,prever¦1istamos:vestir¦1irvamos:servir¦4jamos:rever¦4nhamos:deter,reter,obter¦1ulamos:polir¦4quemos:abraçar¦4amos:morder,treler,curtir,exibir,condir,garrir¦3idamos:agredir¦3istamos:investir¦2quemos:coçar,roçar,laçar¦3nhamos:ater¦5idamos:progredir¦3quemos:calçar,forçar,atiçar¦5emos:mobiliar¦3intamos:assentir¦7jamos:entrever,interver¦2enhamos:avir¦4iamos:reler¦7amos:dissentir¦1amos:rer¦9amos:retrogredir¦8amos:correferir¦2ictamos:flectir¦1onhamos:pôr¦2gamos:dizer¦1jamos:agir¦1igamos:seguir¦1iramos:ferir,gerir¦4çamos:impedir¦1urtamos:sortir¦1coitemos:açoitar¦3jamos:monger¦6jamos:absterger"
    },
    "firstPlural": {
      "fwd": "onde:ôr¦coitai:çoitar¦3cai:rinçar",
      "both": "2:hir,cir,zir,pir,nir,lir,rir,bir,dir,gir,mir,tir¦3:ssir¦4:nquir,nguir,eguir¦5:servir¦5de:terver¦5nde:treter,tervir¦4de:tever,orrir¦4nde:rovir¦3cai:troçar¦3de:crer¦3nde:avir,evir,ster,bter,nvir,nter¦2çais:ouvir¦1í:uir,air¦1nde:or¦i:r",
      "rev": "r:nde¦1r:ede,ide¦2r:vi¦2çar:mocai¦3çar:bracai¦4çar:trincai",
      "ex": "4:ouvir¦5:servir¦1de:ir¦2de:ser,ver,rir,ler¦2nde:vir,ter¦3de:crer¦5de:prover,prever¦4de:rever,reler¦4nde:deter,reter,advir¦4cai:abraçar,remoçar¦2cai:coçar,roçar,laçar¦3nde:ater,avir¦3cai:calçar,forçar,atiçar¦7de:entrever¦1onde:pôr¦1coitai:açoitar"
    },
    "secondPlural": {
      "fwd": "onham:ôr¦jam:gir,ger¦igam:eguir¦iram:erir¦itam:etir¦am:uer¦çam:cir¦urtam:ortir¦coitem:çoitar¦1jam:aver¦1am:mer,rer,ber,her,per,ser,hir¦1gam:izer¦1em:iar¦2am:itir,ndir,rter,mbir,ulir,idir,irir,rdir¦2eiem:nsiar¦2çam:pedir,medir¦2quem:inçar¦3em:iguar,nquar¦3am:arrir¦4em:inguar,coitar",
      "both": "5am:ementir,flectir,mprazer¦5jam:terver¦5ejam:brestar¦5idam:ansgredir¦5nham:treter¦4uem:umegar,amegar,elegar¦4em:foitar,noitar¦4am:inibir,opelir,xceler,sorver,rreter,epolir,rantir,orrir¦4intam:ressentir¦4jam:tever¦4eiem:cendiar¦4iram:equerer¦4enham:tervir¦3am:bolir,arzir,abrir,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3uem:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3em:bitar,titar,gitar,vitar,ejuar,pitar,uitar,sitar,litar,citar,mitar,ditar,ritar,eitar¦3quem:emoçar,troçar,braçar¦3idam:egredir¦3iam:crer¦3eiem:mediar¦3nham:ster,bter,nter¦3enham:rovir¦2am:lpir,orir,cuir,urir,alir,odir,plir,adir,ater,upir,imir,ozer,trir,over,udir,buir,nguir,tuir,lver,nuir,uzir,eder,utir,luir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2em:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,tuar,etar,rtar,utar,atar,nuar,ltar,star,ntar¦2úlem:baular¦2ízem:juizar¦2intam:smentir,nsentir¦2uem:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilam:mpelir,xpelir¦2ínem:ruinar¦2enham:avir,evir,dvir,nvir¦2ham:aler¦2cam:erder¦1údem:iudar¦1irvam:servir¦1çam:uvir,azer¦1ízem:aizar,eizar¦1úcem:iuçar¦1ísquem:aiscar¦1em:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjam:vergir¦1iram:arir¦1íbam:oibir¦1am:oer,nir,xer¦1ulam:golir¦1únam:eunir¦1iem:ear¦1nham:or¦1ibam:aber¦1ssam:oder¦óleguem:olegar¦irzam:erzir¦ínquam:inquir¦igram:egrir¦águem:aguar¦ispam:espir¦ubram:obrir¦équem:equar¦irtam:ertir¦ussam:ossir¦çam:cer¦cem:çar¦quem:car¦urmam:ormir",
      "rev": "ar:eem¦entir:intam¦ervir:irvam¦udar:údem¦iliar:íliem¦ectir:ictam¦1rer:eiram¦1zer:agam¦1r:eiam¦1gir:ijam,ujam,ljam¦1eguir:sigam¦1erir:firam,diram,giram,siram,tiram¦1etir:pitam,litam¦1edir:ridam¦1enir:vinam¦1estir:vistam¦1ar:tem¦1ir:venham¦2ar:stejam,viem,piem,oiem,fiem,ciem,riem,giem,diem,aiem,tiem,biem,siem,ziem,niem,uiem,miem,xiem¦2er:omam,rram,ebam,cham,fram,etam,emam,mpam,osam¦2gir:injam,urjam,eajam,erjam,oajam,unjam,arjam¦2r:vejam,tenham¦2ger:lejam,anjam,rejam,onjam¦2zer:digam¦2cir:arçam¦2uer:rgam¦3ir:vidam,cidam,uiram,undam,uspam,mitam,andam,indam,sidam,lidam,unham,umbam,bulam,redam,urzam,feram,ardam¦3ger:otejam¦3er:olham,ambam,ervam,ertam,ueram,orvam,relam,essam¦3ar:iliem,pliem,aliem,oliem¦3dir:xpeçam¦4dir:espeçam,impeçam,esmeçam¦4gir:terajam¦4ar:ziguem,reliem¦4ir:apulam,sentam,lanham¦4çar:trinquem¦4ger:sterjam¦5ar:pinquem,ginquem,aniguem",
      "ex": "vão:ir¦águem:aguar¦2jam:ser,ver,haver,reger,viger¦1enham:vir¦3ejam:estar¦2nham:ter¦1eem:dar¦3iram:querer¦3gam:trazer¦2am:rir¦2iam:ler¦1intam:sentir,mentir¦2çam:pedir,medir¦3am:abrir,dever,meter,jazer,arder,bulir,urdir¦3iam:crer¦3uem:pegar,negar,regar,cegar,legar,segar¦5jam:prover,prever¦1istam:vestir¦1irvam:servir¦4jam:rever¦2eiem:odiar¦4nham:deter,reter¦1ulam:polir¦4am:curtir,cuspir,ferver,inibir,sorver,treler,zurzir,condir,surdir,garrir¦2em:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idam:agredir¦3eiem:mediar,ansiar¦4inam:prevenir¦3istam:investir,revestir¦2údem:saudar¦2quem:coçar,roçar,laçar¦3nham:ater¦5idam:progredir¦3quem:calçar,forçar,atiçar¦3em:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4uem:alegar¦3íliem:mobiliar¦3intam:assentir¦7jam:entrever¦2enham:avir¦4iam:reler¦1usquem:moscar¦4intam:ressentir¦7am:dissentir¦1am:rer¦9am:retrogredir¦8am:correferir¦2ictam:flectir¦4em:poitar¦1onham:pôr¦2gam:dizer¦1jam:agir¦1igam:seguir¦1iram:ferir,gerir¦4çam:impedir¦7em:averiguar¦1urtam:sortir¦5em:minguar¦1coitem:açoitar"
    },
    "thirdPlural": {
      "fwd": "",
      "both": "",
      "rev": "",
      "ex": ""
    }
  },
  "imperfect": {
    "first": {
      "fwd": "usesse:ôr¦coitasse:çoitar¦2ivesse:ster¦2casse:inçar",
      "both": "5ivesse:brestar¦5isse:ntrever¦5esse:tervir¦4casse:stroçar¦4isse:terver¦4esse:rovir¦4ivesse:treter¦3casse:emoçar,braçar¦3izesse:sprazer¦3esse:avir,evir,nvir¦3ouvesse:mprazer¦3isse:tever¦2ísse:cuir,buir,tuir,nuir,luir,ruir,suir¦2ivesse:bter,nter¦1izesse:fazer¦1ouvesse:eaver¦1ísse:air¦1ssesse:izer¦usesse:or¦oubesse:aber¦udesse:oder¦sse:r",
      "rev": "azer:izesse¦erer:isesse¦ir:ísse¦1r:iesse¦1azer:rouxesse,rouvesse,rouvesse/prazesse¦2er:evisse,etivesse¦3er:bstivesse,ustivesse¦4çar:trincasse",
      "ex": "fosse:ir¦1izesse:fazer¦2esse:vir¦1isse:ver¦3ivesse:estar,deter,reter¦1ivesse:ter¦1esse:dar¦1ouvesse:haver¦2isesse:querer¦2ouxesse:trazer¦4isse:prever¦3isse:rever¦4esse:advir¦3ouvesse:aprazer¦2casse:coçar,roçar,laçar¦2ivesse:ater¦4ísse:arguir¦2ouvesse/prazesse:prazer¦3casse:calçar,forçar,atiçar¦2ísse:ruir,puir¦3esse:avir¦1usesse:pôr¦1coitasse:açoitar"
    },
    "second": {
      "fwd": "usesses:ôr¦coitasses:çoitar¦2ivesses:ster¦2casses:inçar",
      "both": "5ivesses:brestar¦5isses:ntrever¦5ssem:rassar¦5esses:tervir¦4casses:stroçar¦4isses:terver¦4esses:rovir¦4ivesses:treter¦3casses:emoçar,braçar¦3izesses:sprazer¦3ssem:doer¦3esses:avir,evir,nvir¦3ouvesses:mprazer¦3isses:tever¦2ísses:cuir,buir,tuir,nuir,luir,ruir,suir¦2ivesses:bter,nter¦1izesses:fazer¦1ouvesses:eaver¦1ísses:air¦1ssesses:izer¦usesses:or¦oubesses:aber¦udesses:oder¦sses:r",
      "rev": "azer:izesses,ouvessem¦erer:isesses¦ir:ísses¦1r:iesses,issem¦1azer:rouxesses,rouvessem/prazessem¦2r:oessem,tessem¦2er:evisses¦3er:bstivesses,ustivesses¦4çar:trincasses",
      "ex": "fosses:ir¦1izesses:fazer¦2esses:vir¦1isses:ver¦3ivesses:estar,deter,reter¦1ivesses:ter¦1esses:dar¦1ouvesses:haver¦2isesses:querer¦2ouxesses:trazer¦3ssem:doer¦4isses:prever¦3isses:rever¦4esses:advir¦3ouvessem:aprazer¦2casses:coçar,roçar,laçar¦2ivesses:ater¦4ísses:arguir¦2ouvessem/prazessem:prazer¦3casses:calçar,forçar,atiçar¦2ísses:ruir,puir¦8ssem:concernir¦4ssem:urgir,later¦3esses:avir¦9ssem:obstringir¦1usesses:pôr¦1coitasses:açoitar"
    },
    "third": {
      "fwd": "usesse:ôr¦coitasse:çoitar¦2sse:xer,ser¦2ivesse:ster¦2casse:inçar¦3sse:iver¦5sse:coitar",
      "both": "5sse:quitar,ltitar,noitar,rreter¦5ivesse:brestar¦5isse:ntrever¦5esse:tervir¦4sse:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4isse:terver,ntever¦4esse:rovir¦4ivesse:treter¦3casse:emoçar,troçar¦3sse:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3esse:evir,avir,dvir,nvir¦3ísse:ssuir¦2ísse:cuir,tuir,buir,nuir,luir,ruir¦2sse:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivesse:bter,nter¦1ouvesse:eaver¦1ísse:air¦1ssesse:izer¦1sse:ir¦usesse:or¦oubesse:aber¦udesse:oder¦izesse:azer",
      "rev": "erer:isesse¦ir:ísse¦1r:iesse¦1azer:rouxesse,rouvesse¦2er:evisse,etivesse¦2r:tesse,tasse¦3r:evesse,azesse,ozesse,osesse,exesse¦3çar:bracasse¦4r:vivesse,ervesse¦4çar:trincasse¦5r:ressesse",
      "ex": "fosse:ir¦2esse:vir¦1isse:ver¦3ivesse:estar,deter,reter¦1ivesse:ter¦1esse:dar¦1ouvesse:haver¦2isesse:querer¦2ouxesse:trazer¦2sse:ler,rer¦4sse:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4isse:prever¦3isse:rever¦4casse:abraçar¦2casse:coçar,roçar,laçar¦2ivesse:ater¦4ísse:arguir¦5sse:ferver,quitar,poitar¦5ouvesse:comprazer¦3casse:calçar,forçar,atiçar¦2ísse:ruir,puir¦3sse:atar¦3esse:avir¦6sse:afoitar¦8sse:circuitar¦1usesse:pôr¦4ivesse:abster,suster¦1coitasse:açoitar"
    },
    "firstPlural": {
      "fwd": "uséssemos:ôr¦coitássemos:çoitar¦2ivéssemos:ster¦2cássemos:inçar",
      "both": "5ivéssemos:brestar¦5íssemos:ntrever¦5éssemos:tervir¦4íssemos:terver¦4êssemos:rreter¦4ouvéssemos:omprazer¦4éssemos:rovir¦4ivéssemos:treter¦3cássemos:troçar,braçar¦3éssemos:avir,evir,nvir¦3íssemos:tever¦3êssemos:meter¦3ivéssemos:onter,anter¦2êssemos:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivéssemos:bter¦1êssemos:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvéssemos:eaver¦1sséssemos:izer¦uséssemos:or¦oubéssemos:aber¦ássemos:ar¦íssemos:ir¦udéssemos:oder¦izéssemos:azer",
      "rev": "erer:iséssemos¦er:êssemos¦1r:iéssemos¦1azer:rouxéssemos¦2er:evíssemos,etivéssemos¦2çar:mocássemos¦3er:bstivéssemos,ustivéssemos¦4çar:trincássemos",
      "ex": "fôssemos:ir¦2éssemos:vir¦1íssemos:ver¦3ivéssemos:estar,deter,reter¦1ivéssemos:ter¦1éssemos:dar¦1ouvéssemos:haver¦2iséssemos:querer¦2ouxéssemos:trazer¦1êssemos:ler,rer¦4íssemos:prever¦3íssemos:rever¦4éssemos:advir¦3êssemos:meter,jazer¦2cássemos:coçar,roçar,laçar¦2ivéssemos:ater¦3cássemos:calçar,forçar,atiçar¦3éssemos:avir¦4cássemos:remoçar¦1uséssemos:pôr¦1coitássemos:açoitar"
    },
    "secondPlural": {
      "fwd": "usésseis:ôr¦coitásseis:çoitar¦2ivésseis:ster¦2cásseis:inçar",
      "both": "5ivésseis:brestar¦5ísseis:ntrever¦5ésseis:tervir¦4ísseis:terver¦4êsseis:rreter¦4ouvésseis:omprazer¦4ésseis:rovir¦4ivésseis:treter¦3cásseis:troçar,braçar¦3ésseis:avir,evir,nvir¦3ísseis:tever¦3êsseis:meter¦3ivésseis:onter,anter¦2êsseis:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivésseis:bter¦1êsseis:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvésseis:eaver¦1ssésseis:izer¦usésseis:or¦oubésseis:aber¦ásseis:ar¦ísseis:ir¦udésseis:oder¦izésseis:azer",
      "rev": "erer:isésseis¦er:êsseis¦1r:iésseis¦1azer:rouxésseis¦2er:evísseis,etivésseis¦2çar:mocásseis¦3er:bstivésseis,ustivésseis¦4çar:trincásseis",
      "ex": "fôsseis:ir¦2ésseis:vir¦1ísseis:ver¦3ivésseis:estar,deter,reter¦1ivésseis:ter¦1ésseis:dar¦1ouvésseis:haver¦2isésseis:querer¦2ouxésseis:trazer¦1êsseis:ler,rer¦4ísseis:prever¦3ísseis:rever¦4ésseis:advir¦3êsseis:meter,jazer¦2cásseis:coçar,roçar,laçar¦2ivésseis:ater¦3cásseis:calçar,forçar,atiçar¦3ésseis:avir¦4cásseis:remoçar¦1usésseis:pôr¦1coitásseis:açoitar"
    },
    "thirdPlural": {
      "fwd": "usessem:ôr¦coitassem:çoitar¦2ssem:xer,ser¦2ivessem:ster¦2cassem:inçar¦3ssem:iver¦5ssem:coitar",
      "both": "5ssem:quitar,ltitar,noitar,rreter¦5ivessem:brestar¦5issem:ntrever¦5essem:tervir¦4ssem:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4issem:terver,ntever¦4essem:rovir¦4ivessem:treter¦3cassem:emoçar,troçar¦3ssem:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3essem:evir,avir,dvir,nvir¦3íssem:ssuir¦2íssem:cuir,tuir,buir,nuir,luir,ruir¦2ssem:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivessem:bter,nter¦1ouvessem:eaver¦1íssem:air¦1ssessem:izer¦1ssem:ir¦usessem:or¦oubessem:aber¦udessem:oder¦izessem:azer",
      "rev": "erer:isessem¦ir:íssem¦1r:iessem¦1azer:rouxessem,rouvessem¦2er:evissem,etivessem¦2r:tessem,tassem¦3r:evessem,azessem,ozessem,osessem,exessem¦3çar:bracassem¦4r:vivessem,ervessem¦4çar:trincassem¦5r:ressessem",
      "ex": "fossem:ir¦2essem:vir¦1issem:ver¦3ivessem:estar,deter,reter¦1ivessem:ter¦1essem:dar¦1ouvessem:haver¦2isessem:querer¦2ouxessem:trazer¦2ssem:ler,rer¦4ssem:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4issem:prever¦3issem:rever¦4cassem:abraçar¦2cassem:coçar,roçar,laçar¦2ivessem:ater¦4íssem:arguir¦5ssem:ferver,quitar,poitar¦5ouvessem:comprazer¦3cassem:calçar,forçar,atiçar¦2íssem:ruir,puir¦3ssem:atar¦3essem:avir¦6ssem:afoitar¦8ssem:circuitar¦1usessem:pôr¦4ivessem:abster,suster¦1coitassem:açoitar"
    }
  },
  "pastTense": {
    "first": {
      "fwd": "2:tir,mir,gir,dir,bir,rir,lir,pir,cir,hir¦3:ssir¦i:er¦us:ôr¦coitei:çoitar¦2ive:ster¦2quei:inçar",
      "both": "2:nir,zir¦3:quir,uvir¦4:nguir,eguir¦5:servir¦5ive:brestar¦5m:tervir¦4ou:rassar¦4m:rovir¦4ive:treter¦3m:avir,evir,dvir,nvir¦3quei:troçar,braçar¦3iz:sprazer¦3u:doer¦3ouve:mprazer¦2í:moer,roer¦2ive:bter,nter¦1iz:fazer¦1í:uir,air¦1ouve:eaver¦1uei:gar¦1sse:izer¦us:or¦cei:çar¦quei:car¦oube:aber¦ude:oder¦ei:ar",
      "rev": "azer:iz,ouve/prazeu¦erer:is¦r:m¦1azer:rouxe,rouve¦1er:ci,xi,oí,oi¦1r:iu¦2er:omi,rri,evi,ebi,egi,ati,ovi,lhi,chi,fri,avi,etive,lvi,ivi,azi,ozi,mpi,osi,cri¦2r:oeu,teu¦2çar:moquei¦3er:endi,erdi,meti,bstive,rgui,ambi,cedi,angi,erti,vali,enzi,orvi,reli,celi,essi,ordi¦3r:nti,igi,ubi,ugi,pri,umi,sti,bri,idi,uti,oli,eri,spi,iti,agi,udi,ori,tri,imi,upi,uri,lpi,rgi,rpi,adi,ibi,uli,pli,iri,nhi,odi,lgi,cti¦4r:arti,ormi,ingi,leti,undi,redi,andi,indi,arci,peli,pedi,umbi,rami,urdi,ungi,bali,medi,ardi¦4er:pondi,condi,rreti,premi¦4çar:trinquei¦5er:equeri,-queri,lqueri¦5r:epeti,mpeti,negri,stali",
      "ex": "2:rir¦3:agir,adir¦4:pedir,medir,falir,parir,latir,remir,ungir,delir,balir,urdir¦5:servir,sorrir,tossir,curtir,sortir,surtir,fremir,condir,garrir¦7:divertir,advertir¦fui:ir¦1iz:fazer¦2m:vir¦3ive:estar,deter,reter¦1ive:ter¦1ouve:haver¦2is:querer¦2ouxe:trazer¦3u:doer¦2í:roer,moer,soer¦3ouve:aprazer¦2quei:coçar,roçar,laçar¦2ive:ater¦2ouve/prazeu:prazer¦3quei:calçar,forçar,atiçar¦8u:concernir¦4u:urgir,later¦3m:avir¦4quei:remoçar¦9u:obstringir¦1i:ver,ler¦1us:pôr¦2i:crer¦3i:valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦4i:tremer,ferver,premer,monger¦4ive:suster¦6i:interver¦1coitei:açoitar¦7i:absterger"
    },
    "second": {
      "fwd": "useste:ôr¦coitaste:çoitar¦2iveste:ster¦2caste:inçar",
      "both": "5iveste:brestar¦5iste:ntrever¦5este:tervir¦4caste:stroçar¦4iste:terver¦4am:doer¦4este:rovir¦4iveste:treter¦3caste:emoçar,braçar¦3izeste:sprazer¦3este:avir,evir,nvir¦3ouveste:mprazer¦3iste:tever¦2íste:cuir,buir,tuir,nuir,luir,ruir,suir¦2iveste:bter,nter¦1izeste:fazer¦1ouveste:eaver¦1íste:air¦1sseste:izer¦useste:or¦oubeste:aber¦udeste:oder¦ste:r",
      "rev": "2:aram,iram¦3:oeram,teram¦azer:izeste,ouveram¦erer:iseste¦ir:íste¦1r:ieste¦1azer:rouxeste,rouveram/prazeram¦2er:eviste,etiveste¦3er:ustiveste¦4çar:trincaste",
      "ex": "foste:ir¦1izeste:fazer¦2este:vir¦1iste:ver¦3iveste:estar,deter,reter¦1iveste:ter¦1este:dar¦1ouveste:haver¦2iseste:querer¦2ouxeste:trazer¦4am:doer¦4iste:prever¦3iste:rever¦4este:advir¦3ouveram:aprazer¦2caste:coçar,roçar,laçar¦2iveste:ater¦4íste:arguir¦2ouveram/prazeram:prazer¦3caste:calçar,forçar,atiçar¦7am:grassar¦2íste:ruir,puir¦9am:concernir¦5am:urgir,later¦3este:avir¦10am:obstringir¦1useste:pôr¦4iveste:abster¦1coitaste:açoitar"
    },
    "third": {
      "fwd": "coitou:çoitar¦1s:ôr¦2cou:inçar¦3ve:ster",
      "both": "5eve:brestar¦5u:rreter¦5ve:treter¦4iu:terver,ntever¦4u:orver,meter,caver,rever¦4ouve:omprazer¦4ve:onter¦4eio:tervir¦3cou:emoçar,troçar,braçar¦3u:nzer,iver,rter,ozer,mber,lver,eder,over,ater,rder,eber,nder¦3eio:rovir¦2u:ser,uer,ler,per,oer,her,xer,ger,cer,rer,mer¦2eio:avir,evir,dvir,nvir¦1ouve:eaver¦1sse:izer¦1u:ir¦ôs:or¦oube:aber¦ou:ar¦ôde:oder¦ez:azer",
      "rev": "ir:eio¦erer:is¦1azer:rouxe¦1r:eu¦2er:eviu¦3r:nteve,eteve¦4r:bsteve,usteve¦4çar:trincou",
      "ex": "foi:ir¦1eio:vir¦1iu:ver¦3eve:estar¦2ve:ter¦1eu:dar¦1ouve:haver¦2is:querer¦2ouxe:trazer¦2u:ler,rer¦5ve:manter¦4u:dever,meter,jazer¦4iu:prever¦3iu:rever¦4ve:deter,reter,obter¦2cou:coçar,roçar,laçar¦3ve:ater¦5u:ferver¦3cou:calçar,forçar,atiçar¦6iu:entrever¦2eio:avir¦2s:pôr¦1coitou:açoitar"
    },
    "firstPlural": {
      "fwd": "usemos:ôr¦coitamos:çoitar¦2mos:xer,ser¦2ivemos:ster¦2camos:inçar¦3mos:iver¦5mos:coitar",
      "both": "5mos:quitar,ltitar,noitar,rreter¦5ivemos:brestar¦5imos:ntrever¦5emos:tervir¦4mos:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4imos:terver,ntever¦4emos:rovir¦4ivemos:treter¦3camos:emoçar,troçar¦3mos:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3emos:evir,avir,dvir,nvir¦3ímos:ssuir¦2ímos:cuir,tuir,buir,nuir,luir,ruir¦2mos:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivemos:bter,nter¦1ouvemos:eaver¦1ímos:air¦1ssemos:izer¦1mos:ir¦usemos:or¦oubemos:aber¦udemos:oder¦izemos:azer",
      "rev": "erer:isemos¦ir:ímos¦1r:iemos¦1azer:rouxemos,rouvemos¦2er:evimos,etivemos¦2r:temos,tamos¦3r:evemos,azemos,ozemos,osemos,exemos¦3çar:bracamos¦4r:vivemos,ervemos¦4çar:trincamos¦5r:ressemos",
      "ex": "fomos:ir¦2emos:vir¦1imos:ver¦3ivemos:estar,deter,reter¦1ivemos:ter¦1emos:dar¦1ouvemos:haver¦2isemos:querer¦2ouxemos:trazer¦2mos:ler,rer¦4mos:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4imos:prever¦3imos:rever¦4camos:abraçar¦2camos:coçar,roçar,laçar¦2ivemos:ater¦4ímos:arguir¦5mos:ferver,quitar,poitar¦5ouvemos:comprazer¦3camos:calçar,forçar,atiçar¦2ímos:ruir,puir¦3mos:atar¦3emos:avir¦6mos:afoitar¦8mos:circuitar¦1usemos:pôr¦4ivemos:abster,suster¦1coitamos:açoitar"
    },
    "secondPlural": {
      "fwd": "usestes:ôr¦coitastes:çoitar¦2stes:xer,ser¦2ivestes:ster¦2castes:inçar¦3stes:iver¦5stes:coitar",
      "both": "5stes:quitar,ltitar,noitar,rreter¦5ivestes:brestar¦5istes:ntrever¦5estes:tervir¦4stes:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4istes:terver,ntever¦4estes:rovir¦4ivestes:treter¦3castes:emoçar,troçar¦3stes:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3estes:evir,avir,dvir,nvir¦3ístes:ssuir¦2ístes:cuir,tuir,buir,nuir,luir,ruir¦2stes:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivestes:bter,nter¦1ouvestes:eaver¦1ístes:air¦1ssestes:izer¦1stes:ir¦usestes:or¦oubestes:aber¦udestes:oder¦izestes:azer",
      "rev": "erer:isestes¦ir:ístes¦1r:iestes¦1azer:rouxestes,rouvestes¦2er:evistes,etivestes¦2r:testes,tastes¦3r:evestes,azestes,ozestes,osestes,exestes¦3çar:bracastes¦4r:vivestes,ervestes¦4çar:trincastes¦5r:ressestes",
      "ex": "fostes:ir¦2estes:vir¦1istes:ver¦3ivestes:estar,deter,reter¦1ivestes:ter¦1estes:dar¦1ouvestes:haver¦2isestes:querer¦2ouxestes:trazer¦2stes:ler,rer¦4stes:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4istes:prever¦3istes:rever¦4castes:abraçar¦2castes:coçar,roçar,laçar¦2ivestes:ater¦4ístes:arguir¦5stes:ferver,quitar,poitar¦5ouvestes:comprazer¦3castes:calçar,forçar,atiçar¦2ístes:ruir,puir¦3stes:atar¦3estes:avir¦6stes:afoitar¦8stes:circuitar¦1usestes:pôr¦4ivestes:abster,suster¦1coitastes:açoitar"
    },
    "thirdPlural": {
      "fwd": "useram:ôr¦coitaram:çoitar¦2iveram:ster¦2caram:inçar¦3am:xer,ser¦4am:iver",
      "both": "5am:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iveram:brestar,ntreter¦5iram:ntrever¦4am:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4iram:terver¦4ou:saguar¦4eram:rovir¦3caram:emoçar,troçar,braçar¦3am:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3eram:avir,evir,dvir,nvir¦3ouveram:mprazer¦3iram:tever¦2iveram:bter,nter¦1íram:uir,air¦1ouveram:eaver¦1sseram:izer¦useram:or¦ouberam:aber¦uderam:oder¦izeram:azer",
      "rev": "3:çaram,teram,taram,uiram¦4:everam,azeram,ozeram,oseram,exeram¦5:viveram,erveram,esseram¦erer:iseram¦1r:ieram¦1azer:rouxeram¦2er:eviram,etiveram¦3er:bstiveram,ustiveram¦4çar:trincaram",
      "ex": "foram:ir¦2eram:vir¦1iram:ver¦3iveram:estar,deter,reter¦1iveram:ter¦1eram:dar¦1ouveram:haver¦2iseram:querer¦2ouxeram:trazer¦3am:rir,ler,rer¦7eram:intervir¦5am:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7am:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4iram:prever¦6am:servir,traçar,ferver,poitar¦3iram:rever¦2caram:coçar,roçar,laçar¦2iveram:ater¦3caram:calçar,forçar,atiçar¦8am:derreter,saltitar,engraçar,morraçar¦4am:atar,içar¦10am:despedaçar,escorraçar,abiscoitar¦3eram:avir¦9am:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12am:desembaraçar¦1useram:pôr¦1coitaram:açoitar"
    }
  },
  "pluperfect": {
    "first": {
      "fwd": "a:¦usera:ôr¦coitara:çoitar¦2ivera:ster¦2cara:inçar",
      "both": "5ivera:brestar¦5ira:ntrever¦5era:tervir¦4cara:stroçar¦4ira:terver¦4era:rovir¦4ivera:treter¦3cara:emoçar,braçar¦3izera:sprazer¦3era:avir,evir,nvir¦3ouvera:mprazer¦3ira:tever¦2íra:cuir,buir,tuir,nuir,luir,ruir,suir¦2ivera:bter,nter¦1izera:fazer¦1ouvera:eaver¦1íra:air¦1ssera:izer¦usera:or¦oubera:aber¦udera:oder",
      "rev": "3:mara,tira,dara,lara,rera,mira,gira,dira,gara,rira,çara,uira,jara,cera,eara,rara,sara,xara,hara,lera,tera,tara,oera,hera,zara,lira,nara,oara,para,iara,uara,zira,nira,pira,vara,mera,uera,bara,pera,gera,bira,fara,hira¦4:ndera,evera,ncara,ebera,ssira,overa,avera,rcara,lvera,icara,ecara,scara,ucara,edera,rdera,lcara,exera,rvera,uvira,osera¦5:locara,vivera,arcira,tacara,vocara,hocara,focara,lacara,pocara,bocara,pacara,hacara,essera,sacara,bacara¦azer:izera,ouvera/prazera¦erer:isera¦ir:íra¦1r:iera¦1azer:rouxera,rouvera¦2er:evira,etivera¦3er:bstivera,ustivera",
      "ex": "fora:ir¦1izera:fazer¦2era:vir¦1ira:ver¦3ivera:estar,deter,reter¦1ivera:ter¦1era:dar¦1ouvera:haver¦2isera:querer¦2ouxera:trazer¦4ira:prever¦3ira:rever¦4era:advir¦3ouvera:aprazer¦2cara:coçar,roçar,laçar¦2ivera:ater¦4íra:arguir¦2ouvera/prazera:prazer¦3cara:calçar,forçar,atiçar¦2íra:ruir,puir¦3era:avir¦1usera:pôr¦3a:rir,ler,rer¦5a:viver,tocar,focar,jazer,cozer,tacar,sacar,locar,socar¦6a:servir,trocar,lamber,benzer,brocar¦10a:reciprocar¦7a:atracar,xerocar,retocar,entocar¦1coitara:açoitar¦7cara:destrinçar¦8a:derrocar¦9a:atarracar,desservir,esburacar"
    },
    "second": {
      "fwd": "as:¦useras:ôr¦coitaras:çoitar¦2iveras:ster¦2caras:inçar",
      "both": "5iveras:brestar¦5iras:ntrever¦5eras:tervir¦4caras:stroçar¦4iras:terver¦4am:doer¦4eras:rovir¦4iveras:treter¦3caras:emoçar,braçar¦3izeras:sprazer¦3eras:avir,evir,nvir¦3ouveras:mprazer¦3iras:tever¦2íras:cuir,buir,tuir,nuir,luir,ruir,suir¦2iveras:bter,nter¦1izeras:fazer¦1ouveras:eaver¦1íras:air¦1sseras:izer¦useras:or¦ouberas:aber¦uderas:oder",
      "rev": "2:aram,iram¦3:maras,tiras,daras,laras,reras,miras,giras,diras,garas,riras,çaras,uiras,jaras,ceras,earas,raras,saras,xaras,haras,leras,teras,taras,oeram,heras,zaras,liras,naras,oaras,paras,iaras,uaras,ziras,niras,piras,varas,meras,ueras,baras,peras,geras,biras,oeras,faras,hiras,teram¦4:nderas,everas,ncaras,eberas,ssiras,overas,averas,rcaras,lveras,icaras,ecaras,scaras,ucaras,ederas,rderas,lcaras,exeras,rveras,uviras,oseras¦5:locaras,viveras,arciras,tacaras,vocaras,hocaras,focaras,lacaras,pocaras,bocaras,pacaras,hacaras,esseras,sacaras,bacaras¦azer:izeras,ouveram,ouveram/prazeram¦erer:iseras¦ir:íras¦1r:ieras¦1azer:rouxeras¦2er:eviras,etiveras¦3er:bstiveras,ustiveras",
      "ex": "foras:ir¦1izeras:fazer¦2eras:vir¦1iras:ver¦3iveras:estar,deter,reter¦1iveras:ter¦1eras:dar¦1ouveras:haver¦2iseras:querer¦2ouxeras:trazer¦4am:doer¦4iras:prever¦3iras:rever¦4eras:advir¦3ouveram:aprazer¦2caras:coçar,roçar,laçar¦2iveras:ater¦4íras:arguir¦2ouveram/prazeram:prazer¦3caras:calçar,forçar,atiçar¦7am:grassar¦2íras:ruir,puir¦9am:concernir¦5am:urgir,later¦3eras:avir¦10am:obstringir¦1useras:pôr¦3as:rir,ler,rer¦5as:viver,tocar,focar,jazer,cozer,tacar,sacar,locar,socar¦6as:servir,trocar,lamber,benzer,brocar¦10as:reciprocar¦7as:atracar,xerocar,retocar,entocar¦1coitaras:açoitar¦7caras:destrinçar¦8as:derrocar¦9as:atarracar,desservir,esburacar"
    },
    "third": {
      "fwd": "usera:ôr¦coitara:çoitar¦2ivera:ster¦2cara:inçar¦3a:xer,ser¦4a:iver",
      "both": "5a:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5ivera:brestar,ntreter¦5ira:ntrever¦4a:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4ira:terver¦4era:rovir¦3cara:emoçar,troçar,braçar¦3a:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3era:avir,evir,dvir,nvir¦3ouvera:mprazer¦3ira:tever¦2ivera:bter,nter¦1íra:uir,air¦1ouvera:eaver¦1ssera:izer¦usera:or¦oubera:aber¦udera:oder¦izera:azer",
      "rev": "3:çara,tera,tara,uira¦4:evera,azera,ozera,osera,exera¦5:vivera,ervera,essera¦erer:isera¦1r:iera¦1azer:rouxera¦2er:evira,etivera¦3er:bstivera,ustivera¦4çar:trincara",
      "ex": "fora:ir¦2era:vir¦1ira:ver¦3ivera:estar,deter,reter¦1ivera:ter¦1era:dar¦1ouvera:haver¦2isera:querer¦2ouxera:trazer¦3a:rir,ler,rer¦7era:intervir¦5a:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7a:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4ira:prever¦6a:servir,traçar,ferver,poitar¦3ira:rever¦2cara:coçar,roçar,laçar¦2ivera:ater¦3cara:calçar,forçar,atiçar¦8a:derreter,saltitar,engraçar,morraçar¦4a:atar,içar¦10a:despedaçar,escorraçar,abiscoitar¦3era:avir¦9a:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12a:desembaraçar¦1usera:pôr¦1coitara:açoitar"
    },
    "firstPlural": {
      "fwd": "uséramos:ôr¦coitáramos:çoitar¦2ivéramos:ster¦2cáramos:inçar",
      "both": "5ivéramos:brestar¦5íramos:ntrever¦5éramos:tervir¦4íramos:terver¦4êramos:rreter¦4ouvéramos:omprazer¦4éramos:rovir¦4ivéramos:treter¦3cáramos:troçar,braçar¦3éramos:avir,evir,nvir¦3íramos:tever¦3êramos:meter¦3ivéramos:onter,anter¦2êramos:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivéramos:bter¦1êramos:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvéramos:eaver¦1sséramos:izer¦uséramos:or¦oubéramos:aber¦áramos:ar¦íramos:ir¦udéramos:oder¦izéramos:azer",
      "rev": "erer:iséramos¦er:êramos¦1r:iéramos¦1azer:rouxéramos¦2er:evíramos,etivéramos¦2çar:mocáramos¦3er:bstivéramos,ustivéramos¦4çar:trincáramos",
      "ex": "fôramos:ir¦2éramos:vir¦1íramos:ver¦3ivéramos:estar,deter,reter¦1ivéramos:ter¦1éramos:dar¦1ouvéramos:haver¦2iséramos:querer¦2ouxéramos:trazer¦1êramos:ler,rer¦4íramos:prever¦3íramos:rever¦4éramos:advir¦3êramos:meter,jazer¦2cáramos:coçar,roçar,laçar¦2ivéramos:ater¦3cáramos:calçar,forçar,atiçar¦3éramos:avir¦4cáramos:remoçar¦1uséramos:pôr¦1coitáramos:açoitar"
    },
    "secondPlural": {
      "fwd": "uséreis:ôr¦coitáreis:çoitar¦2ivéreis:ster¦2cáreis:inçar",
      "both": "5ivéreis:brestar¦5íreis:ntrever¦5éreis:tervir¦4íreis:terver¦4êreis:rreter¦4ouvéreis:omprazer¦4éreis:rovir¦4ivéreis:treter¦3cáreis:troçar,braçar¦3éreis:avir,evir,nvir¦3íreis:tever¦3êreis:meter¦3ivéreis:onter,anter¦2êreis:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivéreis:bter¦1êreis:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvéreis:eaver¦1sséreis:izer¦uséreis:or¦oubéreis:aber¦áreis:ar¦íreis:ir¦udéreis:oder¦izéreis:azer",
      "rev": "erer:iséreis¦er:êreis¦1r:iéreis¦1azer:rouxéreis¦2er:evíreis,etivéreis¦2çar:mocáreis¦3er:bstivéreis,ustivéreis¦4çar:trincáreis",
      "ex": "fôreis:ir¦2éreis:vir¦1íreis:ver¦3ivéreis:estar,deter,reter¦1ivéreis:ter¦1éreis:dar¦1ouvéreis:haver¦2iséreis:querer¦2ouxéreis:trazer¦1êreis:ler,rer¦4íreis:prever¦3íreis:rever¦4éreis:advir¦3êreis:meter,jazer¦2cáreis:coçar,roçar,laçar¦2ivéreis:ater¦3cáreis:calçar,forçar,atiçar¦3éreis:avir¦4cáreis:remoçar¦1uséreis:pôr¦1coitáreis:açoitar"
    },
    "thirdPlural": {
      "fwd": "useram:ôr¦coitaram:çoitar¦2iveram:ster¦2caram:inçar¦3am:xer,ser¦4am:iver",
      "both": "5am:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iveram:brestar,ntreter¦5iram:ntrever¦4am:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4iram:terver¦4eram:rovir¦3caram:emoçar,troçar,braçar¦3am:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3eram:avir,evir,dvir,nvir¦3ouveram:mprazer¦3iram:tever¦2iveram:bter,nter¦1íram:uir,air¦1ouveram:eaver¦1sseram:izer¦useram:or¦ouberam:aber¦uderam:oder¦izeram:azer",
      "rev": "3:çaram,teram,taram,uiram¦4:everam,azeram,ozeram,oseram,exeram¦5:viveram,erveram,esseram¦erer:iseram¦1r:ieram¦1azer:rouxeram¦2er:eviram,etiveram¦3er:bstiveram,ustiveram¦4çar:trincaram",
      "ex": "foram:ir¦2eram:vir¦1iram:ver¦3iveram:estar,deter,reter¦1iveram:ter¦1eram:dar¦1ouveram:haver¦2iseram:querer¦2ouxeram:trazer¦3am:rir,ler,rer¦7eram:intervir¦5am:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7am:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4iram:prever¦6am:servir,traçar,ferver,poitar¦3iram:rever¦2caram:coçar,roçar,laçar¦2iveram:ater¦3caram:calçar,forçar,atiçar¦8am:derreter,saltitar,engraçar,morraçar¦4am:atar,içar¦10am:despedaçar,escorraçar,abiscoitar¦3eram:avir¦9am:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12am:desembaraçar¦1useram:pôr¦1coitaram:açoitar"
    }
  },
  "presentTense": {
    "first": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦ita:etir¦a:uer¦ça:cir¦urta:ortir¦coite:çoitar¦1a:mer,rer,ber,her,per,ser¦1ga:izer¦1e:iar¦2a:itir,ndir,rter,nzer,idir,nzir,mbir,irir,ulir¦2eie:nsiar¦2ça:pedir¦2que:inçar¦3a:urtir,arrir¦3e:nquar,iguar¦4e:inguar,coitar",
      "both": "5a:eflorir,omburir,flectir,mplodir,nstruir,mprazer,estruir¦5s:erruir¦5mos:aforir,dernir,omedir,sequir¦5ja:terver¦5eja:brestar¦5es:scernir¦5o:xplodir¦5nha:treter¦4a:emunir,ebolir,stalir,etinir,opelir,esunir,clodir,rreter,epolir,efinir,rantir,orrir¦4e:ltitar,noitar¦4es:pingir,turdir,randir,epelir,olorir¦4ça:sprazer¦4ue:elegar¦4ia:screr¦4ja:tever¦4eie:cendiar¦4mos:caver¦4ira:equerer¦4enha:tervir¦3a:rurir,anhir,arzir,celer,runir,ardir,abrir,reler,ornir,rodir,unhir,nibir,xibir,rguir,fruir,order,meter,artir¦3ue:iegar,megar,negar,fegar,segar,pegar,vegar,regar,hegar¦3e:vitar,pitar,uitar,gitar,bitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3ça:smedir¦3que:troçar,braçar¦3inta:esmentir¦3ida:egredir,sgredir¦3ila:ompelir¦3es:aurir,rquir,molir¦3eie:mediar¦3nha:ster,bter,nter¦3enha:rovir¦2a:cuir,plir,upir,imir,ater,udir,trir,luir,buir,nguir,tuir,adir,nuir,uzir,eder,utir,suir,umir,prir,stir,ubir,nder,air¦2e:fuar,ruar,suar,duar,muar,xtar,juar,cuar,etar,ctar,ptar,otar,tuar,rtar,ltar,utar,atar,nuar,star,ntar¦2úle:baular¦2ímos:bair¦2íze:juizar¦2es:amir,rpir,atir¦2ue:rgar,ngar,sgar,lgar,igar,ugar,agar,ogar¦2ista:evestir¦2irna:ncernir¦2íne:ruinar¦2enha:avir,evir,dvir,nvir¦2inta:nsentir¦2ça:fazer¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1e:far,xar,bar,nar,zar,par,dar,var,har,oar,jar,rar,sar,lar,mar¦1irja:vergir¦1ira:arir¦1íba:oibir¦1ula:golir¦1ie:ear¦1a:oer,xer,ver¦1nha:or¦1iba:aber¦1ça:uvir¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦águe:aguar¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦ir:es¦unir:úna¦udar:úde¦iliar:ílie¦ectir:icta¦1zer:aça,aga¦1rer:eira¦1r:eia,emos,imos,is¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita,lita¦1edir:rida¦1enir:vina¦1estir:vista¦1ar:te¦1elir:pila¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,aza,mpa,osa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2ir:una,rua,ala,ena,lpa¦2cir:arça¦2uer:rga¦2çar:moque¦3ir:vida,cida,uira,unda,uspa,mita,anda,sida,umba,inda,pula,enta,bula,lida,reda,urza¦3ger:oteja¦3er:olha,amba,erta,enza,uera,essa¦3ar:ilie,alie,olie¦3dir:xpeça¦4dir:espeça,impeça¦4gir:teraja¦4ar:mplie,zigue,relie¦4ir:ranza,efera¦4çar:trinque¦4ger:sterja¦5ar:pinque,ginque,anigue",
      "ex": "vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger,urgir¦2ça:fazer,pedir,medir¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir,unir¦2ia:ler¦1inta:sentir,mentir¦3a:abrir,punir,meter,jazer,cozer,arder,zunir,balir,urdir,lenir,bulir¦3ia:crer¦5mos:reaver,florir,renhir¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4mos:falir,remir,vagir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦1ula:polir¦4es:abolir,fulgir,fremir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦2úna:reunir¦4a:cuspir,prazer,zurzir,surdir,curtir,condir,garrir¦3ida:agredir¦3eie:mediar,ansiar¦4ina:prevenir¦5a:aprazer,revenir¦3ista:investir¦2úde:saudar¦3es:banir,ungir,munir,delir,ganir,tinir¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦3s:ruir,puir¦4ue:alegar¦3ílie:mobiliar¦3ila:expelir¦6es:esculpir¦3inta:assentir¦6a:obstruir,fementir¦7ja:entrever¦5es:impelir¦5inta:pressentir¦2enha:avir¦3mos:adir¦4ia:reler¦4s:fruir,pruir¦1usque:moscar¦4inta:ressentir¦7mos:combalir¦10s:desobstruir¦7a:dissentir,insculpir¦1a:rer¦9a:retrogredir¦4que:remoçar¦8a:correferir¦5e:afoitar,minguar¦8mos:espavorir¦7s:abstruir¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦1coite:açoitar"
    },
    "second": {
      "fwd": "onhas:ôr¦jas:gir,ger¦igas:eguir¦iras:erir¦itas:etir¦as:uer¦ças:cir¦urtas:ortir¦coites:çoitar¦1as:mer,rer,ber,her,per,ser¦1gas:izer¦1es:iar¦2as:itir,ndir,rter,ulir,nzer,idir,nzir,mbir,irir¦2eies:nsiar¦2ças:pedir¦2ques:inçar¦3as:urtir,arrir¦3es:nquar,iguar¦4es:inguar,coitar",
      "both": "5:erruir¦5as:eflorir,omburir,flectir,mplodir,mprazer,nstruir,estruir¦5s:aforir,dernir,omedir,sequir¦5jas:terver¦5ejas:brestar¦5e:scernir¦5es:xplodir¦5nhas:treter¦4as:emunir,ebolir,stalir,morder,opelir,esunir,clodir,rreter,epolir,efinir,rantir,orrir¦4es:foitar,ltitar,noitar¦4e:pingir,turdir,randir,epelir,olorir¦4ças:sprazer¦4ues:elegar¦4ias:screr¦4em:rassar¦4jas:tever¦4eies:cendiar¦4is:caver¦4iras:equerer¦4enhas:tervir¦3as:rurir,tinir,arzir,urzir,celer,runir,ardir,abrir,reler,ornir,rodir,unhir,nibir,xibir,rguir,fruir,meter,artir¦3ues:iegar,megar,negar,fegar,segar,pegar,vegar,regar,hegar¦3ças:smedir¦3ques:troçar,braçar¦3intas:esmentir¦3idas:egredir,sgredir¦3es:pitar,uitar,gitar,bitar,litar,citar,sitar,mitar,vitar,ditar,ritar,eitar¦3ilas:ompelir¦3e:aurir,rquir,molir¦3eies:mediar¦3nhas:ster,bter,nter¦3enhas:rovir¦2as:cuir,moer,plir,roer,upir,imir,ater,trir,luir,udir,buir,nguir,tuir,adir,nuir,uzir,eder,utir,suir,umir,prir,stir,ubir,nder,air¦2es:fuar,ruar,suar,duar,muar,xtar,juar,cuar,etar,ctar,ptar,otar,tuar,rtar,ltar,utar,atar,nuar,star,ntar¦2úles:baular¦2ís:bair¦2ízes:juizar¦2e:amir,rpir,anir,atir¦2istas:evestir¦2irnam:ncernir¦2ues:rgar,ngar,sgar,lgar,igar,ugar,agar,ogar¦2am:doer¦2ínes:ruinar¦2enhas:avir,evir,nvir¦2intas:nsentir¦2ças:fazer¦2has:aler¦2cas:erder¦1údes:iudar¦1irvas:servir¦1ízes:aizar,eizar¦1úces:iuçar¦1ísques:aiscar¦1es:far,xar,nar,zar,bar,par,dar,var,har,oar,jar,rar,sar,lar,mar¦1irjas:vergir¦1iras:arir¦1íbas:oibir¦1ulas:golir¦1únas:eunir¦1ies:ear¦1as:xer,ver¦1nhas:or¦1ibas:aber¦1ças:uvir¦1ssas:oder¦ólegues:olegar¦irzas:erzir¦ínquas:inquir¦igras:egrir¦águes:aguar¦ispas:espir¦ubras:obrir¦éques:equar¦irtas:ertir¦ussas:ossir¦ças:cer¦ces:çar¦ques:car¦urmas:ormir",
      "rev": "ar:ês¦entir:intas¦ervir:irvas¦ir:e¦udar:údes¦iliar:ílies¦gir:jam¦ectir:ictas¦1zer:aças,agas¦1rer:eiras¦1r:eias,eis,i¦1gir:ijas,ujas,ljas¦1eguir:sigas¦1er:oam,oas,zam,tam¦1etir:pitas,litas¦1erir:diras,giras,firas,siras,tiras¦1edir:ridas¦1enir:vinas¦1ir:venhas¦1estir:vistas¦1ar:tes¦1elir:pilas¦2ar:stejas,vies,pies,oies,fies,cies,ries,gies,dies,aies,ties,bies,sies,zies,nies,uies,mies,xies¦2er:omas,rras,ebas,chas,fras,etas,emas,mpas,osas¦2gir:injas,urjas,eajas,erjas,oajas,unjas,arjas¦2r:vejas,tenhas,mis,lis,ris¦2ger:lejas,anjas,rejas,onjas¦2zer:digas¦2ir:unas,alas,enas,lpas¦2cir:arças¦2uer:rgas¦2çar:moques¦3ir:vidas,cidas,uiras,undas,uspas,mitas,andas,indas,sidas,umbas,anzas,entas,bulas,lidas,redas¦3ger:otejas¦3er:olhas,ambas,ertas,enzas,ueras,essas¦3ar:ilies,olies,alies¦3dir:xpeças¦3r:nhis,agis¦4dir:espeças,impeças¦4gir:terajas¦4ar:mplies,zigues,relies¦4ir:struas,apulas,eferas¦4çar:trinques¦4ger:sterjas¦5ar:pinques,ginques,anigues",
      "ex": "3:ruir,puir¦4:fruir,pruir¦7:abstruir¦10:desobstruir¦vás:ir¦águes:aguar¦2jas:ser,ver,haver,reger,viger¦2ças:fazer,pedir,medir¦1enhas:vir¦3ejas:estar¦2nhas:ter¦1ês:dar¦3iras:querer¦3gas:trazer¦2as:rir,unir,roer,moer,poer¦2ias:ler¦1intas:sentir,mentir¦3as:abrir,punir,meter,jazer,cozer,arder,zunir,balir,urdir,lenir,bulir¦3ias:crer¦5is:reaver¦3ues:pegar,negar,regar,cegar,legar,segar¦5jas:prover,prever¦1istas:vestir¦2am:doer¦1irvas:servir¦4s:falir,remir,vagir¦4jas:rever¦2eies:odiar¦4nhas:deter,reter¦1ulas:polir¦4e:abolir,fulgir,fremir¦2es:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦4as:cuspir,morder,surdir,curtir,condir,garrir¦3idas:agredir¦3eies:mediar,ansiar¦4inas:prevenir¦3enhas:advir¦5am:aprazer¦5s:florir,renhir¦3istas:investir¦2údes:saudar¦2ques:coçar,roçar,laçar¦3nhas:ater¦5idas:progredir¦4am:prazer¦3ques:calçar,forçar,atiçar¦3es:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4ues:alegar¦3ílies:mobiliar¦3ilas:expelir¦6e:esculpir¦3intas:assentir¦6as:obstruir,fementir¦7jas:entrever¦5e:impelir¦3e:ungir,munir,delir,tinir¦5intas:pressentir¦2jam:urgir¦2enhas:avir¦3s:adir¦4ias:reler¦1usques:moscar¦4intas:ressentir¦3am:later¦7s:combalir¦7as:dissentir,insculpir¦5as:revenir,planhir¦1as:rer¦9as:retrogredir¦4ques:remoçar¦8as:correferir¦8s:espavorir¦7jam:obstringir¦2ictas:flectir¦4es:poitar¦1onhas:pôr¦2gas:dizer¦1jas:agir¦1igas:seguir¦1iras:ferir,gerir¦4ças:impedir¦7es:averiguar¦1urtas:sortir¦5es:minguar¦1coites:açoitar"
    },
    "third": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦ita:etir¦a:uer¦ça:cir¦urta:ortir¦coite:çoitar¦1ja:aver¦1a:mer,rer,ber,her,per,ser,hir¦1ga:izer¦1e:iar¦2a:itir,ndir,nzer,idir,mbir,rter,nzir,ulir,irir¦2eie:nsiar¦2ça:pedir,medir¦2que:inçar¦3a:urtir,arrir¦3e:iguar,nquar¦4e:inguar,coitar",
      "both": "5a:ementir,flectir,mplodir,mprazer,estruir,nstruir¦5mos:turdir,randir,epelir,olorir,emolir¦5eja:brestar¦5e:xplodir¦5nha:treter¦4a:mburir,etinir,opelir,xceler,esunir,clodir,rreter,epolir,efinir,rantir,orrir¦4ímos:erruir¦4e:ltitar,noitar¦4ue:elegar¦4inta:ressentir¦4ia:screr¦4mos:ernir,aurir,rquir¦4ida:nsgredir¦4ja:tever¦4eie:cendiar¦4ira:equerer¦4enha:tervir¦3a:munir,rurir,arzir,runir,ardir,abrir,reler,rodir,nibir,orver,xibir,rguir,fruir,order,meter,rever,artir¦3ue:iegar,megar,negar,fegar,segar,pegar,vegar,regar,hegar¦3e:vitar,bitar,extar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3que:emoçar,troçar,braçar¦3mos:amir,rpir,anir¦3inta:esmentir¦3ida:egredir¦3ila:ompelir¦3eie:mediar¦3nha:ster,bter,nter¦3ina:revenir¦3enha:rovir¦2a:cuir,alir,plir,adir,upir,imir,ater,trir,over,udir,buir,nguir,tuir,lver,nuir,uzir,eder,utir,luir,stir,suir,umir,prir,ubir,iver,nder,air¦2e:fuar,ruar,suar,duar,muar,juar,ctar,cuar,ptar,otar,tuar,etar,rtar,utar,atar,nuar,ltar,star,ntar¦2úle:baular¦2íze:juizar¦2ue:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ista:evestir¦2íne:ruinar¦2enha:avir,evir,dvir,nvir¦2ila:xpelir¦2inta:nsentir¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1ça:uvir,azer¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1e:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irja:vergir¦1ira:arir¦1íba:oibir¦1a:oer,xer¦1ula:golir¦1úna:eunir¦1ie:ear¦1nha:or¦1iba:aber¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦águe:aguar¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦udar:úde¦ir:ímos¦iliar:ílie¦ectir:icta¦1rer:eira¦1zer:aga¦1r:eia,imos¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita,lita¦1edir:rida¦1estir:vista¦1ar:te¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,mpa,osa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2ir:una,rua,rna,ena,ola,ora,lpa¦2cir:arça¦2uer:rga¦3ir:vida,cida,uira,unda,uspa,mita,anda,inda,sida,anza,umba,bula,lida,reda,urza¦3ger:oteja¦3er:olha,amba,erva,enza,erta,uera,essa¦3ar:ilie,plie,alie,olie,elie¦3dir:xpeça,smeça¦4dir:espeça,impeça¦4gir:teraja¦4ar:zigue,nigue¦4ir:apula,runha,senta,efera¦4çar:trinque¦5ar:pinque,ginque¦5ger:bsterja",
      "ex": "vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir,unir¦2ia:ler¦1inta:sentir,mentir¦2ça:pedir,medir¦3a:abrir,dever,punir,meter,jazer,cozer,arder,zunir,urdir,lenir,bulir¦3ia:crer¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦1ula:polir¦5mos:abolir,fulgir,fremir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦4a:cuspir,ferver,fornir,zurzir,surdir,curtir,condir,garrir¦3ida:agredir¦3eie:mediar,ansiar¦4mos:latir,ungir,munir,delir,tinir¦3ista:investir¦2úde:saudar¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦2ímos:ruir,puir¦4ue:alegar¦3ílie:mobiliar¦7mos:esculpir,impingir¦3inta:assentir¦6a:obstruir,reflorir¦7ja:entrever,interver¦6mos:impelir¦2enha:avir¦4ia:reler¦3ímos:fruir,pruir¦1usque:moscar¦4inta:ressentir¦9ímos:desobstruir¦7a:dissentir,insculpir¦5a:revenir,rebolir,planhir¦1a:rer¦9a:retrogredir¦8a:correferir¦5e:afoitar,minguar¦6ímos:abstruir¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦1coite:açoitar"
    },
    "firstPlural": {
      "fwd": "onhamos:ôr¦jamos:gir,ger¦igamos:eguir¦iramos:erir¦itamos:etir¦amos:uer¦çamos:cir¦urtamos:ortir¦coitemos:çoitar¦1amos:mer,rer,ber,bir,her,per,ser,hir¦1gamos:izer¦2amos:idir,itir,ndir,rter,ulir,nzer,nzir,irir¦2çamos:pedir,medir¦2quemos:inçar¦3amos:urtir,arrir",
      "both": "5amos:ementir,flectir,mplodir,mprazer,estruir,nstruir¦5s:turdir,cernir,epelir,olorir¦5jamos:terver¦5ejamos:brestar¦5nhamos:treter¦4amos:florir,ebolir,morder,opelir,xceler,clodir,inquir,rreter,orrir¦4iamos:screr¦4s:aurir,rquir,molir¦4jamos:tever¦4iramos:equerer¦4enhamos:tervir¦3amos:burir,rurir,tinir,arzir,urzir,ardir,abrir,ornir,rodir,polir,rguir,fruir,finir,meter,antir,ssuir,artir¦3quemos:emoçar,troçar,braçar¦3s:emir,amir,rpir,anir,atir¦3intamos:essentir,esmentir¦3idamos:egredir,sgredir¦3nhamos:ster,nter¦3ilamos:ompelir¦3inamos:revenir¦3enhamos:rovir¦2amos:cuir,alir,plir,upir,imir,ater,trir,buir,udir,unir,nguir,tuir,adir,nuir,uzir,eder,utir,luir,umir,prir,stir,nder,air¦2istamos:evestir¦2enhamos:avir,evir,nvir¦2ilamos:xpelir¦2intamos:nsentir¦2hamos:aler¦2camos:erder¦1irvamos:servir¦1irjamos:vergir¦1iramos:arir¦1amos:oer,xer,ver¦1ulamos:golir¦1nhamos:or¦1uemos:gar¦1çamos:uvir,azer¦1ssamos:oder¦irzamos:erzir¦igramos:egrir¦ispamos:espir¦ubramos:obrir¦irtamos:ertir¦ussamos:ossir¦çamos:cer¦cemos:çar¦quemos:car¦urmamos:ormir¦emos:ar",
      "rev": "entir:intamos¦ervir:irvamos¦ir:ís¦ectir:ictamos¦1rer:eiramos¦1zer:agamos¦1r:eiamos,is,imos¦1ber:aibamos¦1gir:ijamos,ujamos,ljamos¦1eguir:sigamos¦1erir:firamos,diramos,giramos,siramos,tiramos¦1etir:pitamos,litamos¦1edir:ridamos¦1estir:vistamos¦1ir:venhamos¦2ar:stejamos¦2er:omamos,rramos,ebamos,framos,emamos,chamos,azamos,mpamos,osamos¦2gir:injamos,urjamos,eajamos,erjamos,oajamos,unjamos,arjamos¦2r:vejamos,tenhamos¦2ger:lejamos,anjamos,rejamos¦2zer:digamos¦2cir:arçamos¦2ir:ruamos,enamos,lpamos¦2uer:rgamos¦3ir:vidamos,cidamos,uiramos,undamos,uspamos,oibamos,andamos,mitamos,umbamos,indamos,sidamos,entamos,bulamos,lidamos,nibamos,urdamos,anhamos¦3ger:otejamos¦3er:olhamos,ordamos,ambamos,ertamos,enzamos,ueramos¦3dir:xpeçamos,smeçamos¦4dir:espeçamos,impeçamos¦4gir:terajamos¦4ir:ranzamos,runhamos,gredamos,eferamos¦4çar:trinquemos¦5ir:capulamos¦5er:bressamos",
      "ex": "vamos:ir¦2jamos:ser,ver,haver,reger,viger¦1enhamos:vir¦3ejamos:estar¦2nhamos:ter¦3iramos:querer¦3gamos:trazer¦2amos:rir,unir¦2iamos:ler¦2ibamos:saber,caber¦1intamos:sentir,mentir¦2çamos:pedir,medir¦3amos:abrir,meter,jazer,cozer,arder,urdir,lenir,subir,bulir¦3iamos:crer¦5jamos:prover,prever¦1istamos:vestir¦1irvamos:servir¦4jamos:rever¦4nhamos:deter,reter,obter¦1ulamos:polir¦5s:abolir,fulgir¦4amos:cuspir,morder,treler,surdir,curtir,exibir,condir,garrir¦3idamos:agredir¦7mos:explodir¦3enhamos:advir¦3istamos:investir¦2quemos:coçar,roçar,laçar¦3nhamos:ater¦5idamos:progredir¦3quemos:calçar,forçar,atiçar¦2ís:ruir,puir¦7s:esculpir,impingir¦3intamos:assentir¦6amos:obstruir¦7jamos:entrever¦6s:impelir,brandir¦4s:ungir,munir,delir,tinir¦2enhamos:avir¦4iamos:reler¦3ís:fruir,pruir¦9ís:desobstruir¦7amos:dissentir,insculpir¦5amos:revenir¦1amos:rer¦9amos:retrogredir¦8amos:correferir¦5ís:derruir¦6ís:abstruir¦2ictamos:flectir¦1onhamos:pôr¦2gamos:dizer¦1jamos:agir¦1igamos:seguir¦1iramos:ferir,gerir¦4çamos:impedir¦1urtamos:sortir¦1coitemos:açoitar¦3jamos:monger¦6jamos:absterger"
    },
    "secondPlural": {
      "fwd": "onhais:ôr¦jais:gir,ger¦igais:eguir¦irais:erir¦itais:etir¦ais:uer¦çais:cir¦urtais:ortir¦coiteis:çoitar¦1ais:mer,rer,ber,bir,her,per,ser,hir¦1gais:izer¦2ais:idir,itir,ndir,rter,ulir,nzer,nzir,irir¦2çais:pedir,medir¦2queis:inçar¦3ais:urtir,arrir",
      "both": "5ais:ementir,flectir,mplodir,mprazer,nstruir,estruir¦5ejais:brestar¦5nhais:treter¦4ais:florir,ebolir,morder,opelir,xceler,rreter,orrir¦4em:pingir,turdir,randir,cernir,epelir,emolir,olorir¦4iais:screr¦4jais:tever¦4irais:equerer¦4enhais:tervir¦3ais:burir,rurir,tinir,arzir,urzir,ardir,abrir,ornir,rodir,nquir,polir,rguir,fruir,finir,meter,antir,ssuir,artir¦3queis:emoçar,troçar,braçar¦3intais:essentir,esmentir¦3idais:egredir,sgredir¦3nhais:ster,nter¦3ilais:ompelir¦3em:aurir,rquir¦3inais:revenir¦3enhais:rovir¦2ais:cuir,alir,plir,upir,imir,ater,trir,buir,udir,unir,nguir,tuir,adir,nuir,uzir,eder,utir,luir,umir,prir,stir,nder,air¦2enhais:avir,evir,nvir¦2em:emir,amir,rpir,anir¦2istais:evestir¦2ilais:xpelir¦2intais:nsentir¦2hais:aler¦2cais:erder¦1irvais:servir¦1irjais:vergir¦1irais:arir¦1ais:oer,xer,ver¦1ulais:golir¦1nhais:or¦1ueis:gar¦1çais:uvir,azer¦1ssais:oder¦irzais:erzir¦igrais:egrir¦ispais:espir¦ubrais:obrir¦irtais:ertir¦ussais:ossir¦çais:cer¦ceis:çar¦queis:car¦urmais:ormir¦eis:ar",
      "rev": "entir:intais¦ervir:irvais¦ir:em¦ectir:ictais¦1rer:eirais¦1zer:agais¦1r:eiais¦1ber:aibais¦1gir:ijais,ujais,ljais¦1eguir:sigais¦1erir:firais,dirais,girais,sirais,tirais¦1etir:pitais,litais¦1edir:ridais¦1ir:venhais¦1estir:vistais¦2ar:stejais¦2er:omais,rrais,ebais,frais,emais,etais,azais,mpais,osais,chais¦2gir:injais,urjais,eajais,rajais,erjais,oajais,unjais,arjais¦2r:vejais,tenhais¦2ger:lejais,anjais,rejais¦2zer:digais¦2cir:arçais¦2ir:ruais,odais,enais¦2uer:rgais¦3ir:vidais,cidais,uirais,undais,uspais,oibais,andais,mitais,umbais,indais,sidais,entais,bulais,lidais,nibais,urdais,anhais,ulpais¦3ger:otejais¦3er:olhais,ordais,ambais,ertais,enzais,uerais¦3dir:xpeçais,smeçais¦4dir:espeçais,impeçais¦4r:lodis¦4ir:ranzais,runhais,gredais,eferais¦4çar:trinqueis¦5ir:capulais¦5er:bressais",
      "ex": "vades:ir¦2jais:ser,ver,haver,reger,viger¦1enhais:vir¦3ejais:estar¦2nhais:ter¦3irais:querer¦3gais:trazer¦2ais:rir,unir¦2iais:ler¦2ibais:saber,caber¦1intais:sentir,mentir¦2çais:pedir,medir¦3ais:abrir,meter,jazer,cozer,arder,urdir,lenir,subir,bulir¦3iais:crer¦5jais:prover,prever¦1istais:vestir¦1irvais:servir¦4jais:rever¦4nhais:deter,reter,obter¦1ulais:polir¦4em:abolir,fulgir¦4ais:cuspir,morder,treler,surdir,curtir,exibir,condir,garrir¦3idais:agredir¦7s:explodir¦3enhais:advir¦3em:latir,ungir,munir,fruir,delir,tinir,pruir¦3istais:investir¦2queis:coçar,roçar,laçar¦3nhais:ater¦5idais:progredir¦3queis:calçar,forçar,atiçar¦2em:ruir,puir¦6em:esculpir,abstruir¦3intais:assentir¦6ais:obstruir¦7jais:entrever,interver¦5em:impelir,derruir¦2enhais:avir¦4iais:reler¦5ais:eclodir,revenir¦9em:desobstruir¦7ais:dissentir,insculpir¦1ais:rer¦9ais:retrogredir¦8ais:correferir¦2ictais:flectir¦1onhais:pôr¦2gais:dizer¦1jais:agir¦1igais:seguir¦1irais:ferir,gerir¦4çais:impedir¦1urtais:sortir¦1coiteis:açoitar¦3jais:monger¦6jais:absterger"
    },
    "thirdPlural": {
      "fwd": "onham:ôr¦jam:gir,ger¦igam:eguir¦iram:erir¦itam:etir¦am:uer¦çam:cir¦urtam:ortir¦coitem:çoitar¦1jam:aver¦1am:mer,rer,ber,her,per,ser,hir¦1gam:izer¦1em:iar¦2am:itir,ndir,rter,mbir,ulir,idir,irir,rdir¦2eiem:nsiar¦2çam:pedir,medir¦2quem:inçar¦3em:iguar,nquar¦3am:arrir¦4em:inguar,coitar",
      "both": "5am:ementir,flectir,mplodir,mprazer¦5jam:terver¦5ejam:brestar¦5em:xplodir¦5nham:treter¦4am:ebolir,inibir,opelir,xceler,clodir,rreter,epolir,rantir,orrir¦4em:foitar,noitar¦4uem:elegar¦4intam:ressentir¦4jam:tever¦4eiem:cendiar¦4iram:equerer¦4enham:tervir¦3uem:pegar,iegar,megar,negar,fegar,segar,vegar,regar,hegar¦3am:arzir,abrir,rodir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3em:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3quem:emoçar,troçar,braçar¦3idam:egredir,sgredir¦3iam:crer¦3eiem:mediar¦3nham:ster,bter,nter¦3enham:rovir¦2am:lpir,orir,cuir,urir,alir,plir,adir,ater,upir,imir,ozer,trir,over,udir,buir,nguir,tuir,lver,nuir,uzir,eder,utir,luir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2em:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,tuar,etar,rtar,utar,atar,nuar,ltar,star,ntar¦2úlem:baular¦2ízem:juizar¦2intam:smentir,nsentir¦2uem:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilam:mpelir,xpelir¦2ínem:ruinar¦2enham:avir,evir,dvir,nvir¦2ham:aler¦2cam:erder¦1údem:iudar¦1irvam:servir¦1çam:uvir,azer¦1ízem:aizar,eizar¦1úcem:iuçar¦1ísquem:aiscar¦1em:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjam:vergir¦1iram:arir¦1íbam:oibir¦1am:oer,nir,xer¦1ulam:golir¦1únam:eunir¦1iem:ear¦1nham:or¦1ibam:aber¦1ssam:oder¦óleguem:olegar¦irzam:erzir¦ínquam:inquir¦igram:egrir¦águem:aguar¦ispam:espir¦ubram:obrir¦équem:equar¦irtam:ertir¦ussam:ossir¦çam:cer¦cem:çar¦quem:car¦urmam:ormir",
      "rev": "ar:eem¦entir:intam¦ervir:irvam¦udar:údem¦iliar:íliem¦ectir:ictam¦1rer:eiram¦1zer:agam¦1r:eiam¦1gir:ijam,ujam,ljam¦1eguir:sigam¦1erir:firam,diram,giram,siram,tiram¦1etir:pitam,litam¦1edir:ridam¦1enir:vinam¦1estir:vistam¦1ar:tem¦1ir:venham¦2ar:stejam,viem,piem,oiem,fiem,ciem,riem,giem,diem,aiem,tiem,biem,siem,ziem,niem,uiem,miem,xiem¦2er:omam,rram,ebam,cham,fram,etam,emam,mpam,osam¦2gir:injam,urjam,eajam,erjam,oajam,unjam,arjam¦2r:vejam,tenham¦2ger:lejam,anjam,rejam,onjam¦2zer:digam¦2cir:arçam¦2uer:rgam¦3ir:vidam,cidam,uiram,undam,uspam,mitam,andam,indam,sidam,lidam,unham,umbam,bulam,redam,urzam,feram,ardam¦3ger:otejam¦3er:olham,ambam,ervam,ertam,ueram,relam,essam¦3ar:iliem,pliem,aliem,oliem¦3dir:xpeçam¦4dir:espeçam,impeçam,esmeçam¦4gir:terajam¦4ar:ziguem,reliem¦4ir:apulam,sentam,lanham¦4çar:trinquem¦4ger:sterjam¦5ar:pinquem,ginquem,aniguem",
      "ex": "vão:ir¦águem:aguar¦2jam:ser,ver,haver,reger,viger¦1enham:vir¦3ejam:estar¦2nham:ter¦1eem:dar¦3iram:querer¦3gam:trazer¦2am:rir¦2iam:ler¦1intam:sentir,mentir¦2çam:pedir,medir¦3am:abrir,dever,meter,jazer,arder,bulir,urdir¦3iam:crer¦3uem:pegar,negar,regar,cegar,legar,segar¦5jam:prover,prever¦1istam:vestir¦1irvam:servir¦4jam:rever¦2eiem:odiar¦4nham:deter,reter¦1ulam:polir¦4am:curtir,cuspir,ferver,inibir,treler,zurzir,condir,surdir,garrir¦2em:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idam:agredir¦3eiem:mediar,ansiar¦4inam:prevenir¦3istam:investir,revestir¦2údem:saudar¦2quem:coçar,roçar,laçar¦3nham:ater¦5idam:progredir¦3quem:calçar,forçar,atiçar¦3em:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4uem:alegar¦3íliem:mobiliar¦3intam:assentir¦7jam:entrever¦2enham:avir¦4iam:reler¦1usquem:moscar¦4intam:ressentir¦7am:dissentir¦1am:rer¦9am:retrogredir¦8am:correferir¦2ictam:flectir¦4em:poitar¦1onham:pôr¦2gam:dizer¦1jam:agir¦1igam:seguir¦1iram:ferir,gerir¦4çam:impedir¦7em:averiguar¦1urtam:sortir¦5em:minguar¦1coitem:açoitar"
    }
  },
  "gerunds": {
    "gerunds": {
      "fwd": "",
      "both": "3cando:braçar¦ndo:r",
      "rev": "",
      "ex": "1ondo:pôr¦2cando:coçar"
    }
  },
  "pastParticiple": {
    "pastParticiple": {
      "fwd": "ido:er¦osto:ôr¦1to:izer¦2do:tir,mir,dir,bir,gir,zir¦3do:rrir,erir",
      "both": "5do,entregue:tregar¦5ndo:tervir¦4do:utrir,eguir¦4do,inserto:serir¦4ído:minuir¦4ndo:rovir¦4do,impresso:rimir¦3do:orir,arir,irir,ssir,prir¦3ndo:dvir,nvir¦3ido,eleito:leger¦3cado:braçar¦3do,salvo:lvar¦2ído:buir,tuir,luir,ruir,suir¦2do:pir,nir,lir¦2ito:crever¦1ido,roto:per¦1eito:fazer¦1ído:air,oer¦1sto:or¦1erto:brir¦1do:ar",
      "rev": "r:ndo,do ou ganho,do, pago,do,aceito,do ou gasto,do,solto,do,extinto¦er:ido,morto,isto,ido,preso,ido,aceso¦1er:vido,cido,xido,hido¦1r:ado,morto,ado,expresso¦2er:omido,azido,ndido,abido,ebido,rdido,egido,frido,rrido,btido,emido,mbido¦2zer:dito¦3r:rtido,rmido,uvido,idido,stido,ugido,ngido,umido,itido,utido,rgido,uzido,agido,udido¦3er:uerido,ontido,retido,metido,bstido,batido¦4r:entido,rigido,ferido,ervido,petido,gerido,letido,pedido,xigido,nguido,lodido,andido¦5r:rantido,fundido,gredido¦5er:nvertido",
      "ex": "1do:ir¦1eito:fazer¦2ndo:vir¦1isto:ver¦2do:rir¦4do:ouvir,pedir,subir,medir,ferir,latir¦5do ou ganho:ganhar¦4ido,morto:morrer¦4do, pago:pagar¦4isto:prever¦5do:servir,sorrir,aderir¦3isto:rever¦6do,aceito:aceitar¦4do,morto:matar¦5ido,preso:prender¦5ido,aceso:acender¦8do,expresso:expressar¦9do:distinguir,prescindir¦5do ou gasto:gastar¦5do,solto:soltar¦8do,extinto:extinguir¦2cado:coçar¦1ido:ser,ter,ler¦3ido:poder,valer,bater,deter,ceder,feder,reter,meter,viger¦1osto:pôr¦2to:dizer¦3do:agir¦4ido:manter,erguer¦2ido:crer,ater¦6do:invadir,proibir"
    }
  }
}