// generated in ./lib/models
export default {
  "nouns": {
    "plurals": {
      "fwd": "2:is,us¦3:res¦ns:m¦eses:és¦omens:ômen¦1s:i,e,u¦1is:al",
      "both": "1:x¦3:las¦5s:istão¦5es:rguer¦4es:eptil,ssor,lemão¦4s:imen,oupa,orco,adão,rfão,miga,rmão¦3s:mao,uva,nho,çaí,rão,rto,efil,gão,ecil,rna¦3ues:ues¦3es:sul,tor,atão,itão,her,fen,lor¦3eis:éptil¦2s:ta,ia,no,ço,ha,po,do,so,go,vo,nil,lo,ro,ril,sa¦2ões:otão,azão¦2is:ool,iel,vel,zul,aul¦2eis:xtil,átil¦2es:ar,ís¦1oes:cao¦1s-homens:il-homem¦1s:é,ã¦1éis:tel,uel,nel¦1ões:ção,são,ião,eão¦1es:z¦s-feiras:-feira¦eniores:ênior¦ateres:áter¦eses:ês¦óis:ol",
      "rev": "1:os¦2:ases,aus,éus,tes,xis¦3:pis,bus,bores,nus,amas¦4:uenes,ires,írus,haves¦el:éis¦únior:uniores¦ão:ões¦ólen:olens¦1m:ons,ins¦1il:seis,teis¦1o:ães,aes¦1és:veses¦1l:ies¦1ômen:domens¦2l:sais,mais,rais,vais,nais¦2m:buns,dens,gens¦3m:uvens,ovens¦3l:uzis¦4l:pitais",
      "ex": "4:cais¦3s:mão,pai,boi,rei¦2es:cão,pão,pao,cao¦4eis:fóssil,míssil,fértil¦3es:gas,cor¦3éis:papel¦5s:sótão¦4s:fuzil,cama¦1uniores:júnior¦4es:amor¦5es:sabor,fossil¦3ões:limão¦1olens:pólen¦4ns:homem¦2ns:bem¦3ns:trem¦2is:sal"
    }
  },
  "adjectives": {
    "f": {
      "fwd": "1:os,a",
      "both": "1:ão,ó,z,e¦2:em,el,il¦3:aso,zul¦4a:nhol¦éia:eu¦esa:ês¦á:au¦a:o",
      "rev": "4:anja¦1m:oa¦2s:co¦3s:ito",
      "ex": "2a:bom"
    },
    "mp": {
      "fwd": "s:¦eis:il",
      "both": "1:ó¦3:nja¦2es:mão¦2is:vel¦2a:itos¦1óis:hol¦1es:z¦1is:ul¦1a:cos¦eses:ês¦ns:m",
      "rev": "1:os,us¦2:ves,des,tes¦3:bres,oces¦4:remes¦1il:ceis¦1o:sa",
      "ex": "3a:raso"
    },
    "fp": {
      "fwd": "2:os¦eis:il¦1is:el",
      "both": "3:nja¦4ias:ropeu¦3s:aso¦2as:ol¦2es:iz¦1s:ão,e¦1ns:em¦1as:om¦1is:ul¦esas:ês¦ás:au¦as:o",
      "rev": "1:ó¦3:cos¦4:itos¦1il:ceis¦2l:veis",
      "ex": "2:só"
    }
  },
  "conditional": {
    "first": {
      "fwd": "ia:¦oria:ôr¦coitaria:çoitar¦1ria:izer¦2ria:fazer¦2caria:inçar",
      "both": "4ria:sprazer¦3caria:troçar,braçar",
      "rev": "2:eria,iria,oria¦3:maria,daria,laria,taria,garia,çaria,oaria,haria,varia,saria,jaria,paria,baria,zaria,naria,iaria,earia,uaria,xaria¦4:ncaria,traria,araria,oraria,uraria,iraria,icaria,ucaria,nraria,graria,braria,eraria,rraria,draria,rcaria,ecaria,scaria,fraria,lcaria,ufaria,craria,lraria,vraria,ofaria,ifaria,afaria,lfaria¦5:mpraria,locaria,vocaria,opraria,tacaria,hocaria,focaria,lacaria,upraria,pocaria,bocaria,pacaria,hacaria,arfaria,tocaria¦2çar:mocaria¦3zer:sfaria,sdiria,ldiria,-faria¦4zer:radiria,endiria,mefaria,safaria,erdiria¦4çar:trincaria¦5zer:trafaria,rrefaria",
      "ex": "2ria:fazer,dizer¦3ria:trazer,afazer¦2caria:coçar,roçar,laçar¦3caria:calçar,forçar,atiçar¦4caria:remoçar¦2ia:ir¦3ia:dar¦1oria:pôr¦5ia:tocar,focar,tacar,sacar,locar,socar,arfar¦4ria:refazer,redizer¦6ia:trocar,brocar,blefar,surfar¦4ia:orar,irar,arar,erar¦5ria:condizer,perfazer,predizer¦10ia:reciprocar,embasbacar¦8ia:triunfar,derrocar,atarefar¦7ia:atracar,xerocar,ensacar,assacar¦1coitaria:açoitar¦7ria:putrefazer,liquefazer¦6ria:rarefazer¦9ia:atarracar,esburacar"
    },
    "second": {
      "fwd": "ias:¦orias:ôr¦coitarias:çoitar¦1rias:izer¦2rias:fazer¦2carias:inçar",
      "both": "4rias:sprazer¦3carias:troçar,braçar",
      "rev": "2:erias,irias,orias¦3:marias,darias,larias,tarias,garias,çarias,oarias,harias,varias,sarias,jarias,parias,barias,zarias,narias,iarias,earias,uarias,xarias¦4:ncarias,trarias,ararias,orarias,urarias,irarias,icarias,ucarias,nrarias,grarias,brarias,erarias,rrarias,drarias,rcarias,ecarias,scarias,frarias,lcarias,ufarias,crarias,lrarias,vrarias,ofarias,ifarias,afarias,lfarias¦5:mprarias,locarias,vocarias,oprarias,tacarias,hocarias,focarias,lacarias,uprarias,pocarias,bocarias,pacarias,hacarias,arfarias,tocarias¦2çar:mocarias¦3zer:sfarias,sdirias,ldirias,-farias¦4zer:radirias,endirias,mefarias,safarias,erdirias¦4çar:trincarias¦5zer:trafarias,rrefarias",
      "ex": "2rias:fazer,dizer¦3rias:trazer,afazer¦2carias:coçar,roçar,laçar¦3carias:calçar,forçar,atiçar¦4carias:remoçar¦2ias:ir¦3ias:dar¦1orias:pôr¦5ias:tocar,focar,tacar,sacar,locar,socar,arfar¦4rias:refazer,redizer¦6ias:trocar,brocar,blefar,surfar¦4ias:orar,irar,arar,erar¦5rias:condizer,perfazer,predizer¦10ias:reciprocar,embasbacar¦8ias:triunfar,derrocar,atarefar¦7ias:atracar,xerocar,ensacar,assacar¦1coitarias:açoitar¦7rias:putrefazer,liquefazer¦6rias:rarefazer¦9ias:atarracar,esburacar"
    },
    "third": {
      "fwd": "ia:¦oria:ôr¦coitaria:çoitar¦1ria:izer¦2ria:fazer¦2caria:inçar",
      "both": "4ria:sprazer¦3caria:troçar,braçar",
      "rev": "2:eria,iria,oria¦3:maria,daria,laria,taria,garia,çaria,oaria,haria,varia,saria,jaria,paria,baria,zaria,naria,iaria,earia,uaria,xaria¦4:ncaria,traria,araria,oraria,uraria,iraria,icaria,ucaria,nraria,graria,braria,eraria,rraria,draria,rcaria,ecaria,scaria,fraria,lcaria,ufaria,craria,lraria,vraria,ofaria,ifaria,afaria,lfaria¦5:mpraria,locaria,vocaria,opraria,tacaria,hocaria,focaria,lacaria,upraria,pocaria,bocaria,pacaria,hacaria,arfaria,tocaria¦2çar:mocaria¦3zer:sfaria,sdiria,ldiria,-faria¦4zer:radiria,endiria,mefaria,safaria,erdiria¦4çar:trincaria¦5zer:trafaria,rrefaria",
      "ex": "2ria:fazer,dizer¦3ria:trazer,afazer¦2caria:coçar,roçar,laçar¦3caria:calçar,forçar,atiçar¦4caria:remoçar¦2ia:ir¦3ia:dar¦1oria:pôr¦5ia:tocar,focar,tacar,sacar,locar,socar,arfar¦4ria:refazer,redizer¦6ia:trocar,brocar,blefar,surfar¦4ia:orar,irar,arar,erar¦5ria:condizer,perfazer,predizer¦10ia:reciprocar,embasbacar¦8ia:triunfar,derrocar,atarefar¦7ia:atracar,xerocar,ensacar,assacar¦1coitaria:açoitar¦7ria:putrefazer,liquefazer¦6ria:rarefazer¦9ia:atarracar,esburacar"
    },
    "firstPlural": {
      "fwd": "íamos:¦oríamos:ôr¦coitaríamos:çoitar¦1ríamos:izer¦2ríamos:fazer¦2caríamos:inçar",
      "both": "4ríamos:sprazer¦3caríamos:troçar,braçar",
      "rev": "2:eríamos,iríamos,oríamos¦3:maríamos,daríamos,laríamos,taríamos,garíamos,çaríamos,oaríamos,haríamos,varíamos,saríamos,jaríamos,paríamos,baríamos,zaríamos,naríamos,iaríamos,earíamos,uaríamos,xaríamos¦4:ncaríamos,traríamos,araríamos,oraríamos,uraríamos,iraríamos,icaríamos,ucaríamos,nraríamos,graríamos,braríamos,eraríamos,rraríamos,draríamos,rcaríamos,ecaríamos,scaríamos,fraríamos,lcaríamos,ufaríamos,craríamos,lraríamos,vraríamos,ofaríamos,ifaríamos,afaríamos,lfaríamos¦5:mpraríamos,locaríamos,vocaríamos,opraríamos,tacaríamos,hocaríamos,focaríamos,lacaríamos,upraríamos,pocaríamos,bocaríamos,pacaríamos,hacaríamos,arfaríamos,tocaríamos¦2çar:mocaríamos¦3zer:sfaríamos,sdiríamos,ldiríamos,-faríamos¦4zer:radiríamos,endiríamos,mefaríamos,safaríamos,erdiríamos¦4çar:trincaríamos¦5zer:trafaríamos,rrefaríamos",
      "ex": "2ríamos:fazer,dizer¦3ríamos:trazer,afazer¦2caríamos:coçar,roçar,laçar¦3caríamos:calçar,forçar,atiçar¦4caríamos:remoçar¦2íamos:ir¦3íamos:dar¦1oríamos:pôr¦5íamos:tocar,focar,tacar,sacar,locar,socar,arfar¦4ríamos:refazer,redizer¦6íamos:trocar,brocar,blefar,surfar¦4íamos:orar,irar,arar,erar¦5ríamos:condizer,perfazer,predizer¦10íamos:reciprocar,embasbacar¦8íamos:triunfar,derrocar,atarefar¦7íamos:atracar,xerocar,ensacar,assacar¦1coitaríamos:açoitar¦7ríamos:putrefazer,liquefazer¦6ríamos:rarefazer¦9íamos:atarracar,esburacar"
    },
    "secondPlural": {
      "fwd": "íeis:¦oríeis:ôr¦coitaríeis:çoitar¦1ríeis:izer¦2ríeis:fazer¦2caríeis:inçar",
      "both": "4ríeis:sprazer¦3caríeis:troçar,braçar",
      "rev": "2:eríeis,iríeis,oríeis¦3:maríeis,daríeis,laríeis,taríeis,garíeis,çaríeis,oaríeis,haríeis,varíeis,saríeis,jaríeis,paríeis,baríeis,zaríeis,naríeis,iaríeis,earíeis,uaríeis,xaríeis¦4:ncaríeis,traríeis,araríeis,oraríeis,uraríeis,iraríeis,icaríeis,ucaríeis,nraríeis,graríeis,braríeis,eraríeis,rraríeis,draríeis,rcaríeis,ecaríeis,scaríeis,fraríeis,lcaríeis,ufaríeis,craríeis,lraríeis,vraríeis,ofaríeis,ifaríeis,afaríeis,lfaríeis¦5:mpraríeis,locaríeis,vocaríeis,opraríeis,tacaríeis,hocaríeis,focaríeis,lacaríeis,upraríeis,pocaríeis,bocaríeis,pacaríeis,hacaríeis,arfaríeis,tocaríeis¦2çar:mocaríeis¦3zer:sfaríeis,sdiríeis,ldiríeis,-faríeis¦4zer:radiríeis,endiríeis,mefaríeis,safaríeis,erdiríeis¦4çar:trincaríeis¦5zer:trafaríeis,rrefaríeis",
      "ex": "2ríeis:fazer,dizer¦3ríeis:trazer,afazer¦2caríeis:coçar,roçar,laçar¦3caríeis:calçar,forçar,atiçar¦4caríeis:remoçar¦2íeis:ir¦3íeis:dar¦1oríeis:pôr¦5íeis:tocar,focar,tacar,sacar,locar,socar,arfar¦4ríeis:refazer,redizer¦6íeis:trocar,brocar,blefar,surfar¦4íeis:orar,irar,arar,erar¦5ríeis:condizer,perfazer,predizer¦10íeis:reciprocar,embasbacar¦8íeis:triunfar,derrocar,atarefar¦7íeis:atracar,xerocar,ensacar,assacar¦1coitaríeis:açoitar¦7ríeis:putrefazer,liquefazer¦6ríeis:rarefazer¦9íeis:atarracar,esburacar"
    },
    "thirdPlural": {
      "fwd": "iam:¦oriam:ôr¦coitariam:çoitar¦1riam:izer¦2riam:fazer¦2cariam:inçar",
      "both": "4riam:sprazer¦3cariam:troçar,braçar",
      "rev": "2:eriam,iriam,oriam¦3:mariam,dariam,lariam,tariam,gariam,çariam,oariam,hariam,variam,sariam,jariam,pariam,bariam,zariam,nariam,iariam,eariam,uariam,xariam¦4:ncariam,trariam,arariam,orariam,urariam,irariam,icariam,ucariam,nrariam,grariam,brariam,erariam,rrariam,drariam,rcariam,ecariam,scariam,frariam,lcariam,ufariam,crariam,lrariam,vrariam,ofariam,ifariam,afariam,lfariam¦5:mprariam,locariam,vocariam,oprariam,tacariam,hocariam,focariam,lacariam,uprariam,pocariam,bocariam,pacariam,hacariam,arfariam,tocariam¦2çar:mocariam¦3zer:sfariam,sdiriam,ldiriam,-fariam¦4zer:radiriam,endiriam,mefariam,safariam,erdiriam¦4çar:trincariam¦5zer:trafariam,rrefariam",
      "ex": "2riam:fazer,dizer¦3riam:trazer,afazer¦2cariam:coçar,roçar,laçar¦3cariam:calçar,forçar,atiçar¦4cariam:remoçar¦2iam:ir¦3iam:dar¦1oriam:pôr¦5iam:tocar,focar,tacar,sacar,locar,socar,arfar¦4riam:refazer,redizer¦6iam:trocar,brocar,blefar,surfar¦4iam:orar,irar,arar,erar¦5riam:condizer,perfazer,predizer¦10iam:reciprocar,embasbacar¦8iam:triunfar,derrocar,atarefar¦7iam:atracar,xerocar,ensacar,assacar¦1coitariam:açoitar¦7riam:putrefazer,liquefazer¦6riam:rarefazer¦9iam:atarracar,esburacar"
    }
  },
  "futureTense": {
    "first": {
      "fwd": "ei:¦orei:ôr¦1rei:izer¦2rei:fazer¦2carei:tiçar",
      "both": "4á:doer¦3carei:braçar¦coitarei:çoitar",
      "rev": "2:erei,irei,orei¦3:marei,darei,larei,garei,çarei,rarei,oarei,harei,sarei,jarei,parei,barei,zarei,narei,iarei,uarei,varei,earei,xarei¦4:starei,ntarei,ncarei,ltarei,scarei,rcarei,atarei,ocarei,ucarei,icarei,ptarei,etarei,otarei,rtarei,ctarei,utarei,ecarei,afarei,nfarei,ufarei,xtarei,ofarei¦5:eitarei,ditarei,vitarei,sitarei,tacarei,litarei,ritarei,mitarei,citarei,pitarei,lacarei,gitarei¦:á¦2çar:alcarei¦3zer:sfarei,efarei,sdirei,ldirei¦4zer:radirei,erfarei,endirei",
      "ex": "2rei:fazer,dizer¦3rei:trazer,afazer¦4á:doer¦7á:aprazer,grassar¦2carei:coçar,roçar,laçar¦6á:prazer¦3carei:calçar,forçar,atiçar¦9á:concernir¦5á:urgir¦2ei:ir¦3ei:dar¦1orei:pôr¦5rei:condizer,predizer¦5ei:citar,tacar,fitar,sacar,ditar,arfar¦7ei:habitar,atracar¦4ei:atar¦6ei:quitar,grifar¦8ei:inculcar"
    },
    "second": {
      "fwd": "ás:¦orás:ôr¦1rás:izer¦2rás:fazer¦2carás:tiçar",
      "both": "4ão:doer¦3carás:braçar¦coitarás:çoitar",
      "rev": "2:erás,irás,orás¦3:marás,darás,larás,garás,çarás,rarás,oarás,harás,sarás,jarás,parás,barás,zarás,narás,iarás,uarás,varás,earás,xarás¦4:starás,ntarás,ncarás,ltarás,scarás,rcarás,atarás,ocarás,ucarás,icarás,ptarás,etarás,otarás,rtarás,ctarás,utarás,ecarás,afarás,nfarás,ufarás,xtarás,ofarás¦5:eitarás,ditarás,vitarás,sitarás,tacarás,litarás,ritarás,mitarás,citarás,pitarás,lacarás,gitarás¦:ão¦2çar:alcarás¦3zer:sfarás,efarás,sdirás,ldirás¦4zer:radirás,erfarás,endirás",
      "ex": "2rás:fazer,dizer¦3rás:trazer,afazer¦4ão:doer¦7ão:aprazer,grassar¦2carás:coçar,roçar,laçar¦6ão:prazer¦3carás:calçar,forçar,atiçar¦9ão:concernir¦5ão:urgir¦2ás:ir¦3ás:dar¦1orás:pôr¦5rás:condizer,predizer¦5ás:citar,tacar,fitar,sacar,ditar,arfar¦7ás:habitar,atracar¦4ás:atar¦6ás:quitar,grifar¦8ás:inculcar"
    },
    "third": {
      "fwd": "á:¦orá:ôr¦1rá:izer¦2rá:fazer¦2cará:tiçar",
      "both": "3cará:braçar¦coitará:çoitar",
      "rev": "2:erá,irá,orá¦3:mará,dará,lará,gará,çará,rará,oará,hará,sará,jará,pará,bará,zará,nará,iará,uará,vará,eará,xará¦4:stará,ntará,ncará,ltará,scará,rcará,atará,ocará,ucará,icará,ptará,etará,otará,rtará,ctará,utará,ecará,afará,nfará,ufará,xtará,ofará¦5:eitará,ditará,vitará,sitará,tacará,litará,ritará,mitará,citará,pitará,lacará,gitará¦2çar:alcará¦3zer:sfará,efará,sdirá,ldirá¦4zer:radirá,erfará,endirá",
      "ex": "2rá:fazer,dizer¦3rá:trazer,afazer¦2cará:coçar,roçar,laçar¦3cará:calçar,forçar,atiçar¦2á:ir¦3á:dar¦1orá:pôr¦5rá:condizer,predizer¦5á:citar,tacar,fitar,sacar,ditar,arfar¦7á:habitar,atracar¦4á:atar¦6á:quitar,grifar¦8á:inculcar"
    },
    "firstPlural": {
      "fwd": "emos:¦oremos:ôr¦1remos:izer¦2remos:fazer¦2caremos:tiçar",
      "both": "3caremos:braçar¦coitaremos:çoitar",
      "rev": "2:eremos,iremos,oremos¦3:maremos,daremos,laremos,garemos,çaremos,raremos,oaremos,haremos,saremos,jaremos,paremos,baremos,zaremos,naremos,iaremos,uaremos,varemos,earemos,xaremos¦4:staremos,ntaremos,ncaremos,ltaremos,scaremos,rcaremos,ataremos,ocaremos,ucaremos,icaremos,ptaremos,etaremos,otaremos,rtaremos,ctaremos,utaremos,ecaremos,afaremos,nfaremos,ufaremos,xtaremos,ofaremos¦5:eitaremos,ditaremos,vitaremos,sitaremos,tacaremos,litaremos,ritaremos,mitaremos,citaremos,pitaremos,lacaremos,gitaremos¦2çar:alcaremos¦3zer:sfaremos,efaremos,sdiremos,ldiremos¦4zer:radiremos,erfaremos,endiremos",
      "ex": "2remos:fazer,dizer¦3remos:trazer,afazer¦2caremos:coçar,roçar,laçar¦3caremos:calçar,forçar,atiçar¦2emos:ir¦3emos:dar¦1oremos:pôr¦5remos:condizer,predizer¦5emos:citar,tacar,fitar,sacar,ditar,arfar¦7emos:habitar,atracar¦4emos:atar¦6emos:quitar,grifar¦8emos:inculcar"
    },
    "secondPlural": {
      "fwd": "eis:¦oreis:ôr¦1reis:izer¦2reis:fazer¦2careis:tiçar",
      "both": "3careis:braçar¦coitareis:çoitar",
      "rev": "2:ereis,ireis,oreis¦3:mareis,dareis,lareis,gareis,çareis,rareis,oareis,hareis,sareis,jareis,pareis,bareis,zareis,nareis,iareis,uareis,vareis,eareis,xareis¦4:stareis,ntareis,ncareis,ltareis,scareis,rcareis,atareis,ocareis,ucareis,icareis,ptareis,etareis,otareis,rtareis,ctareis,utareis,ecareis,afareis,nfareis,ufareis,xtareis,ofareis¦5:eitareis,ditareis,vitareis,sitareis,tacareis,litareis,ritareis,mitareis,citareis,pitareis,lacareis,gitareis¦2çar:alcareis¦3zer:sfareis,efareis,sdireis,ldireis¦4zer:radireis,erfareis,endireis",
      "ex": "2reis:fazer,dizer¦3reis:trazer,afazer¦2careis:coçar,roçar,laçar¦3careis:calçar,forçar,atiçar¦2eis:ir¦3eis:dar¦1oreis:pôr¦5reis:condizer,predizer¦5eis:citar,tacar,fitar,sacar,ditar,arfar¦7eis:habitar,atracar¦4eis:atar¦6eis:quitar,grifar¦8eis:inculcar"
    },
    "thirdPlural": {
      "fwd": "ão:¦orão:ôr¦1rão:izer¦2rão:fazer¦2carão:tiçar",
      "both": "3carão:braçar¦coitarão:çoitar",
      "rev": "2:erão,irão,orão¦3:marão,darão,larão,garão,çarão,rarão,oarão,harão,sarão,jarão,parão,barão,zarão,narão,iarão,uarão,varão,earão,xarão¦4:starão,ntarão,ncarão,ltarão,scarão,rcarão,atarão,ocarão,ucarão,icarão,ptarão,etarão,otarão,rtarão,ctarão,utarão,ecarão,afarão,nfarão,ufarão,xtarão,ofarão¦5:eitarão,ditarão,vitarão,sitarão,tacarão,litarão,ritarão,mitarão,citarão,pitarão,lacarão,gitarão¦2çar:alcarão¦3zer:sfarão,efarão,sdirão,ldirão¦4zer:radirão,erfarão,endirão",
      "ex": "2rão:fazer,dizer¦3rão:trazer,afazer¦2carão:coçar,roçar,laçar¦3carão:calçar,forçar,atiçar¦2ão:ir¦3ão:dar¦1orão:pôr¦5rão:condizer,predizer¦5ão:citar,tacar,fitar,sacar,ditar,arfar¦7ão:habitar,atracar¦4ão:atar¦6ão:quitar,grifar¦8ão:inculcar"
    }
  },
  "imperativeNeg": {
    "first": {
      "fwd": "onhas:ôr¦jas:gir,ger¦igas:eguir¦iras:erir¦as:uer¦ças:cir¦urtas:ortir¦coites:çoitar¦1jas:aver¦1as:mer,rer,ber,her,per,ser,hir¦1gas:izer¦1es:iar¦2as:ndir,rter,mbir,ulir,idir,irir,rdir¦2eies:nsiar¦2ças:pedir,medir¦2ques:inçar¦3es:iguar,nquar¦3as:arrir¦4es:inguar,coitar",
      "both": "5as:ementir,flectir,mprazer¦5jas:terver¦5ejas:brestar¦5nhas:treter¦4ues:umegar,amegar,elegar¦4es:foitar,noitar¦4as:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4intas:ressentir¦4jas:tever¦4eies:cendiar¦4iras:equerer¦4enhas:tervir¦3as:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3ues:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3es:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3ques:emoçar,troçar,braçar¦3idas:egredir,sgredir¦3ias:crer¦3eies:mediar¦3nhas:ster,bter,nter¦3enhas:rovir¦2as:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2es:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úles:baular¦2enhas:avir,evir,nvir¦2ízes:juizar¦2intas:smentir,nsentir¦2ues:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilas:mpelir,xpelir¦2ínes:ruinar¦2ita:mpetir¦2has:aler¦2cas:erder¦1údes:iudar¦1irvas:servir¦1ças:uvir,azer¦1ízes:aizar,eizar¦1úces:iuçar¦1ísques:aiscar¦1águas:saguar¦1es:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjas:vergir¦1águes:xaguar¦1iras:arir¦1íbas:oibir¦1as:oer,nir,xer¦1ulas:golir¦1únas:eunir¦1itas:letir¦1ies:ear¦1nhas:or¦1ibas:aber¦1ssas:oder¦ólegues:olegar¦irzas:erzir¦ínquas:inquir¦igras:egrir¦ispas:espir¦ubras:obrir¦éques:equar¦irtas:ertir¦ussas:ossir¦ças:cer¦ces:çar¦ques:car¦urmas:ormir",
      "rev": "ar:ês¦entir:intas¦ervir:irvas¦udar:údes¦iliar:ílies¦ectir:ictas¦1rer:eiras¦1zer:agas¦1r:eias¦1gir:ijas,ujas,ljas¦1eguir:sigas¦1erir:firas,diras,giras,siras,tiras¦1etir:pitas¦1edir:ridas¦1enir:vinas¦1estir:vistas¦1ar:tes¦1ir:venhas¦2ar:stejas,vies,pies,oies,fies,cies,ries,gies,dies,aies,ties,bies,sies,zies,nies,uies,mies,xies¦2er:omas,rras,ebas,chas,fras,etas,emas,osas,mpas¦2gir:injas,urjas,eajas,erjas,oajas,unjas,arjas¦2r:vejas,tenhas¦2ger:lejas,anjas,rejas,onjas¦2zer:digas¦2cir:arças¦2uer:rgas¦3ir:vidas,cidas,undas,uspas,andas,indas,sidas,lidas,uiras,unhas,bulas,redas,urzas,feras,ardas¦3ger:otejas¦3er:olhas,ambas,ervas,ertas,ueras,relas,essas¦3ar:ilies,plies,alies,olies¦3dir:xpeças¦4dir:espeças,impeças,esmeças¦4gir:terajas¦4ar:zigues,relies¦4ir:cumbas,apulas,sentas,lanhas¦4çar:trinques¦4ger:sterjas¦5ar:pinques,ginques,anigues",
      "ex": "vás:ir¦águes:aguar¦2jas:ser,ver,haver,reger,viger¦1enhas:vir¦3ejas:estar¦2nhas:ter¦1ês:dar¦3iras:querer¦3gas:trazer¦2as:rir¦2ias:ler¦1intas:sentir,mentir¦2ças:pedir,medir¦3as:abrir,dever,meter,jazer,arder,bulir,urdir¦3ias:crer¦3ues:pegar,negar,regar,cegar,legar,segar¦5jas:prover,prever¦1istas:vestir¦1irvas:servir¦4jas:rever¦2eies:odiar¦4nhas:deter,reter¦3itas:repetir¦1ulas:polir¦4as:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2es:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idas:agredir¦3eies:mediar,ansiar¦4inas:prevenir¦3enhas:advir¦3istas:investir,revestir¦2údes:saudar¦2ques:coçar,roçar,laçar¦3nhas:ater¦5idas:progredir¦3ques:calçar,forçar,atiçar¦3es:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4ues:alegar¦3ílies:mobiliar¦3intas:assentir¦7jas:entrever¦2enhas:avir¦4ias:reler¦4intas:ressentir¦7as:dissentir¦1as:rer¦9as:retrogredir¦8as:correferir¦2ictas:flectir¦4es:poitar¦1onhas:pôr¦2gas:dizer¦1jas:agir¦1igas:seguir¦1iras:ferir,gerir¦4ças:impedir¦7es:averiguar¦1urtas:sortir¦5es:minguar¦1coites:açoitar"
    },
    "second": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦a:uer¦urta:ortir¦coite:çoitar¦1ja:aver¦1a:mer,rer,ber,her,per,ser,hir¦1ga:izer¦1e:iar¦2a:ndir,rter,mbir,ulir,idir,irir,rdir¦2eie:nsiar¦2ça:pedir,medir¦2que:inçar¦3e:iguar,nquar¦3a:arrir¦4e:inguar,coitar",
      "both": "5a:ementir,flectir,mprazer¦5ja:terver¦5eja:brestar¦5nha:treter¦4ue:umegar,amegar,elegar¦4e:foitar,noitar¦4a:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4inta:ressentir¦4ja:tever¦4eie:cendiar¦4ira:equerer¦4enha:tervir¦3a:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3ue:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3e:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3que:emoçar,troçar,braçar¦3ida:egredir,sgredir¦3ia:crer¦3eie:mediar¦3nha:ster,bter,nter¦3enha:rovir¦2a:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2e:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úle:baular¦2enha:avir,evir,nvir¦2íze:juizar¦2inta:smentir,nsentir¦2ue:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ila:mpelir,xpelir¦2íne:ruinar¦2itas:mpetir¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1ça:uvir,azer¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1água:saguar¦1e:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irja:vergir¦1águe:xaguar¦1ira:arir¦1íba:oibir¦1a:oer,nir,xer¦1ula:golir¦1úna:eunir¦1ita:letir¦1ie:ear¦1nha:or¦1iba:aber¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦ças:cir¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦udar:úde¦iliar:ílie¦ectir:icta¦1rer:eira¦1zer:aga¦1r:eia¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita¦1edir:rida¦1enir:vina¦1estir:vista¦1ar:te¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,osa,mpa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2uer:rga¦3ir:vida,cida,unda,uspa,anda,inda,sida,lida,uira,unha,bula,reda,urza,fera,arda¦3ger:oteja¦3er:olha,amba,erva,erta,uera,rela,essa¦3ar:ilie,plie,alie,olie¦3dir:xpeça¦4dir:espeça,impeça,esmeça¦4gir:teraja¦4ar:zigue,relie¦4ir:cumba,apula,senta,lanha¦4çar:trinque¦4ger:sterja¦5ar:pinque,ginque,anigue",
      "ex": "vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir¦2ia:ler¦1inta:sentir,mentir¦2ça:pedir,medir¦3a:abrir,dever,meter,jazer,arder,bulir,urdir¦3ia:crer¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦3ita:repetir¦1ula:polir¦4a:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3ida:agredir¦3eie:mediar,ansiar¦4ina:prevenir¦3enha:advir¦3ista:investir,revestir¦2úde:saudar¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4ue:alegar¦3ílie:mobiliar¦3inta:assentir¦7ja:entrever¦2enha:avir¦4ia:reler¦4inta:ressentir¦7a:dissentir¦1a:rer¦9a:retrogredir¦8a:correferir¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦5e:minguar¦1coite:açoitar"
    },
    "third": {
      "fwd": "onhamos:ôr¦jamos:gir,ger¦igamos:eguir¦iramos:erir¦amos:uer¦çamos:cir¦urtamos:ortir¦coitemos:çoitar¦1amos:mer,rer,ber,bir,her,per,ser,hir¦1gamos:izer¦2amos:idir,ndir,rter,nzer,ulir,irir,rdir¦2çamos:pedir,medir¦2quemos:inçar¦3amos:urtir,arrir",
      "both": "5amos:ementir,flectir,mprazer¦5ejamos:brestar¦5mos:saguar¦5nhamos:treter¦4amos:morder,opelir,xceler,inquir,rreter,orrir¦4nhamos:uster,bster¦4jamos:tever¦4iramos:equerer¦4enhamos:tervir¦3amos:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3quemos:emoçar,troçar¦3intamos:essentir¦3idamos:egredir,sgredir¦3iamos:crer¦3inamos:revenir¦3enhamos:rovir¦3nhamos:nter¦2amos:lpir,orir,urir,alir,odir,ater,plir,upir,imir,eder,trir,udir,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,itir,umir,prir,stir,nder,air¦2intamos:smentir,nsentir¦2istamos:evestir¦2ilamos:mpelir,xpelir¦2enhamos:avir,evir,nvir¦2ita:mpetir¦2hamos:aler¦2camos:erder¦1irvamos:servir¦1irjamos:vergir¦1iramos:arir¦1amos:oer,nir,xer,ver¦1ulamos:golir¦1itamos:letir¦1nhamos:or¦1uemos:gar¦1çamos:uvir,azer¦1ssamos:oder¦irzamos:erzir¦igramos:egrir¦ispamos:espir¦ubramos:obrir¦irtamos:ertir¦ussamos:ossir¦çamos:cer¦cemos:çar¦quemos:car¦urmamos:ormir¦emos:ar",
      "rev": "entir:intamos¦ervir:irvamos¦ectir:ictamos¦1rer:eiramos¦1zer:agamos¦1r:eiamos¦1ber:aibamos¦1gir:ijamos,ujamos,ljamos¦1eguir:sigamos¦1erir:firamos,diramos,giramos,siramos,tiramos¦1etir:pitamos¦1edir:ridamos¦1ir:venhamos¦1estir:vistamos¦2ar:stejamos¦2er:omamos,rramos,ebamos,framos,emamos,chamos,azamos,mpamos,osamos¦2gir:injamos,urjamos,eajamos,erjamos,oajamos,unjamos,arjamos¦2r:vejamos,tenhamos¦2ger:lejamos,anjamos,rejamos¦2zer:digamos¦2cir:arçamos¦2uer:rgamos¦3ir:vidamos,cidamos,undamos,oibamos,andamos,umbamos,indamos,pulamos,sidamos,entamos,uiramos,redamos,nibamos,urdamos,anhamos¦3ger:otejamos¦3er:olhamos,ordamos,ambamos,ertamos,enzamos,ueramos,relamos¦3çar:braquemos¦3dir:xpeçamos,smeçamos¦4dir:espeçamos,impeçamos¦4gir:terajamos¦4iar:obilemos¦4ir:olidamos,runhamos,cardamos,eferamos¦4çar:trinquemos¦5er:bressamos",
      "ex": "vamos:ir¦2jamos:ser,ver,haver,reger,viger¦1enhamos:vir¦3ejamos:estar¦2nhamos:ter¦3iramos:querer¦3gamos:trazer¦2amos:rir¦2iamos:ler¦2ibamos:saber,caber¦1intamos:sentir,mentir¦2çamos:pedir,medir¦3amos:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iamos:crer¦5jamos:prover,prever¦1istamos:vestir¦1irvamos:servir¦4jamos:rever¦4nhamos:deter,reter,obter¦3itamos:repetir¦1ulamos:polir¦4quemos:abraçar¦4amos:morder,treler,curtir,exibir,ebulir,elidir,ilidir,condir,garrir¦3idamos:agredir¦3enhamos:advir¦3istamos:investir¦2quemos:coçar,roçar,laçar¦3nhamos:ater¦5idamos:progredir¦3quemos:calçar,forçar,atiçar¦5emos:mobiliar¦3intamos:assentir¦7jamos:entrever,interver¦2enhamos:avir¦4iamos:reler¦7amos:dissentir¦1amos:rer¦9amos:retrogredir¦8amos:correferir¦2ictamos:flectir¦1onhamos:pôr¦2gamos:dizer¦1jamos:agir¦1igamos:seguir¦1iramos:ferir,gerir¦4çamos:impedir¦1urtamos:sortir¦1coitemos:açoitar¦3jamos:monger¦6jamos:absterger"
    },
    "firstPlural": {
      "fwd": "onhais:ôr¦jais:gir,ger¦igais:eguir¦irais:erir¦ais:uer¦çais:cir¦urtais:ortir¦coiteis:çoitar¦1ais:mer,rer,ber,bir,her,per,ser,hir¦1gais:izer¦2ais:idir,ndir,rter,nzer,ulir,irir,rdir¦2çais:pedir,medir¦2queis:inçar¦3ais:urtir,arrir",
      "both": "5ais:ementir,flectir,mprazer¦5ejais:brestar¦5is:saguar¦5nhais:treter¦4ais:morder,opelir,xceler,inquir,rreter,orrir¦4nhais:uster,bster¦4jais:tever¦4irais:equerer¦4enhais:tervir¦3ais:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3queis:emoçar,troçar¦3intais:essentir¦3idais:egredir,sgredir¦3iais:crer¦3inais:revenir¦3enhais:rovir¦3nhais:nter¦2ais:lpir,orir,urir,alir,odir,ater,plir,upir,imir,eder,trir,udir,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,itir,umir,prir,stir,nder,air¦2intais:smentir,nsentir¦2istais:evestir¦2ilais:mpelir,xpelir¦2enhais:avir,evir,nvir¦2itamos:mpetir¦2hais:aler¦2cais:erder¦1irvais:servir¦1irjais:vergir¦1irais:arir¦1ais:oer,nir,xer,ver¦1ulais:golir¦1itais:letir¦1nhais:or¦1ueis:gar¦1çais:uvir,azer¦1ssais:oder¦irzais:erzir¦igrais:egrir¦ispais:espir¦ubrais:obrir¦irtais:ertir¦ussais:ossir¦çais:cer¦ceis:çar¦queis:car¦urmais:ormir¦eis:ar",
      "rev": "entir:intais¦ervir:irvais¦ectir:ictais¦1rer:eirais¦1zer:agais¦1r:eiais¦1ber:aibais¦1gir:ijais,ujais,ljais¦1eguir:sigais¦1erir:firais,dirais,girais,sirais,tirais¦1etir:pitais¦1edir:ridais¦1ir:venhais¦1estir:vistais¦2ar:stejais¦2er:omais,rrais,ebais,frais,emais,chais,azais,mpais,osais¦2gir:injais,urjais,eajais,erjais,oajais,unjais,arjais¦2r:vejais,tenhais¦2ger:lejais,anjais,rejais¦2zer:digais¦2cir:arçais¦2uer:rgais¦3ir:vidais,cidais,undais,oibais,andais,umbais,indais,pulais,sidais,entais,uirais,redais,nibais,urdais,anhais¦3ger:otejais¦3er:olhais,ordais,ambais,ertais,enzais,uerais,relais¦3çar:braqueis¦3dir:xpeçais,smeçais¦4dir:espeçais,impeçais¦4gir:terajais¦4ir:olidais,runhais,cardais,eferais¦4çar:trinqueis¦5er:bressais",
      "ex": "vades:ir¦2jais:ser,ver,haver,reger,viger¦1enhais:vir¦3ejais:estar¦2nhais:ter¦3irais:querer¦3gais:trazer¦2ais:rir¦2iais:ler¦2ibais:saber,caber¦1intais:sentir,mentir¦2çais:pedir,medir¦3ais:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iais:crer¦5jais:prover,prever¦1istais:vestir¦1irvais:servir¦4jais:rever¦4nhais:deter,reter,obter¦3itais:repetir¦1ulais:polir¦4queis:abraçar¦4ais:morder,treler,curtir,exibir,ebulir,elidir,ilidir,condir,garrir¦3idais:agredir¦3enhais:advir¦3istais:investir¦2queis:coçar,roçar,laçar¦3nhais:ater¦5idais:progredir¦3queis:calçar,forçar,atiçar¦3intais:assentir¦7jais:entrever,interver¦2enhais:avir¦4iais:reler¦7ais:dissentir¦1ais:rer¦9ais:retrogredir¦8ais:correferir¦2ictais:flectir¦1onhais:pôr¦2gais:dizer¦1jais:agir¦1igais:seguir¦1irais:ferir,gerir¦4çais:impedir¦1urtais:sortir¦1coiteis:açoitar¦3jais:monger¦6jais:absterger"
    },
    "secondPlural": {
      "fwd": "onham:ôr¦jam:gir,ger¦igam:eguir¦iram:erir¦am:uer¦çam:cir¦urtam:ortir¦coitem:çoitar¦1jam:aver¦1am:mer,rer,ber,her,per,ser,hir¦1gam:izer¦1em:iar¦2am:ndir,rter,mbir,ulir,idir,irir,rdir¦2eiem:nsiar¦2çam:pedir,medir¦2quem:inçar¦3em:iguar,nquar¦3am:arrir¦4em:inguar,coitar",
      "both": "5am:ementir,flectir,mprazer¦5jam:terver¦5ejam:brestar¦5nham:treter¦4uem:umegar,amegar,elegar¦4em:foitar,noitar¦4am:inibir,opelir,xceler,rreter,epolir,rantir,orrir¦4intam:ressentir¦4jam:tever¦4eiem:cendiar¦4iram:equerer¦4enham:tervir¦3am:bolir,arzir,abrir,orver,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3uem:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3em:bitar,titar,vitar,ejuar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3quem:emoçar,troçar,braçar¦3idam:egredir,sgredir¦3iam:crer¦3eiem:mediar¦3nham:ster,bter,nter¦3enham:rovir¦2am:lpir,orir,cuir,urir,alir,odir,plir,adir,tuir,ater,upir,imir,ozer,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,itir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2em:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úlem:baular¦2enham:avir,evir,nvir¦2ízem:juizar¦2intam:smentir,nsentir¦2uem:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilam:mpelir,xpelir¦2ínem:ruinar¦2itais:mpetir¦2ham:aler¦2cam:erder¦1údem:iudar¦1irvam:servir¦1çam:uvir,azer¦1ízem:aizar,eizar¦1úcem:iuçar¦1ísquem:aiscar¦1águam:saguar¦1em:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjam:vergir¦1águem:xaguar¦1iram:arir¦1íbam:oibir¦1am:oer,nir,xer¦1ulam:golir¦1únam:eunir¦1itam:letir¦1iem:ear¦1nham:or¦1ibam:aber¦1ssam:oder¦óleguem:olegar¦irzam:erzir¦ínquam:inquir¦igram:egrir¦ispam:espir¦ubram:obrir¦équem:equar¦irtam:ertir¦ussam:ossir¦çam:cer¦cem:çar¦quem:car¦urmam:ormir",
      "rev": "ar:eem¦entir:intam¦ervir:irvam¦udar:údem¦iliar:íliem¦ectir:ictam¦1rer:eiram¦1zer:agam¦1r:eiam¦1gir:ijam,ujam,ljam¦1eguir:sigam¦1erir:firam,diram,giram,siram,tiram¦1etir:pitam¦1edir:ridam¦1enir:vinam¦1estir:vistam¦1ar:tem¦1ir:venham¦2ar:stejam,viem,piem,oiem,fiem,ciem,riem,giem,diem,aiem,tiem,biem,siem,ziem,niem,uiem,miem,xiem¦2er:omam,rram,ebam,cham,fram,etam,emam,osam,mpam¦2gir:injam,urjam,eajam,erjam,oajam,unjam,arjam¦2r:vejam,tenham¦2ger:lejam,anjam,rejam,onjam¦2zer:digam¦2cir:arçam¦2uer:rgam¦3ir:vidam,cidam,undam,uspam,andam,indam,sidam,lidam,uiram,unham,bulam,redam,urzam,feram,ardam¦3ger:otejam¦3er:olham,ambam,ervam,ertam,ueram,relam,essam¦3ar:iliem,pliem,aliem,oliem¦3dir:xpeçam¦4dir:espeçam,impeçam,esmeçam¦4gir:terajam¦4ar:ziguem,reliem¦4ir:cumbam,apulam,sentam,lanham¦4çar:trinquem¦4ger:sterjam¦5ar:pinquem,ginquem,aniguem",
      "ex": "vão:ir¦águem:aguar¦2jam:ser,ver,haver,reger,viger¦1enham:vir¦3ejam:estar¦2nham:ter¦1eem:dar¦3iram:querer¦3gam:trazer¦2am:rir¦2iam:ler¦1intam:sentir,mentir¦2çam:pedir,medir¦3am:abrir,dever,meter,jazer,arder,bulir,urdir¦3iam:crer¦3uem:pegar,negar,regar,cegar,legar,segar¦5jam:prover,prever¦1istam:vestir¦1irvam:servir¦4jam:rever¦2eiem:odiar¦4nham:deter,reter¦3itam:repetir¦1ulam:polir¦4am:curtir,cuspir,ferver,inibir,treler,zurzir,zumbir,condir,surdir,garrir¦2em:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idam:agredir¦3eiem:mediar,ansiar¦4inam:prevenir¦3enham:advir¦3istam:investir,revestir¦2údem:saudar¦2quem:coçar,roçar,laçar¦3nham:ater¦5idam:progredir¦3quem:calçar,forçar,atiçar¦3em:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4uem:alegar¦3íliem:mobiliar¦3intam:assentir¦7jam:entrever¦2enham:avir¦4iam:reler¦4intam:ressentir¦7am:dissentir¦1am:rer¦9am:retrogredir¦8am:correferir¦2ictam:flectir¦4em:poitar¦1onham:pôr¦2gam:dizer¦1jam:agir¦1igam:seguir¦1iram:ferir,gerir¦4çam:impedir¦7em:averiguar¦1urtam:sortir¦5em:minguar¦1coitem:açoitar"
    },
    "thirdPlural": {
      "fwd": "",
      "both": "itam:etir",
      "rev": "",
      "ex": ""
    }
  },
  "imperative": {
    "first": {
      "fwd": "õe:ôr¦urte:ortir¦coita:çoitar¦1e:sir,cir¦1ói:roer¦1ole:pulir¦2e:idir,ngir,olir,ndir,etir,inir,odir,atir,elir,mbir,nzir,rdir¦2eia:nsiar¦2ca:inçar¦3e:ertir,urtir,arrir",
      "both": "2:izer¦3:fazer¦5:sprazer¦5e:sservir,nsfugir¦5á:brestar¦5ê:ntrever¦5eia:ncendiar¦5ói:onstruir¦4e:emunir,parzir,smedir,esunir,cernir,olorir,esumir,eragir,ssumir¦4ca:stroçar¦4ê:terver¦4ói:estruir¦4i:caver¦4ém:treter,tervir¦3e:talir,anhir,nibir,runir,ornir,bulir,oagir,unhir,ramir,pedir,rquir,xibir,ludir,audir,eagir,nguir,eguir,artir¦3ca:emoçar,braçar¦3í:mbair¦3ide:sgredir¦3ê:tever¦3eia:mediar¦3ém:rovir¦2e:lpir,urir,lgir,plir,ctir,irir,brir,rpir,adir,imir,anir,trir,uzir,rgir,utir,itir,erir,ntir,prir,stir,igir,uvir,rmir¦2ém:avir,evir,dvir,ster,bter,nvir,nter¦2íza:juizar¦2ome:bsumir,nsumir¦2ê:crer¦2ína:ruinar¦1úda:iudar¦1íza:aizar,eizar¦1úça:iuçar¦1ísca:aiscar¦1ói:moer¦1ode:cudir¦1íbe:oibir¦1úne:eunir¦1ia:ear¦ólega:olegar¦irze:erzir¦ínque:inquir¦igre:egrir¦ope:upir¦água:aguar¦ospe:uspir¦équa:equar¦obe:ubir¦õe:or¦:r",
      "rev": "er:ê, ou dize¦ugir:oge¦udar:úda¦iliar:ília¦ular:úla¦1er:z ou faze,r,tém¦1ar:tá¦1r:ei¦1edir:ride¦1enir:vine¦1ir:vém¦2er:az¦2ir:une,are,uge,ene,ore¦2oer:rrói¦2ulir:apole¦3ir:vide,inge,cide,pete,bole,unde,gole,fine,lode,ande,arce,pele,umbe,inde,side,unge,rode,lide,arde,urze,urde¦4ir:flete,emole,epole,ranze,grede¦4çar:trinca¦5ir:iverte,dverte",
      "ex": "4:querer,trazer¦vai:ir¦água:aguar¦1ê:ser,ver,ler¦3 ou faze:fazer¦1em:vir¦3á:estar¦2m:ter¦1á:dar,haver¦3 ou dize:dizer¦2e:agir,unir¦3e:pedir,medir,punir,parir,rugir,mugir,munir,zunir,balir,lenir,latir,ungir,delir,tinir,urdir¦2ê:crer¦5i:reaver¦1oge:fugir¦1ome:sumir¦4ê:prover,prever¦4e:servir,despir,fremir,zurzir,tossir,curtir,condir,garrir¦3ê:rever,reler¦2eia:odiar¦3ém:deter,reter¦1ule:polir¦1ói:roer,moer,soer¦3ide:agredir¦3eia:mediar,ansiar¦4ine:prevenir¦2úda:saudar¦2ca:coçar,roçar,laçar¦2ém:ater,avir¦2ege:frigir¦5ide:progredir¦4a:prazer¦3ca:calçar,forçar,atiçar¦1ole:bulir¦3ília:mobiliar¦4ide:regredir¦1usca:moscar¦5e:revenir,retinir¦3oge:refugir¦9e:retrogredir¦3úla:abaular¦6e:reflorir¦1õe:pôr¦1urte:sortir¦1coita:açoitar"
    },
    "second": {
      "fwd": "onha:ôr¦ja:gir,ger¦iga:eguir¦ira:erir¦ita:etir¦a:uer¦ça:cir¦urta:ortir¦coite:çoitar¦1ja:aver¦1a:mer,rer,ber,her,per,ser,hir¦1ga:izer¦1e:iar¦2a:itir,ndir,nzer,idir,mbir,rter,nzir,ulir,irir¦2eie:nsiar¦2ça:pedir,medir¦2que:inçar¦3a:urtir,arrir¦3e:iguar,nquar¦4e:inguar",
      "both": "3:emir,amir,rpir,anir¦4:celir,ernir,aurir,rquir¦5:turdir,randir,epelir,olorir,emolir¦5a:ementir,flectir,mprazer,estruir,nstruir¦5eja:brestar¦5nha:treter¦4a:florir,mburir,etinir,opelir,xceler,esunir,rreter,epolir,efinir,rantir,orrir¦4ue:umegar,amegar,elegar¦4e:ltitar,noitar¦4ça:sprazer¦4inta:ressentir¦4ia:screr¦4ida:nsgredir¦4ja:tever¦4eie:cendiar¦4ira:equerer¦4enha:tervir¦3a:munir,rurir,arzir,runir,ardir,abrir,reler,nibir,orver,xibir,rguir,fruir,order,meter,rever,artir¦3í:rruir¦3ue:iegar,negar,fegar,segar,pegar,vegar,regar,hegar¦3e:vitar,bitar,pitar,uitar,gitar,litar,citar,sitar,mitar,ditar,ritar,eitar¦3que:emoçar,troçar,braçar¦3inta:esmentir¦3ida:egredir¦3ila:ompelir¦3eie:mediar¦3nha:ster,bter,nter¦3ina:revenir¦3enha:rovir¦2a:cuir,alir,odir,plir,tuir,adir,upir,imir,ater,trir,udir,buir,nguir,over,lver,nuir,uzir,eder,utir,luir,stir,suir,umir,prir,ubir,iver,nder,air¦2e:fuar,ruar,suar,duar,muar,xtar,juar,ctar,cuar,ptar,otar,rtar,tuar,etar,utar,atar,nuar,ltar,star,ntar¦2úle:baular¦2ue:sgar,lgar,ngar,rgar,agar,igar,ugar,ogar¦2enha:avir,evir,dvir,nvir¦2íze:juizar¦2ista:evestir¦2íne:ruinar¦2ila:xpelir¦2inta:nsentir¦2ça:fazer¦2ha:aler¦2ca:erder¦1úde:iudar¦1irva:servir¦1ça:uvir¦1íze:aizar,eizar¦1úce:iuçar¦1ísque:aiscar¦1e:far,xar,nar,zar,bar,par,var,har,oar,jar,rar,sar,dar,lar,mar¦1irja:vergir¦1ira:arir¦1íba:oibir¦1a:oer,xer¦1ula:golir¦1úna:eunir¦1ie:ear¦1nha:or¦1iba:aber¦1ssa:oder¦ólegue:olegar¦irza:erzir¦ínqua:inquir¦igra:egrir¦águe:aguar¦ispa:espir¦ubra:obrir¦éque:equar¦irta:ertir¦ussa:ossir¦ça:cer¦ce:çar¦que:car¦urma:ormir",
      "rev": "ar:ê¦entir:inta¦ervir:irva¦udar:úde¦er:am¦ir:í¦iliar:ílie¦ectir:icta¦1zer:aça,aga¦1rer:eira¦1r:eia,i,ei¦1gir:ija,uja,lja¦1eguir:siga¦1erir:fira,dira,gira,sira,tira¦1etir:pita,lita¦1edir:rida¦1estir:vista¦1ar:te¦1ir:venha¦2ar:steja,vie,pie,oie,fie,cie,rie,gie,die,aie,tie,bie,sie,zie,nie,uie,mie,xie¦2er:oma,rra,eba,cha,fra,eta,ema,mpa,osa¦2gir:inja,urja,eaja,erja,oaja,unja,arja¦2r:veja,tenha¦2ger:leja,anja,reja,onja¦2zer:diga¦2ir:una,rua,rna,ena,ola,lpa¦2cir:arça¦2uer:rga¦3ir:vida,cida,uira,unda,uspa,mita,anda,inda,sida,anza,umba,bula,lida,reda,urza¦3ger:oteja¦3er:olha,amba,erva,enza,erta,uera,essa¦3ar:ilie,plie,alie,olie,elie¦3dir:xpeça,smeça¦4dir:espeça,impeça¦4gir:teraja¦4ar:zigue,nigue¦4ir:apula,runha,senta,efera¦4çar:trinque¦5ar:pinque,ginque¦5ger:bsterja",
      "ex": "4:latir,ungir,munir,delir,tinir¦5:abolir,fulgir¦6:impelir¦7:esculpir,impingir¦vá:ir¦águe:aguar¦2ja:ser,ver,haver,reger,viger¦2ça:fazer,pedir,medir¦1enha:vir¦3eja:estar¦2nha:ter¦1ê:dar¦3ira:querer¦3ga:trazer¦2a:rir,unir¦2ia:ler¦1inta:sentir,mentir¦3a:abrir,dever,punir,meter,jazer,cozer,arder,zunir,urdir,lenir,bulir¦3ia:crer¦3ue:pegar,negar,regar,cegar,legar,segar¦5ja:prover,prever¦1ista:vestir¦1irva:servir¦4ja:rever¦2eie:odiar¦4nha:deter,reter¦1ula:polir¦2e:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦4a:cuspir,ferver,fornir,zurzir,surdir,curtir,condir,garrir¦3ida:agredir¦3eie:mediar,ansiar¦3ista:investir¦2úde:saudar¦2que:coçar,roçar,laçar¦3nha:ater¦5ida:progredir¦4am:prazer¦3que:calçar,forçar,atiçar¦3e:citar,fitar,ditar,pitar,eguar,aliar,chiar¦3i:soer¦2í:ruir,puir¦4ue:alegar¦3ílie:mobiliar¦3inta:assentir¦6a:obstruir¦7ja:entrever,interver¦2enha:avir¦4ia:reler¦3í:fruir,pruir¦1usque:moscar¦4inta:ressentir¦9í:desobstruir¦7a:dissentir,insculpir¦5a:revenir,rebolir,planhir¦1a:rer¦9a:retrogredir¦8a:correferir¦5e:afoitar,minguar¦6í:abstruir¦8e:abiscoitar¦2icta:flectir¦4e:poitar¦1onha:pôr¦2ga:dizer¦1ja:agir¦1iga:seguir¦1ira:ferir,gerir¦4ça:impedir¦7e:averiguar¦1urta:sortir¦1coite:açoitar"
    },
    "third": {
      "fwd": "onhamos:ôr¦jamos:gir,ger¦igamos:eguir¦iramos:erir¦itamos:etir¦amos:uer¦çamos:cir¦urtamos:ortir¦coitemos:çoitar¦1amos:mer,rer,ber,bir,her,per,ser,hir¦1gamos:izer¦2amos:idir,itir,ndir,nzer,ulir,rter,irir,rdir¦2çamos:pedir,medir¦2quemos:inçar¦3amos:urtir,arrir",
      "both": "5amos:ementir,flectir,mprazer¦5ejamos:brestar¦5nhamos:treter¦4amos:morder,opelir,xceler,inquir,rreter,orrir¦4nhamos:uster,bster¦4jamos:tever¦4iramos:equerer¦4enhamos:tervir¦3amos:scuir,bolir,arzir,urzir,abrir,anzir,polir,rguir,meter,uspir,antir,ssuir,artir¦3quemos:emoçar,troçar¦3intamos:essentir,onsentir¦3idamos:egredir,sgredir¦3iamos:crer¦3inamos:revenir¦3enhamos:rovir¦3nhamos:nter¦2amos:lpir,orir,urir,alir,odir,plir,upir,imir,eder,udir,trir,ater,buir,nguir,tuir,adir,nuir,uzir,ruir,utir,luir,umir,prir,stir,nder,air¦2intamos:smentir¦2istamos:evestir¦2ilamos:mpelir,xpelir¦2enhamos:avir,evir,dvir,nvir¦2hamos:aler¦2camos:erder¦1irvamos:servir¦1irjamos:vergir¦1iramos:arir¦1amos:oer,nir,xer,ver¦1ulamos:golir¦1nhamos:or¦1uemos:gar¦1çamos:uvir,azer¦1ssamos:oder¦irzamos:erzir¦igramos:egrir¦ispamos:espir¦ubramos:obrir¦irtamos:ertir¦ussamos:ossir¦çamos:cer¦cemos:çar¦quemos:car¦urmamos:ormir¦emos:ar",
      "rev": "entir:intamos¦ervir:irvamos¦ectir:ictamos¦1rer:eiramos¦1zer:agamos¦1r:eiamos¦1ber:aibamos¦1gir:ijamos,ujamos,ljamos¦1eguir:sigamos¦1erir:firamos,diramos,giramos,siramos,tiramos¦1etir:pitamos,litamos¦1edir:ridamos¦1estir:vistamos¦1ir:venhamos¦2ar:stejamos¦2er:omamos,rramos,ebamos,framos,emamos,chamos,azamos,mpamos,osamos¦2gir:injamos,urjamos,eajamos,erjamos,oajamos,unjamos,arjamos¦2r:vejamos,tenhamos¦2ger:lejamos,anjamos,rejamos¦2zer:digamos¦2cir:arçamos¦2uer:rgamos¦3ir:vidamos,cidamos,uiramos,undamos,oibamos,andamos,mitamos,umbamos,indamos,pulamos,sidamos,unhamos,entamos,bulamos,lidamos,redamos,nibamos,urdamos,anhamos¦3ger:otejamos¦3er:olhamos,ordamos,ambamos,ertamos,enzamos¦3çar:braquemos¦3dir:xpeçamos,smeçamos¦4dir:espeçamos,impeçamos¦4gir:terajamos¦4iar:obilemos¦4er:queramos¦4ir:cardamos,eferamos¦4çar:trinquemos¦5er:bressamos",
      "ex": "vamos:ir¦2jamos:ser,ver,haver,reger,viger¦1enhamos:vir¦3ejamos:estar¦2nhamos:ter¦3iramos:querer¦3gamos:trazer¦2amos:rir¦2iamos:ler¦2ibamos:saber,caber¦1intamos:sentir,mentir¦2çamos:pedir,medir¦3amos:abrir,meter,jazer,cozer,arder,subir,bulir,urdir¦3iamos:crer¦5jamos:prover,prever¦1istamos:vestir¦1irvamos:servir¦4jamos:rever¦4nhamos:deter,reter,obter¦1ulamos:polir¦4quemos:abraçar¦4amos:morder,treler,curtir,exibir,condir,garrir¦3idamos:agredir¦3istamos:investir¦2quemos:coçar,roçar,laçar¦3nhamos:ater¦5idamos:progredir¦3quemos:calçar,forçar,atiçar¦5emos:mobiliar¦3intamos:assentir¦7jamos:entrever,interver¦2enhamos:avir¦4iamos:reler¦7amos:dissentir¦1amos:rer¦9amos:retrogredir¦8amos:correferir¦2ictamos:flectir¦1onhamos:pôr¦2gamos:dizer¦1jamos:agir¦1igamos:seguir¦1iramos:ferir,gerir¦4çamos:impedir¦1urtamos:sortir¦1coitemos:açoitar¦3jamos:monger¦6jamos:absterger"
    },
    "firstPlural": {
      "fwd": "onde:ôr¦coitai:çoitar¦3cai:rinçar",
      "both": "2:hir,cir,zir,pir,nir,lir,rir,bir,dir,gir,mir,tir¦3:ssir¦4:nquir,nguir,eguir¦5:servir¦5de:terver¦5nde:treter,tervir¦4de:tever,orrir¦4nde:rovir¦3cai:troçar¦3de:crer¦3nde:avir,evir,ster,bter,nvir,nter¦2çais:ouvir¦1í:uir,air¦1nde:or¦i:r",
      "rev": "r:nde¦1r:ede,ide¦2r:vi¦2çar:mocai¦3çar:bracai¦4çar:trincai",
      "ex": "4:ouvir¦5:servir¦1de:ir¦2de:ser,ver,rir,ler¦2nde:vir,ter¦3de:crer¦5de:prover,prever¦4de:rever,reler¦4nde:deter,reter,advir¦4cai:abraçar,remoçar¦2cai:coçar,roçar,laçar¦3nde:ater,avir¦3cai:calçar,forçar,atiçar¦7de:entrever¦1onde:pôr¦1coitai:açoitar"
    },
    "secondPlural": {
      "fwd": "onham:ôr¦jam:gir,ger¦igam:eguir¦iram:erir¦itam:etir¦am:uer¦çam:cir¦urtam:ortir¦coitem:çoitar¦1jam:aver¦1am:mer,rer,ber,her,per,ser,hir¦1gam:izer¦1em:iar¦2am:itir,ndir,rter,mbir,ulir,idir,irir,rdir¦2eiem:nsiar¦2çam:pedir,medir¦2quem:inçar¦3em:iguar,nquar¦3am:arrir¦4em:inguar,coitar",
      "both": "5am:ementir,flectir,mprazer¦5jam:terver¦5ejam:brestar¦5idam:ansgredir¦5nham:treter¦4uem:umegar,amegar,elegar¦4em:foitar,noitar¦4am:inibir,opelir,xceler,sorver,rreter,epolir,rantir,orrir¦4intam:ressentir¦4jam:tever¦4eiem:cendiar¦4iram:equerer¦4enham:tervir¦3am:bolir,arzir,abrir,anzir,enzer,xibir,rguir,order,meter,rever,artir¦3uem:iegar,pegar,negar,fegar,segar,vegar,regar,hegar¦3em:bitar,titar,gitar,vitar,ejuar,pitar,uitar,sitar,litar,citar,mitar,ditar,ritar,eitar¦3quem:emoçar,troçar,braçar¦3idam:egredir¦3iam:crer¦3eiem:mediar¦3nham:ster,bter,nter¦3enham:rovir¦2am:lpir,orir,cuir,urir,alir,odir,plir,adir,ater,upir,imir,ozer,trir,over,udir,buir,nguir,tuir,lver,nuir,uzir,eder,utir,luir,ruir,stir,suir,umir,prir,ubir,iver,nder,air¦2em:fuar,ruar,suar,duar,muar,xtar,cuar,ptar,ctar,otar,tuar,etar,rtar,utar,atar,nuar,ltar,star,ntar¦2úlem:baular¦2ízem:juizar¦2intam:smentir,nsentir¦2uem:lgar,ngar,sgar,rgar,agar,igar,ugar,ogar¦2ilam:mpelir,xpelir¦2ínem:ruinar¦2enham:avir,evir,dvir,nvir¦2ham:aler¦2cam:erder¦1údem:iudar¦1irvam:servir¦1çam:uvir,azer¦1ízem:aizar,eizar¦1úcem:iuçar¦1ísquem:aiscar¦1em:far,xar,nar,zar,bar,par,var,har,oar,jar,mar,rar,sar,dar,lar¦1irjam:vergir¦1iram:arir¦1íbam:oibir¦1am:oer,nir,xer¦1ulam:golir¦1únam:eunir¦1iem:ear¦1nham:or¦1ibam:aber¦1ssam:oder¦óleguem:olegar¦irzam:erzir¦ínquam:inquir¦igram:egrir¦águem:aguar¦ispam:espir¦ubram:obrir¦équem:equar¦irtam:ertir¦ussam:ossir¦çam:cer¦cem:çar¦quem:car¦urmam:ormir",
      "rev": "ar:eem¦entir:intam¦ervir:irvam¦udar:údem¦iliar:íliem¦ectir:ictam¦1rer:eiram¦1zer:agam¦1r:eiam¦1gir:ijam,ujam,ljam¦1eguir:sigam¦1erir:firam,diram,giram,siram,tiram¦1etir:pitam,litam¦1edir:ridam¦1enir:vinam¦1estir:vistam¦1ar:tem¦1ir:venham¦2ar:stejam,viem,piem,oiem,fiem,ciem,riem,giem,diem,aiem,tiem,biem,siem,ziem,niem,uiem,miem,xiem¦2er:omam,rram,ebam,cham,fram,etam,emam,mpam,osam¦2gir:injam,urjam,eajam,erjam,oajam,unjam,arjam¦2r:vejam,tenham¦2ger:lejam,anjam,rejam,onjam¦2zer:digam¦2cir:arçam¦2uer:rgam¦3ir:vidam,cidam,uiram,undam,uspam,mitam,andam,indam,sidam,lidam,unham,umbam,bulam,redam,urzam,feram,ardam¦3ger:otejam¦3er:olham,ambam,ervam,ertam,ueram,orvam,relam,essam¦3ar:iliem,pliem,aliem,oliem¦3dir:xpeçam¦4dir:espeçam,impeçam,esmeçam¦4gir:terajam¦4ar:ziguem,reliem¦4ir:apulam,sentam,lanham¦4çar:trinquem¦4ger:sterjam¦5ar:pinquem,ginquem,aniguem",
      "ex": "vão:ir¦águem:aguar¦2jam:ser,ver,haver,reger,viger¦1enham:vir¦3ejam:estar¦2nham:ter¦1eem:dar¦3iram:querer¦3gam:trazer¦2am:rir¦2iam:ler¦1intam:sentir,mentir¦2çam:pedir,medir¦3am:abrir,dever,meter,jazer,arder,bulir,urdir¦3iam:crer¦3uem:pegar,negar,regar,cegar,legar,segar¦5jam:prover,prever¦1istam:vestir¦1irvam:servir¦4jam:rever¦2eiem:odiar¦4nham:deter,reter¦1ulam:polir¦4am:curtir,cuspir,ferver,inibir,sorver,treler,zurzir,condir,surdir,garrir¦2em:suar,atar,ruar,fiar,miar,piar,liar,aiar,siar¦3idam:agredir¦3eiem:mediar,ansiar¦4inam:prevenir¦3istam:investir,revestir¦2údem:saudar¦2quem:coçar,roçar,laçar¦3nham:ater¦5idam:progredir¦3quem:calçar,forçar,atiçar¦3em:citar,fitar,ditar,pitar,eguar,aliar,chiar¦4uem:alegar¦3íliem:mobiliar¦3intam:assentir¦7jam:entrever¦2enham:avir¦4iam:reler¦1usquem:moscar¦4intam:ressentir¦7am:dissentir¦1am:rer¦9am:retrogredir¦8am:correferir¦2ictam:flectir¦4em:poitar¦1onham:pôr¦2gam:dizer¦1jam:agir¦1igam:seguir¦1iram:ferir,gerir¦4çam:impedir¦7em:averiguar¦1urtam:sortir¦5em:minguar¦1coitem:açoitar"
    },
    "thirdPlural": {
      "fwd": "",
      "both": "",
      "rev": "",
      "ex": ""
    }
  },
  "imperfect": {
    "first": {
      "fwd": "ia:er¦unha:ôr¦1a:ir¦2cava:tiçar",
      "both": "5nha:tervir¦4va:pitar,citar,gitar,litar,bitar,ritar,mitar,sitar,vitar,ditar,eitar¦4nha:rovir¦4inha:treter¦4ía:ossuir¦3va:xtar,ctar,otar,etar,ptar,utar,atar,rtar,ltar,ntar,star¦3nha:avir,evir,dvir,nvir¦2ía:moer,doer,roer,tuir,buir,nuir,luir,ruir¦2va:far,xar,ear,par,uar,iar,nar,jar,zar,bar,rar,sar,var,har,oar,çar,gar,car,lar,dar,mar¦2inha:ster,bter,nter¦1ía:air¦coitava:çoitar¦unha:or",
      "rev": "1er:via,cia,xia,oía,hia,tinha,oia¦1ir:uía¦2er:azia,omia,izia,ndia,abia,ebia,atia,rria,fria,egia,mpia,ozia,osia,cria¦2r:uia,lia,nia,vinha¦2çar:alcava¦3er:ueria,erdia,metia,ordia,ambia,remia,cedia,angia,valia,enzia¦3r:rmia,ntia,uvia,igia,ubia,ugia,pria,ssia,umia,stia,oria,idia,utia,rgia,bria,uzia,spia,itia,agia,udia,ibia,upia,uria,lpia,rpia,imia,adia,rzia,iria,nhia¦4r:artia,ingia,feria,petia,geria,letia,undia,redia,lodia,seria,andia,india,arcia,egria,teria,ortia,pedia,umbia,anzia,ramia,urdia,ungia¦4er:rretia¦5er:nvertia,evertia,bvertia,rvertia",
      "ex": "era:ser¦1a:ir¦2nha:vir¦1inha:ter¦2va:dar¦2ía:doer,roer,moer,soer,ruir,puir¦3inha:deter,reter¦4cava:abraçar¦2cava:coçar,roçar,laçar¦2inha:ater¦4ía:arguir¦3cava:calçar,forçar,atiçar¦4va:citar,fitar,ditar¦3va:atar¦5va:quitar¦3nha:avir¦1ia:ver,ler¦3ia:poder,valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦1unha:pôr¦2a:rir¦5a:sorrir,servir,aderir,curtir,nutrir,surtir¦3a:agir,adir¦4a:pedir,medir,ferir,parir,latir,gerir,remir,ungir¦2ia:crer¦7a:divertir,advertir¦4ia:erguer,verter"
    },
    "second": {
      "fwd": "ias:er¦unhas:ôr¦2as:tir,mir,dir,gir,bir,rir,pir,zir,cir,hir¦2cavas:tiçar",
      "both": "5vas:abitar¦5vam:rassar¦4vas:gitar,pitar,uitar,litar,ritar,mitar,citar,vitar,sitar,ditar,eitar¦4inhas:treter¦3vas:xtar,ptar,ctar,otar,etar,utar,atar,rtar,ltar,ntar,star¦3as:quir,guir,ssir,uvir¦2ías:nuir,moer,roer,tuir,buir,luir,ruir,suir¦2íam:doer¦2vas:far,par,jar,zar,oar,iar,nar,gar,bar,uar,var,har,xar,sar,ear,rar,çar,car,dar,lar,mar¦2inhas:ster,bter,nter¦2as:nir,lir¦2nhas:vir¦1ías:air¦coitavas:çoitar¦unhas:or",
      "rev": "er:íam¦1er:cias,xias,hias,tinhas,oías,ziam,oias¦1ir:uías¦2er:azias,avias,omias,izias,ndias,abias,evias,ebias,egias,atias,rrias,ovias,frias,lvias,ivias,mpias,ozias,osias,crias¦2çar:alcavas¦2r:niam,giam¦3er:uerias,erdias,metias,ordias,ambias,remias,cedias,angias,valias,enzias,orvias¦3r:rmias,ntias,igias,ubias,ugias,prias,umias,stias,orias,idias,utias,rgias,brias,uzias,spias,itias,agias,udias,ibias,upias,urias,lpias,rpias,imias,adias,rzias,irias,nhias¦4r:artias,ingias,ferias,petias,gerias,letias,undias,redias,lodias,serias,andias,indias,arcias,egrias,terias,ortias,urtias,anzias,ramias,urdias,ungias¦4er:rretias,tervias¦5r:spedias,mpedias,xpedias,cumbias¦5er:nvertias,bvertias,rvertias",
      "ex": "eras:ser¦1as:ir¦2nhas:vir¦1inhas:ter¦2vas:dar¦2as:rir¦2íam:doer¦5as:servir,sorrir,aderir,nutrir,zumbir¦3inhas:deter,reter¦4cavas:abraçar¦2ías:roer,moer,soer,ruir,puir¦5iam:aprazer¦2cavas:coçar,roçar,laçar¦2inhas:ater¦4ías:arguir¦4iam:prazer¦3cavas:calçar,forçar,atiçar¦4vas:citar,fitar,ditar¦3vas:atar¦8am:concernir¦4am:urgir¦1ias:ver,ler¦3ias:poder,valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦1unhas:pôr¦3as:agir,adir¦4as:pedir,medir,ferir,parir,latir,gerir,remir,ungir¦2ias:crer¦7as:divertir,advertir¦4ias:erguer,ferver,verter¦6ias:reverter"
    },
    "third": {
      "fwd": "ia:er¦unha:ôr¦1a:ir¦2cava:tiçar",
      "both": "5nha:tervir¦4va:pitar,citar,gitar,litar,bitar,ritar,mitar,sitar,vitar,ditar,eitar¦4nha:rovir¦4ía:ossuir¦3va:xtar,ctar,otar,etar,ptar,utar,atar,rtar,ltar,ntar,star¦3nha:avir,evir,dvir,nvir¦2ía:moer,roer,tuir,buir,nuir,luir,ruir¦2va:far,xar,ear,bar,par,uar,iar,nar,jar,zar,rar,sar,var,har,oar,çar,gar,car,lar,dar,mar¦2inha:ster,bter,nter¦1ía:air¦coitava:çoitar¦unha:or",
      "rev": "1er:via,cia,xia,tinha,hia,oía,oia¦1ir:uía¦2er:azia,omia,izia,ndia,abia,ebia,atia,rria,fria,egia,mpia,ozia,osia,cria¦2r:uia,lia,nia,vinha¦2çar:alcava¦3er:ueria,erdia,metia,ordia,ambia,remia,cedia,angia,valia,enzia¦3r:rmia,ntia,uvia,igia,ubia,ugia,pria,ssia,umia,stia,oria,idia,utia,rgia,bria,uzia,spia,itia,agia,udia,ibia,upia,uria,lpia,rpia,imia,adia,rzia,iria,nhia¦4r:artia,ingia,feria,petia,geria,letia,undia,redia,lodia,seria,andia,india,arcia,egria,teria,ortia,pedia,umbia,anzia,ramia,urdia,ungia¦4er:rretia¦5er:nvertia,evertia,bvertia,rvertia",
      "ex": "era:ser¦1a:ir¦2nha:vir¦1inha:ter¦2va:dar¦6inha:entreter¦3inha:deter,reter¦4cava:abraçar¦2ía:roer,moer,soer,ruir,puir¦2cava:coçar,roçar,laçar¦2inha:ater¦4ía:arguir¦3cava:calçar,forçar,atiçar¦4va:citar,fitar,ditar¦3va:atar¦5va:quitar¦3nha:avir¦1ia:ver,ler¦3ia:poder,valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦1unha:pôr¦2a:rir¦5a:sorrir,servir,aderir,curtir,nutrir,surtir¦3a:agir,adir¦4a:pedir,medir,ferir,parir,latir,gerir,remir,ungir¦2ia:crer¦7a:divertir,advertir¦4ia:erguer,verter"
    },
    "firstPlural": {
      "fwd": "íamos:er,ir¦únhamos:ôr",
      "both": "5ínhamos:ntreter¦4ínhamos:tervir¦3ínhamos:rovir¦2ínhamos:avir,evir,ster,bter,nvir,nter¦coitávamos:çoitar¦únhamos:or¦ávamos:ar",
      "rev": "1er:víamos,cíamos,xíamos,híamos,tínhamos,oíamos¦1ir:aíamos,uíamos,líamos,níamos,vínhamos¦2er:azíamos,omíamos,izíamos,ndíamos,abíamos,ebíamos,egíamos,atíamos,rríamos,fríamos,mpíamos,ozíamos,críamos¦2ir:rmíamos,ntíamos,uvíamos,igíamos,idíamos,stíamos,príamos,ssíamos,bríamos,itíamos,rgíamos,eríamos,uzíamos,spíamos,adíamos,umíamos,agíamos,udíamos,oríamos,imíamos,ibíamos,ugíamos,uríamos,lpíamos,gríamos,rpíamos,rzíamos,utíamos,upíamos,amíamos,nhíamos¦3ir:artíamos,ingíamos,uiríamos,petíamos,letíamos,undíamos,pedíamos,lodíamos,andíamos,utríamos,arcíamos,urtíamos,umbíamos,indíamos,urdíamos,ungíamos¦3er:ueríamos,erdíamos,metíamos,ambíamos,cedíamos,angíamos,valíamos,enzíamos,remíamos¦3çar:bracávamos¦4ir:gredíamos,ranzíamos¦4er:rretíamos¦5ir:ivertíamos¦5er:nvertíamos,evertíamos,bvertíamos,rvertíamos",
      "ex": "íamos:ir¦éramos:ser¦1ínhamos:vir,ter¦3ínhamos:deter,reter,advir¦4cávamos:abraçar¦2cávamos:coçar,roçar,laçar¦2ínhamos:ater,avir¦3cávamos:calçar,forçar,atiçar¦1íamos:ver,rir,ler¦3íamos:poder,pedir,subir,medir,valer,ceder,feder,gemer,temer,parir,meter,latir,viger,arder,coser,remir,ungir,reler¦1únhamos:pôr¦4íamos:sorrir,servir,morder,erguer,sortir,verter¦2íamos:agir,crer,adir¦6íamos:advertir"
    },
    "secondPlural": {
      "fwd": "íeis:er,ir¦únheis:ôr",
      "both": "5ínheis:ntreter¦4ínheis:tervir¦3ínheis:rovir¦2ínheis:avir,evir,ster,bter,nvir,nter¦coitáveis:çoitar¦únheis:or¦áveis:ar",
      "rev": "1er:víeis,cíeis,xíeis,híeis,tínheis,oíeis¦1ir:aíeis,uíeis,líeis,níeis,vínheis¦2er:azíeis,omíeis,izíeis,ndíeis,abíeis,ebíeis,egíeis,atíeis,rríeis,fríeis,mpíeis,ozíeis,críeis¦2ir:rmíeis,ntíeis,uvíeis,igíeis,idíeis,stíeis,príeis,ssíeis,bríeis,itíeis,rgíeis,eríeis,uzíeis,spíeis,adíeis,umíeis,agíeis,udíeis,oríeis,imíeis,ibíeis,ugíeis,uríeis,lpíeis,gríeis,rpíeis,rzíeis,utíeis,upíeis,amíeis,nhíeis¦3ir:artíeis,ingíeis,uiríeis,petíeis,letíeis,undíeis,pedíeis,lodíeis,andíeis,utríeis,arcíeis,urtíeis,umbíeis,indíeis,urdíeis,ungíeis¦3er:ueríeis,erdíeis,metíeis,ambíeis,cedíeis,angíeis,valíeis,enzíeis,remíeis¦3çar:bracáveis¦4ir:gredíeis,ranzíeis¦4er:rretíeis¦5ir:ivertíeis¦5er:nvertíeis,evertíeis,bvertíeis,rvertíeis",
      "ex": "íeis:ir¦éreis:ser¦1ínheis:vir,ter¦3ínheis:deter,reter,advir¦4cáveis:abraçar¦2cáveis:coçar,roçar,laçar¦2ínheis:ater,avir¦3cáveis:calçar,forçar,atiçar¦1íeis:ver,rir,ler¦3íeis:poder,pedir,subir,medir,valer,ceder,feder,gemer,temer,parir,meter,latir,viger,arder,coser,remir,ungir,reler¦1únheis:pôr¦4íeis:sorrir,servir,morder,erguer,sortir,verter¦2íeis:agir,crer,adir¦6íeis:advertir"
    },
    "thirdPlural": {
      "fwd": "iam:er¦unham:ôr¦1am:ir¦2cavam:tiçar",
      "both": "5nham:tervir¦4vam:pitar,citar,gitar,litar,bitar,ritar,mitar,sitar,vitar,ditar,eitar¦4nham:rovir¦4íam:ossuir¦3vam:xtar,ctar,otar,etar,ptar,utar,atar,rtar,ltar,ntar,star¦3nham:avir,evir,dvir,nvir¦2íam:moer,roer,tuir,buir,nuir,luir,ruir¦2vam:far,xar,ear,bar,par,uar,iar,nar,jar,zar,rar,sar,var,har,oar,çar,gar,car,lar,dar,mar¦2inham:ster,bter,nter¦1íam:air¦coitavam:çoitar¦unham:or",
      "rev": "1er:viam,ciam,xiam,tinham,hiam,oíam,oiam¦1ir:uíam¦2er:aziam,omiam,iziam,ndiam,abiam,ebiam,atiam,rriam,friam,egiam,mpiam,oziam,osiam,criam¦2r:uiam,liam,niam,vinham¦2çar:alcavam¦3er:ueriam,erdiam,metiam,ordiam,ambiam,remiam,cediam,angiam,valiam,enziam¦3r:rmiam,ntiam,uviam,igiam,ubiam,ugiam,priam,ssiam,umiam,stiam,oriam,idiam,utiam,rgiam,briam,uziam,spiam,itiam,agiam,udiam,ibiam,upiam,uriam,lpiam,rpiam,imiam,adiam,rziam,iriam,nhiam¦4r:artiam,ingiam,feriam,petiam,geriam,letiam,undiam,rediam,lodiam,seriam,andiam,indiam,arciam,egriam,teriam,ortiam,pediam,umbiam,anziam,ramiam,urdiam,ungiam¦4er:rretiam¦5er:nvertiam,evertiam,bvertiam,rvertiam",
      "ex": "eram:ser¦1am:ir¦2nham:vir¦1inham:ter¦2vam:dar¦6inham:entreter¦3inham:deter,reter¦4cavam:abraçar¦2íam:roer,moer,soer,ruir,puir¦2cavam:coçar,roçar,laçar¦2inham:ater¦4íam:arguir¦3cavam:calçar,forçar,atiçar¦4vam:citar,fitar,ditar¦3vam:atar¦5vam:quitar¦3nham:avir¦1iam:ver,ler¦3iam:poder,valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦1unham:pôr¦2am:rir¦5am:sorrir,servir,aderir,curtir,nutrir,surtir¦3am:agir,adir¦4am:pedir,medir,ferir,parir,latir,gerir,remir,ungir¦2iam:crer¦7am:divertir,advertir¦4iam:erguer,verter"
    }
  },
  "pastTense": {
    "first": {
      "fwd": "2:tir,mir,gir,dir,bir,rir,lir,pir,cir,hir¦3:ssir¦i:er¦us:ôr¦coitei:çoitar¦2ive:ster¦2quei:inçar",
      "both": "2:nir,zir¦3:quir,uvir¦4:nguir,eguir¦5:servir¦5ive:brestar¦5m:tervir¦4ou:rassar¦4m:rovir¦4ive:treter¦3m:avir,evir,dvir,nvir¦3quei:troçar,braçar¦3iz:sprazer¦3u:doer¦3ouve:mprazer¦2í:moer,roer¦2ive:bter,nter¦1iz:fazer¦1í:uir,air¦1ouve:eaver¦1uei:gar¦1sse:izer¦us:or¦cei:çar¦quei:car¦oube:aber¦ude:oder¦ei:ar",
      "rev": "azer:iz,ouve/prazeu¦erer:is¦r:m¦1azer:rouxe,rouve¦1er:ci,xi,oí,oi¦1r:iu¦2er:omi,rri,evi,ebi,egi,ati,ovi,lhi,chi,fri,avi,etive,lvi,ivi,azi,ozi,mpi,osi,cri¦2r:oeu,teu¦2çar:moquei¦3er:endi,erdi,meti,bstive,rgui,ambi,cedi,angi,erti,vali,enzi,orvi,reli,celi,essi,ordi¦3r:nti,igi,ubi,ugi,pri,umi,sti,bri,idi,uti,oli,eri,spi,iti,agi,udi,ori,tri,imi,upi,uri,lpi,rgi,rpi,adi,ibi,uli,pli,iri,nhi,odi,lgi,cti¦4r:arti,ormi,ingi,leti,undi,redi,andi,indi,arci,peli,pedi,umbi,rami,urdi,ungi,bali,medi,ardi¦4er:pondi,condi,rreti,premi¦4çar:trinquei¦5er:equeri,-queri,lqueri¦5r:epeti,mpeti,negri,stali",
      "ex": "2:rir¦3:agir,adir¦4:pedir,medir,falir,parir,latir,remir,ungir,delir,balir,urdir¦5:servir,sorrir,tossir,curtir,sortir,surtir,fremir,condir,garrir¦7:divertir,advertir¦fui:ir¦1iz:fazer¦2m:vir¦3ive:estar,deter,reter¦1ive:ter¦1ouve:haver¦2is:querer¦2ouxe:trazer¦3u:doer¦2í:roer,moer,soer¦3ouve:aprazer¦2quei:coçar,roçar,laçar¦2ive:ater¦2ouve/prazeu:prazer¦3quei:calçar,forçar,atiçar¦8u:concernir¦4u:urgir,later¦3m:avir¦4quei:remoçar¦9u:obstringir¦1i:ver,ler¦1us:pôr¦2i:crer¦3i:valer,ceder,feder,gemer,temer,meter,viger,arder,reler¦4i:tremer,ferver,premer,monger¦4ive:suster¦6i:interver¦1coitei:açoitar¦7i:absterger"
    },
    "second": {
      "fwd": "useste:ôr¦coitaste:çoitar¦2iveste:ster¦2caste:inçar",
      "both": "5iveste:brestar¦5iste:ntrever¦5este:tervir¦4caste:stroçar¦4iste:terver¦4am:doer¦4este:rovir¦4iveste:treter¦3regulamentasseiaste:baciar¦3caste:emoçar,braçar¦3izeste:sprazer¦3este:avir,evir,nvir¦3ouveste:mprazer¦3iste:tever¦2íste:cuir,buir,tuir,nuir,luir,ruir,suir¦2iveste:bter,nter¦1izeste:fazer¦1ouveste:eaver¦1íste:air¦1sseste:izer¦useste:or¦oubeste:aber¦udeste:oder¦ste:r",
      "rev": "2:aram,iram¦3:oeram,teram¦azer:izeste,ouveram¦erer:iseste¦ir:íste¦1r:ieste¦1azer:rouxeste,rouveram/prazeram¦2er:eviste,etiveste¦3er:ustiveste¦4çar:trincaste",
      "ex": "foste:ir¦1izeste:fazer¦2este:vir¦1iste:ver¦3iveste:estar,deter,reter¦1iveste:ter¦1este:dar¦1ouveste:haver¦2iseste:querer¦2ouxeste:trazer¦4am:doer¦4iste:prever¦3iste:rever¦4este:advir¦3ouveram:aprazer¦2caste:coçar,roçar,laçar¦2iveste:ater¦4íste:arguir¦2ouveram/prazeram:prazer¦3caste:calçar,forçar,atiçar¦7am:grassar¦2íste:ruir,puir¦9am:concernir¦5am:urgir,later¦3este:avir¦10am:obstringir¦1useste:pôr¦4iveste:abster¦1coitaste:açoitar"
    },
    "third": {
      "fwd": "coitou:çoitar¦1s:ôr¦2cou:inçar¦3ve:ster",
      "both": "5eve:brestar¦5u:rreter¦5ve:treter¦4iu:terver,ntever¦4u:orver,meter,caver,rever¦4ouve:omprazer¦4ve:onter¦4eio:tervir¦3cou:emoçar,troçar,braçar¦3u:nzer,iver,rter,ozer,mber,lver,eder,over,ater,rder,eber,nder¦3eio:rovir¦2u:ser,uer,ler,per,oer,her,xer,ger,cer,rer,mer¦2eio:avir,evir,dvir,nvir¦1ouve:eaver¦1sse:izer¦1u:ir¦ôs:or¦oube:aber¦ou:ar¦ôde:oder¦ez:azer",
      "rev": "ir:eio¦erer:is¦1azer:rouxe¦1r:eu¦2er:eviu¦3r:nteve,eteve¦4r:bsteve,usteve¦4çar:trincou",
      "ex": "foi:ir¦1eio:vir¦1iu:ver¦3eve:estar¦2ve:ter¦1eu:dar¦1ouve:haver¦2is:querer¦2ouxe:trazer¦2u:ler,rer¦5ve:manter¦4u:dever,meter,jazer¦4iu:prever¦3iu:rever¦4ve:deter,reter,obter¦2cou:coçar,roçar,laçar¦3ve:ater¦5u:ferver¦3cou:calçar,forçar,atiçar¦6iu:entrever¦2eio:avir¦2s:pôr¦1coitou:açoitar"
    },
    "firstPlural": {
      "fwd": "usemos:ôr¦coitamos:çoitar¦2mos:xer,ser¦2ivemos:ster¦2camos:inçar¦3mos:iver¦5mos:coitar",
      "both": "5mos:quitar,ltitar,noitar,rreter¦5ivemos:brestar¦5imos:ntrever¦5emos:tervir¦4mos:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4imos:terver,ntever¦4emos:rovir¦4ivemos:treter¦3camos:emoçar,troçar¦3mos:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3emos:evir,avir,dvir,nvir¦3ímos:ssuir¦2ímos:cuir,tuir,buir,nuir,luir,ruir¦2mos:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivemos:bter,nter¦1ouvemos:eaver¦1ímos:air¦1ssemos:izer¦1mos:ir¦usemos:or¦oubemos:aber¦udemos:oder¦izemos:azer",
      "rev": "erer:isemos¦ir:ímos¦1r:iemos¦1azer:rouxemos,rouvemos¦2er:evimos,etivemos¦2r:temos,tamos¦3r:evemos,azemos,ozemos,osemos,exemos¦3çar:bracamos¦4r:vivemos,ervemos¦4çar:trincamos¦5r:ressemos",
      "ex": "fomos:ir¦2emos:vir¦1imos:ver¦3ivemos:estar,deter,reter¦1ivemos:ter¦1emos:dar¦1ouvemos:haver¦2isemos:querer¦2ouxemos:trazer¦2mos:ler,rer¦4mos:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4imos:prever¦3imos:rever¦4camos:abraçar¦2camos:coçar,roçar,laçar¦2ivemos:ater¦4ímos:arguir¦5mos:ferver,quitar,poitar¦5ouvemos:comprazer¦3camos:calçar,forçar,atiçar¦2ímos:ruir,puir¦3mos:atar¦3emos:avir¦6mos:afoitar¦8mos:circuitar¦1usemos:pôr¦4ivemos:abster,suster¦1coitamos:açoitar"
    },
    "secondPlural": {
      "fwd": "usestes:ôr¦coitastes:çoitar¦2stes:xer,ser¦2ivestes:ster¦2castes:inçar¦3stes:iver¦5stes:coitar",
      "both": "5stes:quitar,ltitar,noitar,rreter¦5ivestes:brestar¦5istes:ntrever¦5estes:tervir¦4stes:pitar,gitar,orver,vitar,litar,sitar,enzer,bitar,ritar,citar,mitar,meter,ditar,eitar,caver,rever¦4istes:terver,ntever¦4estes:rovir¦4ivestes:treter¦3castes:emoçar,troçar¦3stes:xtar,rder,eder,ctar,ater,otar,rter,mber,etar,ptar,rtar,lver,utar,atar,eber,over,ltar,star,nder,ntar¦3estes:evir,avir,dvir,nvir¦3ístes:ssuir¦2ístes:cuir,tuir,buir,nuir,luir,ruir¦2stes:far,per,par,uer,oer,bar,ear,car,uar,iar,nar,zar,her,rar,ler,ger,xar,sar,var,har,oar,cer,jar,çar,gar,dar,rer,lar,mer,mar¦2ivestes:bter,nter¦1ouvestes:eaver¦1ístes:air¦1ssestes:izer¦1stes:ir¦usestes:or¦oubestes:aber¦udestes:oder¦izestes:azer",
      "rev": "erer:isestes¦ir:ístes¦1r:iestes¦1azer:rouxestes,rouvestes¦2er:evistes,etivestes¦2r:testes,tastes¦3r:evestes,azestes,ozestes,osestes,exestes¦3çar:bracastes¦4r:vivestes,ervestes¦4çar:trincastes¦5r:ressestes",
      "ex": "fostes:ir¦2estes:vir¦1istes:ver¦3ivestes:estar,deter,reter¦1ivestes:ter¦1estes:dar¦1ouvestes:haver¦2isestes:querer¦2ouxestes:trazer¦2stes:ler,rer¦4stes:dever,meter,jazer,cozer,citar,fitar,ditar,pitar,viver¦4istes:prever¦3istes:rever¦4castes:abraçar¦2castes:coçar,roçar,laçar¦2ivestes:ater¦4ístes:arguir¦5stes:ferver,quitar,poitar¦5ouvestes:comprazer¦3castes:calçar,forçar,atiçar¦2ístes:ruir,puir¦3stes:atar¦3estes:avir¦6stes:afoitar¦8stes:circuitar¦1usestes:pôr¦4ivestes:abster,suster¦1coitastes:açoitar"
    },
    "thirdPlural": {
      "fwd": "useram:ôr¦coitaram:çoitar¦2iveram:ster¦2caram:inçar¦3am:xer,ser¦4am:iver",
      "both": "5am:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iveram:brestar,ntreter¦5iram:ntrever¦4am:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4iram:terver¦4ou:saguar¦4eram:rovir¦3caram:emoçar,troçar,braçar¦3am:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3eram:avir,evir,dvir,nvir¦3ouveram:mprazer¦3iram:tever¦2iveram:bter,nter¦1íram:uir,air¦1ouveram:eaver¦1sseram:izer¦useram:or¦ouberam:aber¦uderam:oder¦izeram:azer",
      "rev": "3:çaram,teram,taram,uiram¦4:everam,azeram,ozeram,oseram,exeram¦5:viveram,erveram,esseram¦erer:iseram¦1r:ieram¦1azer:rouxeram¦2er:eviram,etiveram¦3er:bstiveram,ustiveram¦4çar:trincaram",
      "ex": "foram:ir¦2eram:vir¦1iram:ver¦3iveram:estar,deter,reter¦1iveram:ter¦1eram:dar¦1ouveram:haver¦2iseram:querer¦2ouxeram:trazer¦3am:rir,ler,rer¦7eram:intervir¦5am:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7am:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4iram:prever¦6am:servir,traçar,ferver,poitar¦3iram:rever¦2caram:coçar,roçar,laçar¦2iveram:ater¦3caram:calçar,forçar,atiçar¦8am:derreter,saltitar,engraçar,morraçar¦4am:atar,içar¦10am:despedaçar,escorraçar,abiscoitar¦3eram:avir¦9am:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12am:desembaraçar¦1useram:pôr¦1coitaram:açoitar"
    }
  },
  "pluperfect": {
    "first": {
      "fwd": "a:¦usera:ôr¦coitara:çoitar¦2ivera:ster¦2cara:inçar",
      "both": "5ivera:brestar¦5ira:ntrever¦5era:tervir¦4cara:stroçar¦4ira:terver¦4era:rovir¦4ivera:treter¦3cara:emoçar,braçar¦3izera:sprazer¦3era:avir,evir,nvir¦3ouvera:mprazer¦3ira:tever¦2íra:cuir,buir,tuir,nuir,luir,ruir,suir¦2ivera:bter,nter¦1izera:fazer¦1ouvera:eaver¦1íra:air¦1ssera:izer¦usera:or¦oubera:aber¦udera:oder",
      "rev": "3:mara,tira,dara,lara,rera,mira,gira,dira,gara,rira,çara,uira,jara,cera,eara,rara,sara,xara,hara,lera,tera,tara,oera,hera,zara,lira,nara,oara,para,iara,uara,zira,nira,pira,vara,mera,uera,bara,pera,gera,bira,fara,hira¦4:ndera,evera,ncara,ebera,ssira,overa,avera,rcara,lvera,icara,ecara,scara,ucara,edera,rdera,lcara,exera,rvera,uvira,osera¦5:locara,vivera,arcira,tacara,vocara,hocara,focara,lacara,pocara,bocara,pacara,hacara,essera,sacara,bacara¦azer:izera,ouvera/prazera¦erer:isera¦ir:íra¦1r:iera¦1azer:rouxera,rouvera¦2er:evira,etivera¦3er:bstivera,ustivera",
      "ex": "fora:ir¦1izera:fazer¦2era:vir¦1ira:ver¦3ivera:estar,deter,reter¦1ivera:ter¦1era:dar¦1ouvera:haver¦2isera:querer¦2ouxera:trazer¦4ira:prever¦3ira:rever¦4era:advir¦3ouvera:aprazer¦2cara:coçar,roçar,laçar¦2ivera:ater¦4íra:arguir¦2ouvera/prazera:prazer¦3cara:calçar,forçar,atiçar¦2íra:ruir,puir¦3era:avir¦1usera:pôr¦3a:rir,ler,rer¦5a:viver,tocar,focar,jazer,cozer,tacar,sacar,locar,socar¦6a:servir,trocar,lamber,benzer,brocar¦10a:reciprocar¦7a:atracar,xerocar,retocar,entocar¦1coitara:açoitar¦7cara:destrinçar¦8a:derrocar¦9a:atarracar,desservir,esburacar"
    },
    "second": {
      "fwd": "as:¦useras:ôr¦coitaras:çoitar¦2iveras:ster¦2caras:inçar",
      "both": "5iveras:brestar¦5iras:ntrever¦5eras:tervir¦4caras:stroçar¦4iras:terver¦4am:doer¦4eras:rovir¦4iveras:treter¦3caras:emoçar,braçar¦3izeras:sprazer¦3eras:avir,evir,nvir¦3ouveras:mprazer¦3iras:tever¦2íras:cuir,buir,tuir,nuir,luir,ruir,suir¦2iveras:bter,nter¦1izeras:fazer¦1ouveras:eaver¦1íras:air¦1sseras:izer¦useras:or¦ouberas:aber¦uderas:oder",
      "rev": "2:aram,iram¦3:maras,tiras,daras,laras,reras,miras,giras,diras,garas,riras,çaras,uiras,jaras,ceras,earas,raras,saras,xaras,haras,leras,teras,taras,oeram,heras,zaras,liras,naras,oaras,paras,iaras,uaras,ziras,niras,piras,varas,meras,ueras,baras,peras,geras,biras,oeras,faras,hiras,teram¦4:nderas,everas,ncaras,eberas,ssiras,overas,averas,rcaras,lveras,icaras,ecaras,scaras,ucaras,ederas,rderas,lcaras,exeras,rveras,uviras,oseras¦5:locaras,viveras,arciras,tacaras,vocaras,hocaras,focaras,lacaras,pocaras,bocaras,pacaras,hacaras,esseras,sacaras,bacaras¦azer:izeras,ouveram,ouveram/prazeram¦erer:iseras¦ir:íras¦1r:ieras¦1azer:rouxeras¦2er:eviras,etiveras¦3er:bstiveras,ustiveras",
      "ex": "foras:ir¦1izeras:fazer¦2eras:vir¦1iras:ver¦3iveras:estar,deter,reter¦1iveras:ter¦1eras:dar¦1ouveras:haver¦2iseras:querer¦2ouxeras:trazer¦4am:doer¦4iras:prever¦3iras:rever¦4eras:advir¦3ouveram:aprazer¦2caras:coçar,roçar,laçar¦2iveras:ater¦4íras:arguir¦2ouveram/prazeram:prazer¦3caras:calçar,forçar,atiçar¦7am:grassar¦2íras:ruir,puir¦9am:concernir¦5am:urgir,later¦3eras:avir¦10am:obstringir¦1useras:pôr¦3as:rir,ler,rer¦5as:viver,tocar,focar,jazer,cozer,tacar,sacar,locar,socar¦6as:servir,trocar,lamber,benzer,brocar¦10as:reciprocar¦7as:atracar,xerocar,retocar,entocar¦1coitaras:açoitar¦7caras:destrinçar¦8as:derrocar¦9as:atarracar,desservir,esburacar"
    },
    "third": {
      "fwd": "usera:ôr¦coitara:çoitar¦2ivera:ster¦2cara:inçar¦3a:xer,ser¦4a:iver",
      "both": "5a:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5ivera:brestar,ntreter¦5ira:ntrever¦4a:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4ira:terver¦4era:rovir¦3cara:emoçar,troçar,braçar¦3a:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3era:avir,evir,dvir,nvir¦3ouvera:mprazer¦3ira:tever¦2ivera:bter,nter¦1íra:uir,air¦1ouvera:eaver¦1ssera:izer¦usera:or¦oubera:aber¦udera:oder¦izera:azer",
      "rev": "3:çara,tera,tara,uira¦4:evera,azera,ozera,osera,exera¦5:vivera,ervera,essera¦erer:isera¦1r:iera¦1azer:rouxera¦2er:evira,etivera¦3er:bstivera,ustivera¦4çar:trincara",
      "ex": "fora:ir¦2era:vir¦1ira:ver¦3ivera:estar,deter,reter¦1ivera:ter¦1era:dar¦1ouvera:haver¦2isera:querer¦2ouxera:trazer¦3a:rir,ler,rer¦7era:intervir¦5a:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7a:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4ira:prever¦6a:servir,traçar,ferver,poitar¦3ira:rever¦2cara:coçar,roçar,laçar¦2ivera:ater¦3cara:calçar,forçar,atiçar¦8a:derreter,saltitar,engraçar,morraçar¦4a:atar,içar¦10a:despedaçar,escorraçar,abiscoitar¦3era:avir¦9a:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12a:desembaraçar¦1usera:pôr¦1coitara:açoitar"
    },
    "firstPlural": {
      "fwd": "uséramos:ôr¦coitáramos:çoitar¦2ivéramos:ster¦2cáramos:inçar",
      "both": "5ivéramos:brestar¦5íramos:ntrever¦5éramos:tervir¦4íramos:terver¦4êramos:rreter¦4ouvéramos:omprazer¦4éramos:rovir¦4ivéramos:treter¦3cáramos:troçar,braçar¦3éramos:avir,evir,nvir¦3íramos:tever¦3êramos:meter¦3ivéramos:onter,anter¦2êramos:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivéramos:bter¦1êramos:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvéramos:eaver¦1sséramos:izer¦uséramos:or¦oubéramos:aber¦áramos:ar¦íramos:ir¦udéramos:oder¦izéramos:azer",
      "rev": "erer:iséramos¦er:êramos¦1r:iéramos¦1azer:rouxéramos¦2er:evíramos,etivéramos¦2çar:mocáramos¦3er:bstivéramos,ustivéramos¦4çar:trincáramos",
      "ex": "fôramos:ir¦2éramos:vir¦1íramos:ver¦3ivéramos:estar,deter,reter¦1ivéramos:ter¦1éramos:dar¦1ouvéramos:haver¦2iséramos:querer¦2ouxéramos:trazer¦1êramos:ler,rer¦4íramos:prever¦3íramos:rever¦4éramos:advir¦3êramos:meter,jazer¦2cáramos:coçar,roçar,laçar¦2ivéramos:ater¦3cáramos:calçar,forçar,atiçar¦3éramos:avir¦4cáramos:remoçar¦1uséramos:pôr¦1coitáramos:açoitar"
    },
    "secondPlural": {
      "fwd": "uséreis:ôr¦coitáreis:çoitar¦2ivéreis:ster¦2cáreis:inçar",
      "both": "5ivéreis:brestar¦5íreis:ntrever¦5éreis:tervir¦4íreis:terver¦4êreis:rreter¦4ouvéreis:omprazer¦4éreis:rovir¦4ivéreis:treter¦3cáreis:troçar,braçar¦3éreis:avir,evir,nvir¦3íreis:tever¦3êreis:meter¦3ivéreis:onter,anter¦2êreis:nzer,rter,ozer,mber,rder,eder,ater,eber,nder¦2ivéreis:bter¦1êreis:xer,ser,per,uer,ger,oer,her,ler,cer,ver,rer,mer¦1ouvéreis:eaver¦1sséreis:izer¦uséreis:or¦oubéreis:aber¦áreis:ar¦íreis:ir¦udéreis:oder¦izéreis:azer",
      "rev": "erer:iséreis¦er:êreis¦1r:iéreis¦1azer:rouxéreis¦2er:evíreis,etivéreis¦2çar:mocáreis¦3er:bstivéreis,ustivéreis¦4çar:trincáreis",
      "ex": "fôreis:ir¦2éreis:vir¦1íreis:ver¦3ivéreis:estar,deter,reter¦1ivéreis:ter¦1éreis:dar¦1ouvéreis:haver¦2iséreis:querer¦2ouxéreis:trazer¦1êreis:ler,rer¦4íreis:prever¦3íreis:rever¦4éreis:advir¦3êreis:meter,jazer¦2cáreis:coçar,roçar,laçar¦2ivéreis:ater¦3cáreis:calçar,forçar,atiçar¦3éreis:avir¦4cáreis:remoçar¦1uséreis:pôr¦1coitáreis:açoitar"
    },
    "thirdPlural": {
      "fwd": "useram:ôr¦coitaram:çoitar¦2iveram:ster¦2caram:inçar¦3am:xer,ser¦4am:iver",
      "both": "5am:poçar,naçar,haçar,maçar,ençar,paçar,bitar,gaçar,laçar,baçar,gitar,oaçar,doçar,pitar,uitar,unçar,orver,citar,ritar,litar,meter,nguir,mitar,vitar,ançar,sitar,ditar,eitar,caver,eguir,rever¦5iveram:brestar,ntreter¦5iram:ntrever¦4am:xtar,eçar,nzer,uçar,içar,quir,ctar,rçar,lver,rter,mber,otar,etar,ptar,rtar,star,utar,atar,eder,over,ater,ltar,rder,eber,uvir,nder,ntar¦4iram:terver¦4eram:rovir¦3caram:emoçar,troçar,braçar¦3am:hir,far,ler,cir,per,zir,uer,mer,ger,oer,zar,pir,nir,her,lir,iar,nar,cer,rir,bar,uar,par,var,sir,har,xar,bir,ear,oar,jar,rar,sar,gar,car,dir,gir,mir,rer,lar,dar,tir,mar¦3eram:avir,evir,dvir,nvir¦3ouveram:mprazer¦3iram:tever¦2iveram:bter,nter¦1íram:uir,air¦1ouveram:eaver¦1sseram:izer¦useram:or¦ouberam:aber¦uderam:oder¦izeram:azer",
      "rev": "3:çaram,teram,taram,uiram¦4:everam,azeram,ozeram,oseram,exeram¦5:viveram,erveram,esseram¦erer:iseram¦1r:ieram¦1azer:rouxeram¦2er:eviram,etiveram¦3er:bstiveram,ustiveram¦4çar:trincaram",
      "ex": "foram:ir¦2eram:vir¦1iram:ver¦3iveram:estar,deter,reter¦1iveram:ter¦1eram:dar¦1ouveram:haver¦2iseram:querer¦2ouxeram:trazer¦3am:rir,ler,rer¦7eram:intervir¦5am:dever,caçar,meter,jazer,cozer,citar,fitar,alçar,ditar,maçar,pitar,inçar,viver¦7am:almoçar,ameaçar,realçar,esboçar,achoçar,afoitar¦4iram:prever¦6am:servir,traçar,ferver,poitar¦3iram:rever¦2caram:coçar,roçar,laçar¦2iveram:ater¦3caram:calçar,forçar,atiçar¦8am:derreter,saltitar,engraçar,morraçar¦4am:atar,içar¦10am:despedaçar,escorraçar,abiscoitar¦3eram:avir¦9am:descalçar,redarguir,espicaçar,pernoitar,embaraçar,amordaçar,desgraçar,alvoroçar,espedaçar,congraçar,desservir¦12am:desembaraçar¦1useram:pôr¦1coitaram:açoitar"
    }
  },
  "presentTense": {
    "first": {
      "fwd": "o:ar,uer¦onho:ôr¦urmo:ormir¦jo:gir,ger¦igo:eguir¦ço:cer,cir¦isto:estir¦iro:erir¦ito:etir¦ino:enir¦igro:egrir¦urto:ortir¦usco:oscar¦1sso:oder¦1o:mer,rer,xer,her,per,ser¦1go:izer¦1ço:uvir¦1ulo:golir¦2o:air,nder,iver,ubir,prir,umir,over,idir,itir,utir,eder,ndir,nuir,nguir,inir,odir,udir,ater,rter,trir,imir,ulir,upir,adir,nzer,tuir,roer,mbir,nzir,plir,irir,nhir¦2co:erder¦2ho:aler¦2ço:pedir¦3o:artir,rrir,istir,antir,order¦3io:eler¦4o:rreter",
      "both": "5:rassar¦5jo:terver¦5ou:brestar¦5e:ncernir¦5es:scernir¦5o:mprazer¦5nho:treter¦4es:randir,culpir,olorir¦4io:screr¦4enho:esavir,tervir¦4o:epolir,crever¦4jo:tever¦4mos:caver,eaver¦4iro:equerer¦3o:nibir,orver,xibir,rguir,amber,meter,ssuir¦3ilo:ompelir¦3mos:emir,alir¦3es:arpir,aurir,rquir,molir,bolir¦3eio:endiar,mediar¦3nho:ster,nter¦3co:braçar¦3enho:rovir¦2es:rdir,amir,anir¦2ilo:xpelir¦2enho:evir,dvir,nvir¦2o:ruir,lver,buir,uzir,luir,eber¦2eio:nsiar¦2ço:fazer¦1ízo:aizar,uizar,eizar¦1úço:iuçar¦1ísco:aiscar¦1ói:doer¦1íno:uinar¦1irjo:vergir¦1ílio:biliar¦1iro:arir¦1íbo:oibir¦1ido:redir¦1úno:eunir¦1io:ear¦1nho:or¦coito:çoitar¦ólego:olegar¦irzo:erzir¦ínquo:inquir¦águo:aguar¦ispo:espir¦ubro:obrir¦équo:equar¦irto:ertir¦usso:ossir¦into:entir",
      "rev": "oer:ói,óis¦ervir:irvo¦ir:es,e¦r:mos¦udar:údo¦1ar:tou,oo,xo,fo¦1ber:aibo¦1eguir:sigo¦1cer:eço,sço¦1erir:firo,diro,giro,siro¦1enir:vino¦1er:z¦1egrir:nigro¦1ir:venho¦2ar:alo,nco,ogo,nso,amo,tro,lto,iso,cho,aro,oco,rso,oro,ero,uro,oço,abo,ago,izo,lgo,aso,rno,vio,rco,rio,pio,rdo,uco,ico,nro,ano,oio,ono,rmo,uso,fio,uio,uvo,cio,oto,rbo,eco,lpo,ezo,rgo,ugo,gio,dro,cto,elo,ngo,mio,lso,dio,eso,eno,pto,avo,iço,apo,cuo,gno,sgo,clo,smo,opo,ldo,tio,bio,sio,epo,zio,ipo,lmo,lço,blo,ojo,nio,juo,cro,duo,lro,vro,xto,hio,flo,rlo¦2gir:rijo,eajo,dijo,injo,lijo,erjo,oajo,urjo,unjo¦2cer:enço¦2etir:epito,flito,mpito¦2r:tenho,uis¦2olir:ngulo¦2iar:edeio¦2zer:digo¦2estir:nvisto¦2çar:alco¦2er:oso,moo¦3ar:tudo,osto,anço,iajo,alho,asso,sejo,onto,inho,judo,ento,eito,anto,rego,rito,unto,gino,cupo,impo,dito,ilho,anho,rumo,uido,oubo,esso,esto,rato,orto,nimo,asto,eimo,buzo,obro,vido,tumo,rado,erro,mino,leto,rigo,etuo,esco,rolo,novo,piro,urro,miro,usto,mulo,culo,raço,alio,modo,egro,huto,arro,ailo,ligo,sego,rubo,pejo,plio,tato,opro,cejo,ruto,tino,ulho,taco,iguo,puto,feto,vego,eaço,ruço,ruzo,tivo,elho,ilio,gato,sito,maio,irro,mejo,uivo,cito,timo,isso,mbro,uedo,aspo,cino,levo,uito,ngro,rivo,lino,pedo,nguo,ieto,isco,ibro,nejo,uilo,colo,lato,daço,tigo,iedo,ombo,asco,ifro,redo,bsto,tuno,zijo,utuo,dulo,urvo,tulo,sato,pumo,nulo,guço,zino,agro,luço,mato,cado,cato,oaço,uejo,ulco,cilo,rejo,pego,pido,vito,gito,gemo,dejo,rino,bolo,pino,viro,solo,hego,ampo,baço,jeto,laço,julo,pujo¦3er:endo,hovo,ofro,bato,movo,ompo,cedo,vivo,valho,enzo,rroo,remo,mexo¦3ger:otejo¦3ir:rimo,uiro,uspo,vado,sumo,ludo,tupo,dimo,uado,umbo,anzo,luto,sido¦3r:evejo,raio,caio¦3cer:xerço,torço¦3cir:sarço¦4r:orrio,ssaio¦4ar:ompro,omeço,tinuo,uisto,oximo,scovo,senho,heiro,omito,ssino,stejo,farto,servo,perto,berto,egulo,farço,forço,ilito,lebro,mendo,lerto,ecuto,nsaio,abito,gonho,preto,imito,penho,ferto,gunço,rindo,chaço,onsto,teiro,carto,neiro,etomo,nvejo,mpato,certo,lpito,icido,ontuo,entuo,imilo,ngajo,chilo,migro,ipito,bituo,inquo,tenuo,rrujo,ultuo,cundo,imido,mando,traco,efuto,banjo,izimo,placo,ncimo,elido,denho,raudo,fusco,icaço,apito,rosso,serto,ltejo¦4ir:sisto,umpro,xisto,ecido,rmito,ranto,minuo,tituo,efino,plodo,laudo,pando,dmito,smito,cindo,emito,ncido,apulo,implo,rcuto,mbuto,ncuto,runho¦4er:pondo,corro,condo,colho,verto¦4dir:espeço¦4gir:terajo¦4ger:branjo,tranjo¦5ir:iscuto,eparto,ifundo¦5uir:stingo,xtingo¦5ar:rranjo,mprovo,templo,eprovo,ropeço,corajo,dereço,emunho,arreto,svendo,nipulo,ecreto,ofundo,erendo,lucido,uiteto,solido,lmorço,ceituo,nsinuo,bebedo,stupro,artejo,essumo,icerço¦5er:eencho,erreto,sprovo",
      "ex": "4:prazer¦5:aprazer¦vou:ir¦águo:aguar¦1ou:ser,dar¦2ço:fazer,pedir,medir,ouvir¦1enho:vir¦2jo:ver,fugir,reger,viger,rugir,mugir¦3ou:estar¦2nho:ter¦1ei:haver,saber¦3go:trazer¦2o:rir,unir,roer,moer,poer,amar,usar,suar,orar,atar,fiar,miar,irar,arar,içar,piar,erar,elar,liar,azar¦2io:ler¦2ibo:caber¦3o:abrir,dever,punir,meter,jazer,cozer,arder,comer,sair,andar,viver,cair,pular,subir,levar,olhar,mexer,bater,sumir,pegar,nadar,tomar,mudar,ligar,tirar,ceder,feder,matar,virar,lutar,errar,negar,lidar,caçar,mover,gemer,temer,fumar,erguer,assar,colar,gozar,atuar,regar,rolar,sujar,girar,rodar,citar,nevar,somar,bulir,uivar,mirar,catar,podar,vaiar,remar,tacar,mimar,fuçar,fitar,cegar,pirar,orçar,sacar,vazar,aliar,anuir,urrar,ditar,mijar,legar,domar,rimar,vetar,untar,bolar,vedar,sedar,raiar,ninar,rumar,sovar,pilar¦3io:crer¦5jo:prover,prever,reeleger¦1ói:doer¦1irvo:servir¦4jo:rever¦2eio:odiar¦4nho:deter,reter,obter¦4o:curtir,cuspir,ferver,remoer,partir,querer,correr,mandar,morrer,sonhar,buscar,encher,beijar,salvar,varrer,pintar,colher,emitir,morder,provar,suprir,nutrir,acudir,poupar,molhar,imitar,atirar,chupar,eximir,omitir,peidar,alegar,tolher,reinar,fartar,tatuar,findar,furtar,fundir,apitar,trajar,forrar,verter,manjar,fossar,intuir,situar,lograr,rondar,listar,forjar,sondar,mondar,migrar,terçar,folhar,borrar,torrar,lindar¦3eio:mediar¦3es:latir,ungir,munir,delir¦5mos:florir¦2údo:saudar¦2co:coçar,roçar,laçar¦3nho:ater¦3co:calçar,forçar,atiçar,perder¦1óis:soer¦3s:ruir,puir¦5es:repelir,impelir¦7jo:entrever¦3e:urgir¦2enho:avir¦3mos:adir¦4s:fruir¦2sso:poder¦1onho:pôr¦2go:dizer¦1urmo:dormir¦1jo:agir¦5o:dividir,ensinar,escutar,quebrar,retirar,treinar,avistar,aprovar,sacudir,agendar,esvair,validar,inundar,apartar,pelejar,afundar,colidir,latejar,vegetar,aleijar,velejar,delegar,espetar¦1igo:seguir¦3ho:valer¦1isto:vestir¦1iro:ferir¦7o:confundir,compartir¦3jo:exigir,eleger,ranger,tanger¦4ço:impedir,expedir¦3ço:torcer¦6o:combinar,trovejar,perfumar,mendigar,registar¦9o:entrevistar¦4iro:preterir¦1urto:sortir¦3isto:revestir¦4io:reler¦1usco:moscar"
    },
    "second": {
      "fwd": "ões:ôr¦ines:enir¦oles:ulir¦urtes:ortir¦uscas:oscar¦1es:gir,sir,cir¦1óis:roer¦2es:idir,etir,ndir,odir,mbir,nzir¦3es:ertir",
      "both": "5ás:brestar¦5em:ncernir¦5e:scernir¦5m:rassar¦5óis:onstruir¦4ês:terver,trever¦4e:randir,olorir¦4es:xpelir,epolir,esumir,efinir,ssumir,ngolir¦4eias:cendiar¦4óis:estruir¦4is:caver,eaver¦4éns:treter¦3e:aurir,rquir,molir,bolir¦3es:ludir,nibir,xibir,audir,nguir,espir,pedir,eguir,artir¦3m:doer¦3ês:tever¦3eias:mediar¦3cas:braçar¦3éns:anter¦2es:nhir,irir,plir,adir,imir,trir,arir,uzir,utir,itir,erir,stir,ntir,prir,brir,uvir,rmir¦2e:rdir,rpir,lpir,anir,atir¦2ês:eler,crer¦2omes:bsumir,nsumir¦2éns:ster,bter¦2eias:nsiar¦1ízas:aizar,uizar,eizar¦1úças:iuçar¦1íscas:aiscar¦1óis:moer¦1ínas:uinar¦1ílias:biliar¦1odes:cudir¦1íbes:oibir¦1ides:redir¦1únes:eunir¦1ias:ear¦1éns:vir¦coitas:çoitar¦ólegas:olegar¦irzes:erzir¦ínques:inquir¦igres:egrir¦opes:upir¦águas:aguar¦ospes:uspir¦équas:equar¦obes:ubir¦ões:or¦s:r",
      "rev": "er:ês¦ugir:oges¦olir:ules¦udar:údas¦oer:ói¦ir:e¦1ar:tás¦1er:téns¦1enir:vines¦1igir:reges¦1ir:gem¦2ir:sses,rges,unes,ages,uges,eles¦2r:oem,zem,ui¦2iar:edeias¦2oer:rróis¦2ulir:apoles¦3ir:riges,inges,cides,petes,undes,xiges,lodes,indes,arces,diges,sides,umbes,anzes,liges¦4ir:ivides,fletes,pandes,olides¦5ir:ivertes,dvertes",
      "ex": "3:ruir,puir¦4:fruir¦vais:ir¦és:ser¦águas:aguar¦1ens:vir¦1ês:ver,ler¦3ás:estar¦2ns:ter¦1ás:dar,haver¦3es:pedir,medir,punir¦2ês:crer¦1oges:fugir¦1omes:sumir¦4ês:prover,prever¦3m:doer¦4éns:conter¦4es:servir,curtir,pungir¦3ês:rever¦2eias:odiar¦3éns:deter,reter¦1ules:polir¦2es:unir,agir¦1óis:roer,moer¦3eias:mediar¦6m:aprazer¦2údas:saudar¦2cas:coçar,roçar,laçar¦2éns:ater¦2eges:frigir¦5m:prazer¦3cas:calçar,forçar,atiçar¦1ói:soer¦5e:repelir,impelir¦6es:compelir¦3e:ungir,munir,delir¦3em:urgir¦4e:bramir¦1ões:pôr¦1oles:bulir¦1urtes:sortir¦1uscas:moscar"
    },
    "third": {
      "fwd": "á:aver¦õe:ôr¦ine:enir¦ole:ulir¦urte:ortir¦usca:oscar¦1e:gir,sir,cir¦1ói:roer¦2e:idir,etir,ndir,inir,odir,mbir,nzir¦3e:ertir,urtir",
      "both": "2:izer,uzir,erer,azer¦5á:brestar¦5ê:ntrever¦5mos:epelir¦5ói:onstruir¦4ê:terver¦4mos:ernir,rquir,molir,bolir¦4e:epolir,esumir,ssumir,ngolir¦4ói:estruir¦4ém:treter¦3mos:rdir,amir,rpir,lpir,urir,anir,orir¦3e:ludir,pedir,xibir,audir,nguir,espir,eguir,artir¦3ê:tever¦3eia:mediar¦3ca:braçar¦3ém:anter¦2e:nhir,irir,plir,adir,imir,trir,arir,utir,itir,erir,stir,ntir,prir,brir,uvir,rmir¦2ê:eler,crer¦2ome:bsumir,nsumir¦2eia:ndiar,nsiar¦2ém:ster,bter¦1íza:aizar,uizar,eizar¦1úça:iuçar¦1ísca:aiscar¦1ói:moer¦1ína:uinar¦1ília:biliar¦1ode:cudir¦1íbe:oibir¦1ide:redir¦1úne:eunir¦1ia:ear¦1ém:vir¦coita:çoitar¦ólega:olegar¦irze:erzir¦ínque:inquir¦igre:egrir¦ope:upir¦água:aguar¦ospe:uspir¦équa:equar¦obe:ubir¦õe:or¦:r",
      "rev": "er:ê¦ugir:oge¦olir:ule¦udar:úda¦ir:ímos¦1ar:tá¦1er:tém¦1enir:vine¦1r:imos,emos¦1igir:rege¦2ir:sse,rge,une,age,uge,ele,ibe¦2iar:edeia¦2çar:alca¦2oer:rrói¦2ulir:apole¦3ir:rige,inge,cide,pete,unde,xige,fine,lode,inde,arce,dige,side,umbe,anze,lige¦4ir:ivide,flete,pande,olide¦5ir:iverte,dverte",
      "ex": "vai:ir¦é:ser¦água:aguar¦1em:vir¦1ê:ver,ler¦3á:estar¦2m:ter¦1á:dar,haver¦3e:pedir,medir,punir¦2ê:crer¦1oge:fugir¦1ome:sumir¦4ê:prover,prever¦4ém:conter¦4e:servir,inibir,curtir,pungir¦3ê:rever¦2eia:odiar¦3ém:deter,reter¦1ule:polir¦2e:unir,agir¦1ói:roer,moer¦3eia:mediar¦4mos:latir,ungir,munir,delir¦2úda:saudar¦2ca:coçar,roçar,laçar¦2ém:ater¦2ege:frigir¦3ca:calçar,forçar,atiçar¦3mos:soer¦2ímos:ruir,puir¦5e:expelir¦6e:compelir¦6mos:impelir,brandir¦3ímos:fruir¦1õe:pôr¦1ole:bulir¦1urte:sortir¦1usca:moscar"
    },
    "firstPlural": {
      "fwd": "2camos:tiçar",
      "both": "5s:randir,culpir,emolir¦4s:ernir,rquir,bolir¦3s:rdir,amir,rpir,urir,atir,orir¦3camos:braçar¦2ímos:buir,tuir,nuir,luir,ruir,suir¦1ímos:air¦coitamos:çoitar¦mos:r",
      "rev": "ir:ímos,ís¦1r:is,eis¦2çar:alcamos",
      "ex": "vamos:ir¦1omos:ser,pôr¦4s:banir,ungir,munir,delir¦2camos:coçar,roçar,laçar¦4ímos:arguir¦3camos:calçar,forçar,atiçar¦3is:soer¦2ís:ruir,puir¦6s:repelir,impelir¦3ís:fruir"
    },
    "secondPlural": {
      "fwd": "ondes:ôr¦2cais:tiçar",
      "both": "5des:terver,trever¦5s:xpelir,epolir,ngolir¦5ndes:treter¦4em:randir,epelir¦4s:nquir,nguir,eunir,eguir¦4des:tever¦4ís:ossuir¦3des:eler,crer,rrir¦3s:plir,upir,ulir,enir,inir,spir,ssir¦3em:rquir¦3ís:rguir¦3ndes:ster,bter,nter¦3cais:braçar¦2s:hir,cir,bir,zir,rir,dir,gir,mir,tir¦2em:rdir,amir,rnir,rpir,lpir,urir,anir,orir¦2ís:buir,tuir,nuir,ruir,luir¦2ndes:vir¦1ndes:or¦1ís:air¦coitais:çoitar¦is:r",
      "rev": "er:ois¦r:ndes¦ir:em¦1r:edes,ides¦2r:vis,nis,oem¦2çar:alcais¦3r:olis,elis",
      "ex": "1des:ir¦1ois:ser¦2ndes:vir,ter¦2des:ver,rir,ler¦4s:ouvir,polir,punir¦3des:crer¦5des:prover,prever¦5s:servir¦4des:rever¦4ndes:deter,reter¦4em:abolir¦3s:unir¦5em:demolir,impelir¦3em:latir,ungir,munir,fruir,delir¦2cais:coçar,roçar,laçar¦3ndes:ater¦3cais:calçar,forçar,atiçar¦3m:soer¦2em:ruir,puir¦7s:compelir¦1ondes:pôr"
    },
    "thirdPlural": {
      "fwd": "ão:aver¦õem:ôr¦em:ir¦inem:enir¦olem:ulir¦urtem:ortir¦uscam:oscar",
      "both": "5ão:brestar¦5em:trever¦5oem:onstruir¦4em:tever¦4oem:estruir¦4êm:treter,tervir¦3em:eler,crer,rrir¦3eiam:mediar¦3êm:rovir¦2ízam:juizar¦2omem:bsumir,nsumir¦2êm:ster,avir,evir,dvir,bter,nvir,nter¦2eiam:ndiar,nsiar¦1ízam:aizar,eizar¦1úçam:iuçar¦1íscam:aiscar¦1ínam:uinar¦1íliam:biliar¦1odem:cudir¦1íbem:oibir¦1idem:redir¦1únem:eunir¦1iam:ear¦coitam:çoitar¦ólegam:olegar¦irzem:erzir¦ínquem:inquir¦igrem:egrir¦opem:upir¦águam:aguar¦ospem:uspir¦équam:equar¦obem:ubir¦õem:or¦m:r",
      "rev": "ugir:ogem¦olir:ulem¦udar:údam¦1r:eem¦1ir:aem,vêm¦1er:têm¦1enir:vinem¦1igir:regem¦2ar:stão¦2ir:rmem,uvem,brem,stem,prem,ssem,suem,item,luem,utem,rgem,ntem,uzem,nuem,buem,umem,tuem,agem,unem,udem,ruem,trem,imem,ugem,elem,adem,ibem,plem,irem,nhem¦2çar:alcam¦2ulir:apolem¦3ir:artem,rigem,videm,ingem,ferem,cidem,petem,gerem,undem,xigem,eguem,finem,serem,andem,arcem,digem,sidem,pedem,anzem,umbem,ungem¦3çar:bracam¦4ir:fletem,ngolem,inguem,cindem,epolem,fligem,olidem,plodem¦5ir:ivertem,dvertem,reterem,darguem",
      "ex": "vão:ir¦águam:aguar¦1ão:ser,dar,haver¦1êm:vir,ter¦2em:ver,rir,ler,agir,unir¦3ão:estar¦3em:crer,pedir,medir,ferir,parir,gerir¦1ogem:fugir¦1omem:sumir¦5em:prover,prever¦4em:rever,servir,aderir,curtir,despir,arguir¦2eiam:odiar¦3êm:deter,reter¦1ulem:polir¦4cam:abraçar¦3eiam:mediar¦2údam:saudar¦2cam:coçar,roçar,laçar¦2êm:ater,avir¦2egem:frigir¦3cam:calçar,forçar,atiçar¦7em:interver¦1õem:pôr¦1olem:bulir¦1urtem:sortir¦1uscam:moscar"
    }
  },
  "infinitivo": {
    "first": {
      "fwd": ":¦2car:tiçar",
      "both": "3car:braçar¦coitar:çoitar",
      "rev": "2:er,ir,ôr,or¦3:mar,dar,lar,gar,çar,rar,oar,har,sar,jar,par,bar,zar,nar,iar,uar,var,ear,xar,far¦4:star,ntar,icar,ocar,rcar,atar,utar,ltar,ptar,etar,otar,scar,rtar,ncar,ecar,ctar,ucar,xtar¦5:eitar,ditar,vitar,sitar,tacar,litar,ritar,mitar,citar,pitar,lacar,gitar¦2çar:alcar",
      "ex": "2:ir¦3:dar¦4:atar¦5:citar,tacar,fitar,sacar,ditar¦6:quitar¦7:habitar,atracar¦8:inculcar¦2car:coçar,roçar,laçar¦3car:calçar,forçar,atiçar"
    },
    "second": {
      "fwd": "es:",
      "both": "4em:doer¦3cares:braçar¦2íres:nuir,tuir,buir,luir,ruir,suir¦1íres:air¦coitares:çoitar",
      "rev": "2:eres,ires,ores¦3:mares,dares,lares,gares,çares,rares,oares,hares,sares,jares,pares,bares,zares,nares,iares,uares,vares,eares,xares,fares¦4:stares,ntares,icares,ocares,rcares,atares,utares,ltares,ptares,etares,otares,scares,rtares,ncares,ecares,ctares,ucares,xtares¦5:eitares,ditares,vitares,sitares,tacares,litares,ritares,mitares,citares,pitares,lacares,gitares¦:em¦ir:íres¦2çar:alcares",
      "ex": "1ores:pôr¦4em:doer¦7em:aprazer,grassar¦2cares:coçar,roçar,laçar¦4íres:arguir¦6em:prazer¦3cares:calçar,forçar,atiçar¦2íres:ruir,puir¦9em:concernir¦5em:urgir¦2es:ir¦3es:dar¦5es:citar,tacar,fitar,sacar,ditar¦7es:habitar,atracar¦4es:atar¦6es:quitar¦8es:inculcar"
    },
    "third": {
      "fwd": ":¦2car:tiçar",
      "both": "3car:braçar¦coitar:çoitar",
      "rev": "2:er,ir,ôr,or¦3:mar,dar,lar,gar,çar,rar,oar,har,sar,jar,par,bar,zar,nar,iar,uar,var,ear,xar,far¦4:star,ntar,icar,ocar,rcar,atar,utar,ltar,ptar,etar,otar,scar,rtar,ncar,ecar,ctar,ucar,xtar¦5:eitar,ditar,vitar,sitar,tacar,litar,ritar,mitar,citar,pitar,lacar,gitar¦2çar:alcar",
      "ex": "2:ir¦3:dar¦4:atar¦5:citar,tacar,fitar,sacar,ditar¦6:quitar¦7:habitar,atracar¦8:inculcar¦2car:coçar,roçar,laçar¦3car:calçar,forçar,atiçar"
    },
    "firstPlural": {
      "fwd": "mos:¦2carmos:tiçar",
      "both": "3carmos:braçar¦coitarmos:çoitar",
      "rev": "2:ermos,irmos,ormos¦3:marmos,darmos,larmos,garmos,çarmos,rarmos,oarmos,harmos,sarmos,jarmos,parmos,barmos,zarmos,narmos,iarmos,uarmos,varmos,earmos,xarmos,farmos¦4:starmos,ntarmos,icarmos,ocarmos,rcarmos,atarmos,utarmos,ltarmos,ptarmos,etarmos,otarmos,scarmos,rtarmos,ncarmos,ecarmos,ctarmos,ucarmos,xtarmos¦5:eitarmos,ditarmos,vitarmos,sitarmos,tacarmos,litarmos,ritarmos,mitarmos,citarmos,pitarmos,lacarmos,gitarmos¦2çar:alcarmos",
      "ex": "1ormos:pôr¦2carmos:coçar,roçar,laçar¦3carmos:calçar,forçar,atiçar¦2mos:ir¦3mos:dar¦5mos:citar,tacar,fitar,sacar,ditar¦7mos:habitar,atracar¦4mos:atar¦6mos:quitar¦8mos:inculcar"
    },
    "secondPlural": {
      "fwd": "des:¦2cardes:tiçar",
      "both": "3cardes:braçar¦coitardes:çoitar",
      "rev": "2:erdes,irdes,ordes¦3:mardes,dardes,lardes,gardes,çardes,rardes,oardes,hardes,sardes,jardes,pardes,bardes,zardes,nardes,iardes,uardes,vardes,eardes,xardes,fardes¦4:stardes,ntardes,icardes,ocardes,rcardes,atardes,utardes,ltardes,ptardes,etardes,otardes,scardes,rtardes,ncardes,ecardes,ctardes,ucardes,xtardes¦5:eitardes,ditardes,vitardes,sitardes,tacardes,litardes,ritardes,mitardes,citardes,pitardes,lacardes,gitardes¦2çar:alcardes",
      "ex": "1ordes:pôr¦2cardes:coçar,roçar,laçar¦3cardes:calçar,forçar,atiçar¦2des:ir¦3des:dar¦5des:citar,tacar,fitar,sacar,ditar¦7des:habitar,atracar¦4des:atar¦6des:quitar¦8des:inculcar"
    },
    "thirdPlural": {
      "fwd": "em:¦2carem:tiçar",
      "both": "3carem:braçar¦2írem:buir,ruir,tuir,nuir,luir,suir¦1írem:air¦coitarem:çoitar",
      "rev": "2:erem,irem,orem¦3:marem,darem,larem,garem,çarem,rarem,oarem,harem,sarem,jarem,parem,barem,zarem,narem,iarem,uarem,varem,earem,xarem,farem¦4:starem,ntarem,icarem,ocarem,rcarem,atarem,utarem,ltarem,ptarem,etarem,otarem,scarem,rtarem,ncarem,ecarem,ctarem,ucarem,xtarem¦5:eitarem,ditarem,vitarem,sitarem,tacarem,litarem,ritarem,mitarem,citarem,pitarem,lacarem,gitarem¦ir:írem¦2çar:alcarem",
      "ex": "1orem:pôr¦2carem:coçar,roçar,laçar¦4írem:arguir¦3carem:calçar,forçar,atiçar¦2írem:ruir,puir¦2em:ir¦3em:dar¦5em:citar,tacar,fitar,sacar,ditar¦7em:habitar,atracar¦4em:atar¦6em:quitar¦8em:inculcar"
    }
  },
  "gerunds": {
    "gerunds": {
      "fwd": "",
      "both": "3cando:braçar¦ndo:r",
      "rev": "",
      "ex": "1ondo:pôr¦2cando:coçar"
    }
  },
  "pastParticiple": {
    "pastParticiple": {
      "fwd": "ido:er¦osto:ôr¦1to:izer¦2do:tir,mir,dir,bir,gir,zir¦3do:rrir,erir",
      "both": "5do,entregue:tregar¦5ndo:tervir¦4do:utrir,eguir¦4do,inserto:serir¦4ído:minuir¦4ndo:rovir¦4do,impresso:rimir¦3do:orir,arir,irir,ssir,prir¦3ndo:dvir,nvir¦3ido,eleito:leger¦3cado:braçar¦3do,salvo:lvar¦2ído:buir,tuir,luir,ruir,suir¦2do:pir,nir,lir¦2ito:crever¦1ido,roto:per¦1eito:fazer¦1ído:air,oer¦1sto:or¦1erto:brir¦1do:ar",
      "rev": "r:ndo,do ou ganho,do, pago,do,aceito,do ou gasto,do,solto,do,extinto¦er:ido,morto,isto,ido,preso,ido,aceso¦1er:vido,cido,xido,hido¦1r:ado,morto,ado,expresso¦2er:omido,azido,ndido,abido,ebido,rdido,egido,frido,rrido,btido,emido,mbido¦2zer:dito¦3r:rtido,rmido,uvido,idido,stido,ugido,ngido,umido,itido,utido,rgido,uzido,agido,udido¦3er:uerido,ontido,retido,metido,bstido,batido¦4r:entido,rigido,ferido,ervido,petido,gerido,letido,pedido,xigido,nguido,lodido,andido¦5r:rantido,fundido,gredido¦5er:nvertido",
      "ex": "1do:ir¦1eito:fazer¦2ndo:vir¦1isto:ver¦2do:rir¦4do:ouvir,pedir,subir,medir,ferir,latir¦5do ou ganho:ganhar¦4ido,morto:morrer¦4do, pago:pagar¦4isto:prever¦5do:servir,sorrir,aderir¦3isto:rever¦6do,aceito:aceitar¦4do,morto:matar¦5ido,preso:prender¦5ido,aceso:acender¦8do,expresso:expressar¦9do:distinguir,prescindir¦5do ou gasto:gastar¦5do,solto:soltar¦8do,extinto:extinguir¦2cado:coçar¦1ido:ser,ter,ler¦3ido:poder,valer,bater,deter,ceder,feder,reter,meter,viger¦1osto:pôr¦2to:dizer¦3do:agir¦4ido:manter,erguer¦2ido:crer,ater¦6do:invadir,proibir"
    }
  }
}