export default {
  ones: [
    [1, 'um', 'primeiro'],    // [1, 'uma'],
    [2, 'dois', 'segundo'],    // [2, 'duos'],
    [3, 'três', 'terceiro'],
    [4, 'quatro', 'quarto'],
    [5, 'cinco', 'quinto'],
    [6, 'seis', 'sexto'],
    [7, 'sete', 'sétimo'],
    [8, 'oito', 'oitavo'],
    [9, 'nove', 'nono'],
    [10, 'dez', 'décimo'],
    [11, 'onze'],
    [12, 'doze'],
    [13, 'treze'],
    [14, 'catorze'],
    [15, 'quinze'],
    [16, 'dezesseis'],//    [16, 'dezasseis'],
    [17, 'dezessete'],//    [17, 'dezassete'],
    [18, 'dezoito'],
    [19, 'dezenove'],//    [19, 'dezanove'],
  ],
  tens: [
    [20, 'vinte', 'vigésimo'],
    [30, 'trinta', 'trigésimo'],
    [40, 'quarenta', 'quadragésimo'],
    [50, 'cinquenta', 'quinquagésimo'],
    [50, 'cinquenta', 'qüingentésimo'],
    [60, 'sessenta', 'sexagésimo'],
    [70, 'setenta', 'septuagésimo'],
    [80, 'oitenta', 'octogésimo'],
    [90, 'noventa', 'nonagésimo'],
  ],
  hundreds: [
    [100, 'cem', 'centésimo'],
    [200, 'duzentos', 'ducentésimo'],
    [300, 'trezentos', 'tricentésimo'],
    [300, 'trezentos', 'trecentésimo'],
    [400, 'quatrocentos', 'quadringentésimo'],
    [400, 'quatrocentos', 'quatrocentos'],
    [500, 'quinhentos', 'quincentésimo'],
    [500, 'quinhentos', ''],
    [600, 'seiscentos', 'sexcentésimo'],
    [600, 'seiscentos', ''],
    [700, 'setecentos', 'setingentésimo'],
    [700, 'setecentos', ''],
    [800, 'oitocentos', 'octingentésimo'],
    [800, 'oitocentos', ''],
    [900, 'novecentos', 'nongentésimo'],
  ],
  multiples: [
    [1000, 'mil', 'milésimo'],
    [1000000, 'milhão', 'milionésimo'],
    [1000000000, 'bilhão', 'bilionésimo'],
  ]
}