export default {
  ones: [
    [1, 'um/uma'],
    [2, 'dois/duas'],
    [3, 'três'],
    [4, 'quatro'],
    [5, 'cinco'],
    [6, 'seis'],
    [7, 'sete'],
    [8, 'oito'],
    [9, 'nove'],
    [10, 'dez'],
    [11, 'onze'],
    [12, 'doze'],
    [13, 'treze'],
    [14, 'catorze'],
    [15, 'quinze'],
    [16, 'dezesseis/dezasseis'],
    [17, 'dezassete/dezessete'],
    [18, 'dezoito'],
    [19, 'dezanove/dezenove'],
  ],
  tens: [
    [20, 'vinte'],
    [30, 'trinta'],
    [40, 'quarenta'],
    [50, 'cinquenta'],
    [60, 'sessenta'],
    [70, 'setenta'],
    [80, 'oitenta'],
    [81, 'oitenta e um/uma'],
    [82, 'oitenta e dois/duas'],
    [83, 'oitenta e três'],
    [84, 'oitenta e quatro'],
    [85, 'oitenta e cinco'],
    [86, 'oitenta e seis'],
    [87, 'oitenta e sete'],
    [88, 'oitenta e oito'],
    [89, 'oitenta e nove'],
    [90, 'noventa'],
    [91, 'noventa e um/uma'],
    [92, 'noventa e dois/duas'],
    [93, 'noventa e três'],
    [94, 'noventa e quatro'],
    [95, 'noventa e cinco'],
    [96, 'noventa e seis'],
    [97, 'noventa e sete'],
    [98, 'noventa e oito'],
    [99, 'noventa e nove'],
    [100, 'cem'],
  ]