// https://pt.wiktionary.org/wiki/Ap%C3%AAndice:Combina%C3%A7%C3%B5es_e_contra%C3%A7%C3%B5es_do_portugu%C3%AAs
export default [
  // preposittion-article
  { word: 'do', out: ['de', 'o'] },
  { word: 'da', out: ['de', 'a'] },
  { word: 'dos', out: ['de', 'os'] },
  { word: 'das', out: ['de', 'as'] },

  { word: 'no', out: ['em', 'o'] },
  { word: 'na', out: ['em', 'a'] },
  // { word: 'nos', out: ['em', 'os'] },
  { word: 'nas', out: ['em', 'as'] },

  { word: 'pelo', out: ['por', 'o'] },
  { word: 'pela', out: ['por', 'a'] },
  { word: 'pelos', out: ['por', 'os'] },
  { word: 'pelas', out: ['por', 'as'] },

  { word: 'ao', out: ['a', 'o'] },
  { word: 'à', out: ['a', 'a'] },
  { word: 'aos', out: ['a', 'os'] },
  { word: 'às', out: ['a', 'as'] },

  { word: 'pro', out: ['para', 'o'] },
  { word: 'prò', out: ['para', 'o'] },
  { word: 'prà', out: ['para', 'a'] },
  { word: 'pros', out: ['para', 'os'] },
  { word: 'pròs', out: ['para', 'os'] },
  { word: 'pràs', out: ['para', 'as'] },

  { word: 'cò', out: ['com', 'o'] },
  { word: 'coa', out: ['com', 'a'] },
  { word: 'còs', out: ['com', 'os'] },
  { word: 'coas', out: ['com', 'as'] },

  // 
  { word: 'dum', out: ['de', 'um'] },
  { word: 'duma', out: ['de', 'uma'] },
  { word: 'duns', out: ['de', 'uns'] },
  { word: 'dumas', out: ['de', 'umas'] },

  { word: 'num', out: ['em', 'um'] },
  { word: 'numa', out: ['em', 'uma'] },
  { word: 'nuns', out: ['em', 'uns'] },
  { word: 'numas', out: ['em', 'umas'] },

  { word: 'prum', out: ['para', 'um'] },
  { word: 'pruma', out: ['para', 'uma'] },
  { word: 'pruns', out: ['para', 'uns'] },
  { word: 'prumas', out: ['para', 'umas'] },

  { word: 'cum', out: ['com', 'um'] },
  { word: 'cuma', out: ['com', 'uma'] },
  { word: 'cuns', out: ['com', 'uns'] },
  { word: 'cumas', out: ['com', 'umas'] },

  { word: 'à', out: ['a', 'a'] },
  { word: 'às', out: ['a', 'as'] },
  { word: 'ao', out: ['a', 'o'] },
  { word: 'aos', out: ['a', 'os'] },
  { word: 'coa', out: ['com', 'a'] },
  { word: 'coas', out: ['com', 'as'] },
  { word: 'co', out: ['com', 'o'] },
  { word: 'cos', out: ['com', 'os'] },
  { word: 'do', out: ['de', 'o'] },
  { word: 'da', out: ['de', 'a'] },
  { word: 'dos', out: ['de', 'os'] },
  { word: 'das', out: ['de', 'as'] },
  { word: 'no', out: ['em', 'o'] },
  { word: 'na', out: ['em', 'a'] },
  // { word: 'nos', out: ['em', 'os'] },
  { word: 'nas', out: ['em', 'as'] },
  { word: 'pro', out: ['para', 'o'] },
  { word: 'pra', out: ['para', 'a'] },
  { word: 'pros', out: ['para', 'os'] },
  { word: 'pras', out: ['para', 'as'] },
  { word: 'pelo', out: ['por', 'o'] },
  { word: 'pela', out: ['por', 'a'] },
  { word: 'pelos', out: ['por', 'os'] },
  { word: 'pelas', out: ['por', 'as'] },
  { word: 'cum', out: ['com', 'um'] },
  { word: 'cuns', out: ['com', 'uns'] },
  { word: 'cuma', out: ['com', 'uma'] },
  { word: 'cumas', out: ['com', 'umas'] },
  { word: 'dum', out: ['de', 'um'] },
  { word: 'duns', out: ['de', 'uns'] },
  { word: 'duma', out: ['de', 'uma'] },
  { word: 'dumas', out: ['de', 'umas'] },
  { word: 'num', out: ['em', 'um'] },
  { word: 'nuns', out: ['em', 'uns'] },
  { word: 'numa', out: ['em', 'uma'] },
  { word: 'numas', out: ['em', 'umas'] },
  { word: 'prum', out: ['para', 'um'] },
  { word: 'pruns', out: ['para', 'uns'] },
  { word: 'pruma', out: ['para', 'uma'] },
  { word: 'prumas', out: ['para', 'umas'] },
  { word: 'comigo', out: ['com', 'mim'] },
  { word: 'contigo', out: ['com', 'ti'] },
  { word: 'consigo', out: ['com', 'si'] },
  { word: 'conosco', out: ['com', 'nós'] },
  { word: 'convosco', out: ['com', 'vós'] },
  { word: 'dele', out: ['de', 'ele'] },
  { word: 'dela', out: ['de', 'ela'] },
  { word: 'deles', out: ['de', 'eles'] },
  { word: 'delas', out: ['de', 'elas'] },
  { word: 'nele', out: ['em', 'ele'] },
  { word: 'nela', out: ['em', 'ela'] },
  { word: 'neles', out: ['em', 'eles'] },
  { word: 'nelas', out: ['em', 'elas'] },
  { word: 'àquele', out: ['a', 'aquele'] },
  { word: 'àquela', out: ['a', 'aquela'] },
  { word: 'àqueles', out: ['a', 'aqueles'] },
  { word: 'àquelas', out: ['a', 'aquelas'] },
  { word: 'àquilo', out: ['a', 'aquilo'] },
  { word: 'deste', out: ['de', 'este'] },
  { word: 'desta', out: ['de', 'esta'] },
  { word: 'destes', out: ['de', 'estes'] },
  { word: 'destas', out: ['de', 'estas'] },
  { word: 'disto', out: ['de', 'isto'] },
  { word: 'desse', out: ['de', 'esse'] },
  { word: 'dessa', out: ['de', 'essa'] },
  { word: 'desses', out: ['de', 'esses'] },
  { word: 'dessas', out: ['de', 'essas'] },
  { word: 'disso', out: ['de', 'isso'] },
  { word: 'daquele', out: ['de', 'aquele'] },
  { word: 'daquela', out: ['de', 'aquela'] },
  { word: 'daqueles', out: ['de', 'aqueles'] },
  { word: 'daquelas', out: ['de', 'aquelas'] },
  { word: 'daquilo', out: ['de', 'aquilo'] },
  { word: 'neste', out: ['em', 'este'] },
  { word: 'nesta', out: ['em', 'esta'] },
  { word: 'nestes', out: ['em', 'estes'] },
  { word: 'nestas', out: ['em', 'estas'] },
  { word: 'nisto', out: ['em', 'isto'] },
  { word: 'nesse', out: ['em', 'esse'] },
  { word: 'nessa', out: ['em', 'essa'] },
  { word: 'nesses', out: ['em', 'esses'] },
  { word: 'nessas', out: ['em', 'essas'] },
  { word: 'nisso', out: ['em', 'isso'] },
  { word: 'naquele', out: ['em', 'aquele'] },
  { word: 'naquela', out: ['em', 'aquela'] },
  { word: 'naqueles', out: ['em', 'aqueles'] },
  { word: 'naquelas', out: ['em', 'aquelas'] },
  { word: 'naquilo', out: ['em', 'aquilo'] },
  { word: 'doutro', out: ['de', 'outro'] },
  { word: 'doutra', out: ['de', 'outra'] },
  { word: 'doutros', out: ['de', 'outros'] },
  { word: 'doutras', out: ['de', 'outras'] },
  { word: 'doutrem', out: ['de', 'outrem'] },
  { word: 'doutrora', out: ['de', 'outrora'] },
  { word: 'dalgum', out: ['de', 'algum'] },
  { word: 'dalguma', out: ['de', 'alguma'] },
  { word: 'dalguns', out: ['de', 'alguns'] },
  { word: 'dalgumas', out: ['de', 'algumas'] },
  { word: 'dalguém', out: ['de', 'alguém'] },
  { word: 'dalgo', out: ['de', 'algo'] },
  { word: 'dalgures', out: ['de', 'algures'] },
  { word: 'dalhures', out: ['de', 'alhures'] },
  { word: 'noutro', out: ['em', 'outro'] },
  { word: 'noutra', out: ['em', 'outra'] },
  { word: 'noutros', out: ['em', 'outros'] },
  { word: 'noutras', out: ['em', 'outras'] },
  { word: 'noutrem', out: ['em', 'outrem'] },
  { word: 'nalgum', out: ['em', 'algum'] },
  { word: 'nalguma', out: ['em', 'alguma'] },
  { word: 'nalguns', out: ['em', 'alguns'] },
  { word: 'nalgumas', out: ['em', 'algumas'] },
  { word: 'nalguém', out: ['em', 'alguém'] },
  { word: 'aonde', out: ['a', 'onde'] },
  { word: 'daqui', out: ['de', 'aqui'] },
  { word: 'daí', out: ['de', 'aí'] },
  { word: 'dali', out: ['de', 'ali'] },
  { word: 'daquém', out: ['de', 'aquém'] },
  { word: 'dalém', out: ['de', 'além'] },
  { word: 'dentre', out: ['de', 'entre'] },
  { word: 'dantes', out: ['de', 'antes'] },
  { word: 'dacolá', out: ['de', 'acolá'] },
  { word: 'donde', out: ['de', 'onde'] },
  { word: 'pronde', out: ['para', 'onde'] },
  { word: 'pelaí', out: ['por', 'aí'] },

  { word: 'estoutro', out: ['este', 'outro'] },
  { word: 'estoutra', out: ['esta', 'outra'] },
  { word: 'estoutros', out: ['estes', 'outros'] },
  { word: 'estoutras', out: ['estas', 'outras'] },
  { word: 'essoutro', out: ['esse', 'outro'] },
  { word: 'essoutra', out: ['essa', 'outra'] },
  { word: 'essoutros', out: ['esses', 'outros'] },
  { word: 'essoutras', out: ['essas', 'outras'] },
  { word: 'aqueloutro', out: ['aquele', 'outro'] },
  { word: 'aqueloutra', out: ['aquela', 'outra'] },
  { word: 'aqueloutros', out: ['aqueles', 'outros'] },
  { word: 'aqueloutras', out: ['aquelas', 'outras'] },

  { word: 'doravante', out: ['de', 'ora', 'avante'] },
  { word: 'destoutro', out: ['de', 'este', 'outro'] },
  { word: 'destoutra', out: ['de', 'esta', 'outra'] },
  { word: 'destoutros', out: ['de', 'estes', 'outros'] },
  { word: 'destoutras', out: ['de', 'estas', 'outras'] },
  { word: 'dessoutro', out: ['de', 'esse', 'outro'] },
  { word: 'dessoutra', out: ['de', 'essa', 'outra'] },
  { word: 'dessoutros', out: ['de', 'esses', 'outros'] },
  { word: 'dessoutras', out: ['de', 'essas', 'outras'] },
  { word: 'daqueloutro', out: ['de', 'aquele', 'outro'] },
  { word: 'daqueloutra', out: ['de', 'aquela', 'outra'] },
  { word: 'daqueloutros', out: ['de', 'aqueles', 'outros'] },
  { word: 'daqueloutras', out: ['de', 'aquelas', 'outras'] },
  { word: 'nestoutro', out: ['em', 'este', 'outro'] },
  { word: 'nestoutra', out: ['em', 'esta', 'outra'] },
  { word: 'nestoutros', out: ['em', 'estes', 'outros'] },
  { word: 'nestoutras', out: ['em', 'estas', 'outras'] },
  { word: 'nessoutro', out: ['em', 'esse', 'outro'] },
  { word: 'nessoutra', out: ['em', 'essa', 'outra'] },
  { word: 'nessoutros', out: ['em', 'esses', 'outros'] },
  { word: 'nessoutras', out: ['em', 'essas', 'outras'] },
  { word: 'naqueloutro', out: ['em', 'aquele', 'outro'] },
  { word: 'naqueloutra', out: ['em', 'aquela', 'outra'] },
  { word: 'naqueloutros', out: ['em', 'aqueles', 'outros'] },
  { word: 'naqueloutras', out: ['em', 'aquelas', 'outras'] },
]


