// https://pt.wiktionary.org/wiki/Ap%C3%AAndice:Combina%C3%A7%C3%B5es_e_contra%C3%A7%C3%B5es_do_portugu%C3%AAs
export default [
  // preposittion-article
  { word: 'do', to: ['de', 'o'] },
  { word: 'da', to: ['de', 'a'] },
  { word: 'dos', to: ['de', 'os'] },
  { word: 'das', to: ['de', 'as'] },

  { word: 'no', to: ['em', 'o'] },
  { word: 'na', to: ['em', 'a'] },
  { word: 'nos', to: ['em', 'os'] },
  { word: 'nas', to: ['em', 'as'] },

  { word: 'pelo', to: ['por', 'o'] },
  { word: 'pela', to: ['por', 'a'] },
  { word: 'pelos', to: ['por', 'os'] },
  { word: 'pelas', to: ['por', 'as'] },

  { word: 'ao', to: ['a', 'o'] },
  { word: 'à', to: ['a', 'a'] },
  { word: 'aos', to: ['a', 'os'] },
  { word: 'às', to: ['a', 'as'] },

  { word: 'pro', to: ['para', 'o'] },
  { word: 'prò', to: ['para', 'o'] },
  { word: 'prà', to: ['para', 'a'] },
  { word: 'pros', to: ['para', 'os'] },
  { word: 'pròs', to: ['para', 'os'] },
  { word: 'pràs', to: ['para', 'as'] },

  { word: 'cò', to: ['com', 'o'] },
  { word: 'coa', to: ['com', 'a'] },
  { word: 'còs', to: ['com', 'os'] },
  { word: 'coas', to: ['com', 'as'] },

  // 
  { word: 'dum', to: ['de', 'um'] },
  { word: 'duma', to: ['de', 'uma'] },
  { word: 'duns', to: ['de', 'uns'] },
  { word: 'dumas', to: ['de', 'umas'] },

  { word: 'num', to: ['em', 'um'] },
  { word: 'numa', to: ['em', 'uma'] },
  { word: 'nuns', to: ['em', 'uns'] },
  { word: 'numas', to: ['em', 'umas'] },

  { word: 'prum', to: ['para', 'um'] },
  { word: 'pruma', to: ['para', 'uma'] },
  { word: 'pruns', to: ['para', 'uns'] },
  { word: 'prumas', to: ['para', 'umas'] },

  { word: 'cum', to: ['com', 'um'] },
  { word: 'cuma', to: ['com', 'uma'] },
  { word: 'cuns', to: ['com', 'uns'] },
  { word: 'cumas', to: ['com', 'umas'] },

  { word: 'à', to: ['a', 'a'] },
  { word: 'às', to: ['a', 'as'] },
  { word: 'ao', to: ['a', 'o'] },
  { word: 'aos', to: ['a', 'os'] },
  { word: 'coa', to: ['com', 'a'] },
  { word: 'coas', to: ['com', 'as'] },
  { word: 'co', to: ['com', 'o'] },
  { word: 'cos', to: ['com', 'os'] },
  { word: 'do', to: ['de', 'o'] },
  { word: 'da', to: ['de', 'a'] },
  { word: 'dos', to: ['de', 'os'] },
  { word: 'das', to: ['de', 'as'] },
  { word: 'no', to: ['em', 'o'] },
  { word: 'na', to: ['em', 'a'] },
  { word: 'nos', to: ['em', 'os'] },
  { word: 'nas', to: ['em', 'as'] },
  { word: 'pro', to: ['para', 'o'] },
  { word: 'pra', to: ['para', 'a'] },
  { word: 'pros', to: ['para', 'os'] },
  { word: 'pras', to: ['para', 'as'] },
  { word: 'pelo', to: ['por', 'o'] },
  { word: 'pela', to: ['por', 'a'] },
  { word: 'pelos', to: ['por', 'os'] },
  { word: 'pelas', to: ['por', 'as'] },
  { word: 'cum', to: ['com', 'um'] },
  { word: 'cuns', to: ['com', 'uns'] },
  { word: 'cuma', to: ['com', 'uma'] },
  { word: 'cumas', to: ['com', 'umas'] },
  { word: 'dum', to: ['de', 'um'] },
  { word: 'duns', to: ['de', 'uns'] },
  { word: 'duma', to: ['de', 'uma'] },
  { word: 'dumas', to: ['de', 'umas'] },
  { word: 'num', to: ['em', 'um'] },
  { word: 'nuns', to: ['em', 'uns'] },
  { word: 'numa', to: ['em', 'uma'] },
  { word: 'numas', to: ['em', 'umas'] },
  { word: 'prum', to: ['para', 'um'] },
  { word: 'pruns', to: ['para', 'uns'] },
  { word: 'pruma', to: ['para', 'uma'] },
  { word: 'prumas', to: ['para', 'umas'] },
  { word: 'comigo', to: ['com', 'mim'] },
  { word: 'contigo', to: ['com', 'ti'] },
  { word: 'consigo', to: ['com', 'si'] },
  { word: 'conosco', to: ['com', 'nós'] },
  { word: 'convosco', to: ['com', 'vós'] },
  { word: 'dele', to: ['de', 'ele'] },
  { word: 'dela', to: ['de', 'ela'] },
  { word: 'deles', to: ['de', 'eles'] },
  { word: 'delas', to: ['de', 'elas'] },
  { word: 'nele', to: ['em', 'ele'] },
  { word: 'nela', to: ['em', 'ela'] },
  { word: 'neles', to: ['em', 'eles'] },
  { word: 'nelas', to: ['em', 'elas'] },
  { word: 'àquele', to: ['a', 'aquele'] },
  { word: 'àquela', to: ['a', 'aquela'] },
  { word: 'àqueles', to: ['a', 'aqueles'] },
  { word: 'àquelas', to: ['a', 'aquelas'] },
  { word: 'àquilo', to: ['a', 'aquilo'] },
  { word: 'deste', to: ['de', 'este'] },
  { word: 'desta', to: ['de', 'esta'] },
  { word: 'destes', to: ['de', 'estes'] },
  { word: 'destas', to: ['de', 'estas'] },
  { word: 'disto', to: ['de', 'isto'] },
  { word: 'desse', to: ['de', 'esse'] },
  { word: 'dessa', to: ['de', 'essa'] },
  { word: 'desses', to: ['de', 'esses'] },
  { word: 'dessas', to: ['de', 'essas'] },
  { word: 'disso', to: ['de', 'isso'] },
  { word: 'daquele', to: ['de', 'aquele'] },
  { word: 'daquela', to: ['de', 'aquela'] },
  { word: 'daqueles', to: ['de', 'aqueles'] },
  { word: 'daquelas', to: ['de', 'aquelas'] },
  { word: 'daquilo', to: ['de', 'aquilo'] },
  { word: 'neste', to: ['em', 'este'] },
  { word: 'nesta', to: ['em', 'esta'] },
  { word: 'nestes', to: ['em', 'estes'] },
  { word: 'nestas', to: ['em', 'estas'] },
  { word: 'nisto', to: ['em', 'isto'] },
  { word: 'nesse', to: ['em', 'esse'] },
  { word: 'nessa', to: ['em', 'essa'] },
  { word: 'nesses', to: ['em', 'esses'] },
  { word: 'nessas', to: ['em', 'essas'] },
  { word: 'nisso', to: ['em', 'isso'] },
  { word: 'naquele', to: ['em', 'aquele'] },
  { word: 'naquela', to: ['em', 'aquela'] },
  { word: 'naqueles', to: ['em', 'aqueles'] },
  { word: 'naquelas', to: ['em', 'aquelas'] },
  { word: 'naquilo', to: ['em', 'aquilo'] },
  { word: 'doutro', to: ['de', 'outro'] },
  { word: 'doutra', to: ['de', 'outra'] },
  { word: 'doutros', to: ['de', 'outros'] },
  { word: 'doutras', to: ['de', 'outras'] },
  { word: 'doutrem', to: ['de', 'outrem'] },
  { word: 'doutrora', to: ['de', 'outrora'] },
  { word: 'dalgum', to: ['de', 'algum'] },
  { word: 'dalguma', to: ['de', 'alguma'] },
  { word: 'dalguns', to: ['de', 'alguns'] },
  { word: 'dalgumas', to: ['de', 'algumas'] },
  { word: 'dalguém', to: ['de', 'alguém'] },
  { word: 'dalgo', to: ['de', 'algo'] },
  { word: 'dalgures', to: ['de', 'algures'] },
  { word: 'dalhures', to: ['de', 'alhures'] },
  { word: 'noutro', to: ['em', 'outro'] },
  { word: 'noutra', to: ['em', 'outra'] },
  { word: 'noutros', to: ['em', 'outros'] },
  { word: 'noutras', to: ['em', 'outras'] },
  { word: 'noutrem', to: ['em', 'outrem'] },
  { word: 'nalgum', to: ['em', 'algum'] },
  { word: 'nalguma', to: ['em', 'alguma'] },
  { word: 'nalguns', to: ['em', 'alguns'] },
  { word: 'nalgumas', to: ['em', 'algumas'] },
  { word: 'nalguém', to: ['em', 'alguém'] },
  { word: 'aonde', to: ['a', 'onde'] },
  { word: 'daqui', to: ['de', 'aqui'] },
  { word: 'daí', to: ['de', 'aí'] },
  { word: 'dali', to: ['de', 'ali'] },
  { word: 'daquém', to: ['de', 'aquém'] },
  { word: 'dalém', to: ['de', 'além'] },
  { word: 'dentre', to: ['de', 'entre'] },
  { word: 'dantes', to: ['de', 'antes'] },
  { word: 'dacolá', to: ['de', 'acolá'] },
  { word: 'donde', to: ['de', 'onde'] },
  { word: 'pronde', to: ['para', 'onde'] },
  { word: 'pelaí', to: ['por', 'aí'] },

  { word: 'estoutro', to: ['este', 'outro'] },
  { word: 'estoutra', to: ['esta', 'outra'] },
  { word: 'estoutros', to: ['estes', 'outros'] },
  { word: 'estoutras', to: ['estas', 'outras'] },
  { word: 'essoutro', to: ['esse', 'outro'] },
  { word: 'essoutra', to: ['essa', 'outra'] },
  { word: 'essoutros', to: ['esses', 'outros'] },
  { word: 'essoutras', to: ['essas', 'outras'] },
  { word: 'aqueloutro', to: ['aquele', 'outro'] },
  { word: 'aqueloutra', to: ['aquela', 'outra'] },
  { word: 'aqueloutros', to: ['aqueles', 'outros'] },
  { word: 'aqueloutras', to: ['aquelas', 'outras'] },

  { word: 'doravante', to: ['de', 'ora', 'avante'] },
  { word: 'destoutro', to: ['de', 'este', 'outro'] },
  { word: 'destoutra', to: ['de', 'esta', 'outra'] },
  { word: 'destoutros', to: ['de', 'estes', 'outros'] },
  { word: 'destoutras', to: ['de', 'estas', 'outras'] },
  { word: 'dessoutro', to: ['de', 'esse', 'outro'] },
  { word: 'dessoutra', to: ['de', 'essa', 'outra'] },
  { word: 'dessoutros', to: ['de', 'esses', 'outros'] },
  { word: 'dessoutras', to: ['de', 'essas', 'outras'] },
  { word: 'daqueloutro', to: ['de', 'aquele', 'outro'] },
  { word: 'daqueloutra', to: ['de', 'aquela', 'outra'] },
  { word: 'daqueloutros', to: ['de', 'aqueles', 'outros'] },
  { word: 'daqueloutras', to: ['de', 'aquelas', 'outras'] },
  { word: 'nestoutro', to: ['em', 'este', 'outro'] },
  { word: 'nestoutra', to: ['em', 'esta', 'outra'] },
  { word: 'nestoutros', to: ['em', 'estes', 'outros'] },
  { word: 'nestoutras', to: ['em', 'estas', 'outras'] },
  { word: 'nessoutro', to: ['em', 'esse', 'outro'] },
  { word: 'nessoutra', to: ['em', 'essa', 'outra'] },
  { word: 'nessoutros', to: ['em', 'esses', 'outros'] },
  { word: 'nessoutras', to: ['em', 'essas', 'outras'] },
  { word: 'naqueloutro', to: ['em', 'aquele', 'outro'] },
  { word: 'naqueloutra', to: ['em', 'aquela', 'outra'] },
  { word: 'naqueloutros', to: ['em', 'aqueles', 'outros'] },
  { word: 'naqueloutras', to: ['em', 'aquelas', 'outras'] },
]


